### ISSUE TITLE
mintty misbehaves with interactive programs like irb

### ISSUE THREAD

**Issue by monkeysuffrage** [mintty/mintty#619] opened 2016-12-31 05:21 UTC
When I run interactive programs like irb or pry I don't get a prompt. Irb says: "Switch to inspect mode" which I don't get from bash. I don't know what's going on but I miss mintty since I upgraded from Windows 7 to Windows 10.

This is for mintty 2.5.1 and 2.7.2

**Comment by mintty** [comment] 2017-01-01 11:29
It would be helpful in general to provide more information with an issue report; what are those programs and where are they installed? But I'm pretty sure this is a duplicate of #503, #238 and others, and basically #56.

**Closed by mintty** 2017-01-01 11:29 UTC

**Comment by mintty** [comment] 2019-12-16 23:44
Cygwin 3.1.0 has been released with ConPTY support.
