### ISSUE TITLE
Dragging from explorer to cygwin terminal is not putting the path into the terminal

### ISSUE THREAD

**Issue by AcademyOfF** [mintty/mintty#885] opened 2019-06-12 04:45 UTC
Hello!  I asked this on the cygwin mailing list first and they redirected me here.  Here's my issue: If I take a file from my windows explorer and drag it into my cygwin terminal, I believe it's supposed to expand the full path to that file in the terminal, but instead it has no effect.  I can reproduce this over and over again on my terminal.

I have a bunch of unrelated information to provide about the situation, but I'm happy to provide more if it's insufficient.

I'm not running mintty in administrator mode.

> What does "uname -a" tell you? (just for a start).

CYGWIN_NT-10.0 DESKTOP-CJB8HSU 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin 

>    $ cmd /c ver

Microsoft Windows [Version 10.0.17763.503]

>    $ uname -srvmo

CYGWIN_NT-10.0 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin

>    $ mintty --version

mintty 3.0.1 (x86_64-pc-cygwin)
© 2013/2019 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law. 

> My .minttyrc

BoldAsFont=no
FontHeight=20
RightClickAction=paste
Font=Courier New

I don't have a /etc/minttyrc

I have a huge high resolution screen and bad eyes.  It looks like this: https://imgur.com/ppTljLs

I made it that tall by changing the properties of the terminal and I did that by changing these settings: https://imgur.com/3zhCMEX

One thing I did change is this setting on windows: https://imgur.com/a/M0ckjZs

Installing older versions of mintty doesn't fix the issue.  I've tried 2.9.9 and 3.0.0.

> $ for o in -s -u -f -n -i; do locale $o; done
en_US
en_US
en_US
en_US
en_US

There are two things that I suspect could be the culprit.  I ran these two scripts after installing windows:

https://github.com/Sycnex/Windows10Debloater
https://github.com/alirobe/Reclaim-Windows10 

After that, I created a new user I login as and installed cygwin from the new user.  I remember having some issues with copy/paste after that on this new user account, but after running sfc /scannow twice, the problem went away and now when I run that command it says it didn't find any issues.

I start mintty with a shortcut and it runs this: C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico - 

Sorry for the dump of information.  I hope someone can help me with this.

**Comment by mintty** [comment] 2019-06-12 20:12
Thanks for collecting the symptoms here. As a workaround, you can of course also paste using the menu or the Shift+Insert shortcut.

**Comment by AcademyOfF** [comment] 2019-06-13 01:15
I don't think that's a workaround, because I don't have the path of the file in my clipboard.

**Comment by avih** [comment] 2019-06-13 04:03
I think he means that instead of dragging you can copy the file in explorer and paste it in mintty - which will paste the file path.

**Comment by AcademyOfF** [comment] 2019-06-13 04:04
Oh true, that does work.

**Comment by avih** [comment] 2019-06-13 04:13
Also, if you can afford, maybe you can try a new windows install in a virtual machine without those "cleanup scripts" (debloater, reclaim) and test if dragging works, then run these scripts and see if they indeed break it. If dragging worked but stopped working after those scripts then it means the fault is with one of those scripts.

**Comment by AcademyOfF** [comment] 2019-06-25 23:23
I just completely reinstalled my OS.  I've installed discord, jdownloader 2, firefox, chrome, and cygwin.  When I drag to mintty, it still acts the same way.  I had these programs installed earlier when drag&drop was working correctly.

I did not run those debloater scripts this time.

**Comment by mintty** [comment] 2019-06-26 09:45
Thanks for the info. Unfortunately this does not give us more info to chase down the issue.

**Comment by AcademyOfF** [comment] 2019-06-27 04:39
is there any info that would?  What else would you like to know?

**Comment by mintty** [comment] 2019-06-27 09:43
Do you have $APPDATA/mintty/config or ~/.config/mintty/config ?
Can you add debug printf's to winclip.c, to check whether functions dt_drop and paste_hdrop are activated while dragging?
Like, in function dt_drop: printf("dt_drop\n");

**Comment by mintty** [comment] 2019-06-27 10:29
You might also check whether the call of RegisterDragDrop (last statement in winclip.c) returns non-zero.

**Comment by AcademyOfF** [comment] 2019-06-29 18:38
> 
> 
> Do you have $APPDATA/mintty/config or ~/.config/mintty/config ?
I don't have either of those files
> Can you add debug printf's to winclip.c, to check whether functions dt_drop and paste_hdrop are activated while dragging?

I think you're asking me to download the source, modify those files, then compile the project from source?

**Comment by mintty** [comment] 2019-06-30 07:57
Yes, if that's feasible. You just need packages `gcc` and `make` and the mintty source package or a source zip download from here, no git required. Building mintty is straightforward, just invoke `make`. I can provide a drop-in source file for debugging if you're not familiar with sources.

**Comment by AcademyOfF** [comment] 2019-06-30 17:44
I think I could do that.  Should I be using cygwin's gcc to compile it, or is there a gcc for windows?  Where will the output print when I've compiled it?

**Comment by mintty** [comment] 2019-07-01 02:24
It's cygwin gcc. Start the instance from another mintty session where the output will go.

**Comment by mintty** [comment] 2019-08-08 08:08
Closing as not reproducible and due to lack of diagnostic information.

**Closed by mintty** 2019-08-08 08:08 UTC
Labels: help wanted
