### ISSUE TITLE
Mintty shows arrow sequence characters when clicking in a terminal

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#640] opened 2017-03-06 09:10 UTC
Hey,

Not sure the best way of titling this, but sometimes when you click out of a terminal window and click back in one ends up with a load of arrow sequences `^[[C` being inserted into the terminal. The screenshot below shows what I mean. This behaviour is seemingly random, but happens often and I haven't found another open issue specifically about this.

![image](https://cloud.githubusercontent.com/assets/2286713/23603291/63f5c612-024c-11e7-9f8c-f378843bade1.png)

**Comment by mintty** [comment] 2017-03-06 10:18
Please disable Options – Mouse – Clicks place command line cursor

"It's a feature, not a bug" :)
It's intended for the command line, though, or maybe other readline-driven input, not general input, so it's bound to cause problems.
In connection with the new scroll markers feature (#569), we could perhaps restrict the feature to actual command lines...

**Comment by mintty** [comment] 2017-05-30 10:27
The idea to suppress this conditionally by limiting it to the prompt line has some tricky caveats;
wrap-around on the prompt line would have to be handled in subtle ways...
So I'd prefer to not pursue this further unless urged to. Can we close the issue?

**Closed** 2017-08-02 16:17 UTC
