### ISSUE TITLE
Trails left by windows moving over mintty

### ISSUE THREAD

**Issue by fstearns** [mintty/mintty#576] opened 2016-08-15 20:15 UTC
I use a dark background color with mintty.  Since 2.4.2 release, I get trails when other windows move over mintty.  This is related to the removal of the PADDING offset for p.rcPaint.{left,top} in win_paint.

**Comment by mintty** [comment] 2016-08-16 19:20
Thanks for the report; however, I cannot reproduce any glitches. Also, tracing old vs. new values shows that the new ones reflect the respective terminal size precisely while the old don't always. Maybe it's different with specific settings; what font and font size do you use? Also please describe the "trails" more specifically. Maybe a screenshot?

**Comment by fstearns** [comment] 2016-08-16 20:06
--- settings from .minttyrc
BoldAsFont=-1
FontHeight=10
Rows=70
Font=Lucida Console
BackgroundColour=0,30,70
ForegroundColour=166,210,255
CursorType=block
Transparency=off

In this image, I moved a top window slowly to the right uncovering the mintty window, and at one point started moving up.  As an example, when p.rcPaint.left==8 and p.rcPaint.right == 9, then in term_invalidate left==1 and right==0.  The value of cell_width is 8.  If I define strange_calculation I don't get any trails.

![image](https://cloud.githubusercontent.com/assets/21045055/17713090/2b46d690-63c7-11e6-97f4-8f656d991f8c.png)

**Comment by fstearns** [comment] 2016-08-16 20:21
With Padding=0 in .minttyrc, I don't get any trails.
With Padding=3, I get:

![image](https://cloud.githubusercontent.com/assets/21045055/17714318/38c49536-63cd-11e6-8913-8f747da2ea79.png)

**Comment by fstearns** [comment] 2016-08-17 22:08
The system I am having this problem on is Windows 7
Windows 10 doesn't seem to have this problem, but I need to do more testing.

**Comment by mintty** [comment] 2016-08-18 16:14
Reproduced on Windows XP. I think the position you identified reveals the bug but the actual bug may be somewhere else. Will analyse.

**Comment by mintty** [comment] 2016-08-22 23:22
Fixed in 2.4.3.

**Closed by mintty** 2016-08-22 23:22 UTC
