### ISSUE TITLE
Tabbar broken since 3.6.5

### ISSUE THREAD

**Issue by k-takata** [mintty/mintty#1249] opened 2023-12-30 04:07 UTC
I use mintty with `TabBar=3`.
Since 3.6.5, switching the focus to another tab causes flickering and often doesn't switch to the expected tab.
Moreover, the mintty icon sometimes disappears from the taskbar.
I suppose that there is a race condition in hiding and showing background tabs.
![mintty-tabbar](https://github.com/mintty/mintty/assets/840186/8728ca81-ad77-4e4d-80fc-2a1e0192edea)

**Comment by mintty** [comment] 2024-01-01 18:14
This is duplicate of part of #1242. There is a workaround for it already, but it's a bit nasty. There are 3 possible changes and a weird set of 4 combinations of them fixes the issue while the others don't.
I haven't yet commited that as I'm stil fighting the other related issue, Ctrl+TAB failing after minimize/restore (step 5 in that issue) and maybe the fixes interfere...

**Comment by mintty** [comment] 2024-01-14 10:33
Revised tab switching. Testing would be appreciated.

**Comment by k-takata** [comment] 2024-01-22 01:37
Thank you. It works better than before. Flickering doesn't occur now.
However, it seems that the mintty icon still sometimes disappears from the taskbar. (It is acceptable for me, though.)

**Comment by mintty** [comment] 2024-02-24 20:57
Released 3.7.1.

**Closed by mintty** 2024-02-24 20:57 UTC
