### ISSUE TITLE
Using mintty with git, bash crashes on start up (Windows 7)

### ISSUE THREAD

**Issue by bdh2991** [mintty/mintty#555] opened 2016-05-27 14:56 UTC
Mintty was installed when I first installed git on my computer (I believe git 2.7).  For some reason now when I try to open up the git bash it just crashes: 

Exception: STATUS_ACCESS_VIOLATION at rip=00100405BAF
rax=FFFFFFFFFFFFFFFF rbx=00000000FFFFC490 rcx=0000000000000000
rdx=03FFFFFFFFFFFFFF rsi=000000010042DE00 rdi=00000000FFFFC48C
r8 =0000000000000001 r9 =0000000000000000 r10=8000000000000000
r11=000007FFFFFDE000 r12=000000010042DDA8 r13=000000010042E900
r14=00000000FFFFCB78 r15=00000000FFFFC5E0
rbp=00000000FFFFC498 rsp=00000000FFFFC450
program=C:\Program Files\Git\usr\bin\mintty.exe, pid 9096, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC498  00100405BAF (000FFFFC570, 000777F39F0, 00100410510, 00600000001)
000FFFFC570  0010041AC01 (001800CE622, 0000000002F, 00600042017, 00000008000)
000FFFFCCC0  00180047C0F (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0018004590C (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800459A4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

I don't remember changing anything with git or mintty before this happened...

I've tried re-installing git (2.8.3) but that didn't seem to change anything.

**Comment by mintty** [comment] 2016-05-28 16:34
If you didn't change anything, it's likely that this is a BLODA problem. Maybe you installed (a new version of) a virus scanner?
Can you compile and try the latest release on Git?

**Comment by fatefan** [comment] 2016-06-03 08:28
I've had the same problem.I use a Trojan scan software.I use 2.8.3 git.

**Comment by mintty** [comment] 2016-06-03 12:01
What are the actual symptoms? The new window opens and inside it you see the quoted error messages?

**Comment by bdh2991** [comment] 2016-06-03 14:18
In my case, this wasn't an issue with mintty.  Somehow the null device driver got stopped or deleted on my pc (https://msdn.microsoft.com/en-us/library/aa939249(v=winembedded.5).aspx).  Was able to fix it in the registry with a script and it is working fine now.

**Comment by bdh2991** [comment] 2016-06-03 15:36
Here is where i found the solution if anyone else is having the same issue: http://stackoverflow.com/questions/28941304/getting-errors-when-using-github-for-windows/34307471#34307471

**Comment by mintty** [comment] 2016-06-03 19:30
So can we close this issue here?

**Closed** 2016-06-05 13:40 UTC

**Comment by VaseemDeveloper** [comment] 2020-07-01 01:57
This problem is still coming in my windows 8 and I am not able to find a solution on how to fix it. Can you help.

**Comment by mintty** [comment] 2020-07-01 06:14
This appeared in 3.1.5; unfortunately, git bash currently ships with 3.1.6. The problem was fixed in 3.1.7.

**Comment by Muradalikhan** [comment] 2020-07-12 18:12
I have restored my computer and now when I open git bash here it creates mintty.exe file instead of opening  please help me out

**Comment by mintty** [comment] 2020-07-12 18:31
Please describe your issue more clearly. Also which version of git do you have?

**Comment by Muradalikhan** [comment] 2020-07-12 18:37
I have downloaded the latest one 2.27.0. the problem is in a start-up before my window restore it was working properly but now git bash doesn't open and it creates a file of mintty

**Comment by mintty** [comment] 2020-07-12 18:57
File mintty or mintty.exe? Where is it placed, what's its size/contents? You're running Windows 7?

**Comment by Muradalikhan** [comment] 2020-07-13 09:43
filename is **mintty.exe.stackdump** As I am opening git bash here at desktop it creates the file at the same location.
The size of the file is 4kb and the content  exists the following
```
Exception: STATUS_ACCESS_VIOLATION at eip=00140326
eax=00000000 ebx=0045028B ecx=0022C5CC edx=77BF70B4 esi=004A0410 edi=80000000
ebp=0022CB48 esp=0022C614 program=C:\Program Files\Git\usr\bin\mintty.exe, pid 310, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CB48  00140326 (200610E8, 200610F2, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace
```

I am using Windows 7.

**Comment by k-takata** [comment] 2020-07-13 09:48
It should be the same as #1014.

**Comment by Muradalikhan** [comment] 2020-07-13 19:02
I can't understand the problem from 3 days @k-takata  it creates a great headache for me now plz try to help me out of this irritating issue.

**Comment by mintty** [comment] 2020-07-13 20:01
Install a new pre-release [snapshot](https://wingit.blob.core.windows.net/files/index.html) of Git for Windows or wait for the next release.

**Comment by BrianInglis** [comment] 2020-07-14 03:36
@mintty included in last @git-for-windows release crashes - new pre-release candidate [available](https://github.com/git-for-windows/git/releases/tag/v2.28.0-rc0.windows.1)  4 days ago includes latest @mintty which does not crash
