### ISSUE TITLE
Can't run Python on Windows 10

### ISSUE THREAD

**Issue by TYZRPVX** [mintty/mintty#503] opened 2015-12-16 03:06 UTC
I installed mintty when I installed Git. Old version mintty can run Python when I type "python" in mintty, but  now I type "python" and mintty paused. Can I ask for some help about this?

**Comment by mintty** [comment] 2015-12-16 09:52
This is likely a duplicate of an interworking problem. I cannot say which, however, as you don't provide much information. Which is "old version" and which is current? Are both the ones packaged with Git for Windows? What Python do you run (cygwin or Windows)? So what does `mintty -V` say (old and new) and what does `python -V` say?

**Comment by TYZRPVX** [comment] 2015-12-17 08:39
$ mintty -V
mintty 2.0.3 (x86_64-pc-msys)
(C) 2015 Andy Koppe
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.

this is mintty - V shows.

python -V run normally. 

Sorry for my carelessness, I run Python normally in an old version git Bash, not old version mintty.

**Comment by mintty** [comment] 2015-12-17 12:39
So if `python -V` runs normally, what does it say?
Also, what does `type python` say?
Anyway,  with Python for Windows I can reproduce the behaviour, and it's a duplicate of #238, see also issues 481 and 380 for more explanation, as well as other duplicates of #56 like 230, 212, 158).

To run python from an MSys environment (which is what Git Bash is) you'd need to install an MSys package of python. A cygwin python might also work.

**Closed by mintty** 2015-12-17 12:39 UTC

**Comment by mintty** [comment] 2015-12-17 12:41
Not related to Windows 10, by the way; changing title.

**Comment by mintty** [comment] 2019-12-16 23:44
Cygwin 3.1.0 has been released with ConPTY support.
