### ISSUE TITLE
Solarized bold colors are gray

### ISSUE THREAD

**Issue by fniessen** [mintty/mintty#683] opened 2017-09-04 12:07 UTC
Dear all,

Any reason why most bold colors (green, yellow, blue, cyan) of Solarized are gray in MinTTY?

In my .zshrc, I do have:
- Oh-my-Zsh, and
- source ~/git/mintty-colors-solarized/mintty-solarized-dark.sh
  (obtained from repo https://github.com/karlin/mintty-colors-solarized.git)

Best regards!

**Comment by mintty** [comment] 2017-09-04 12:40
Please check whether it's a duplicate of #550 or duplicate of #647.

**Comment by fniessen** [comment] 2017-09-04 17:45
Dear mintty, it looks a lot like it's the same root cause, though it's about another theme.

But I'm not sure to understand the problem: it's the Solarized theme that's buggy?

Anybody having a correct Solarized theme for MinTTY?

**Comment by mintty** [comment] 2017-09-04 20:12
Look at the numeric values for bold green, yellow, blue, cyan in the theme you quoted:
The byte values for R/G/B are almost equal in them; yes, the theme is buggy.

**Closed by mintty** 2017-09-04 20:12 UTC

**Comment by fniessen** [comment] 2017-09-04 20:16
I don't understand why themes can be buggy... copying the right hexa values shouldn't be that hard.

Or there is something that I miss?

Anyway, thanks for looking at this!
