### ISSUE TITLE
calling mintty.exe with cmd.exe command line does not execute command given on command line

### ISSUE THREAD

**Issue by tps800** [mintty/mintty#1241] opened 2023-11-20 13:23 UTC
mintty: 3.7.0 (x86_64-pc-mysy)

In a `cmd.exe` window:
```
mintty.exe -d --geometry 260x43+0-0 -B void -h never -e \
  cmd.exe /c "$APPDATA\\KeePass\\script\\backup.cmd"
```

This opens mintty with a running cmd.exe, but does not execute the command handled over. The only message seen is "eepass" is not an executalbe command. I've tried for the command:
```
"$APPDATA\\KeePass\\script\\backup.cmd"
"%APPDATA%\\KeePass\\script\\backup.cmd"
"C:\\Users\\<username>\\AppData\\Roaming\\KeePass\\script\\backup.cmd"
"c/Users/<username>/AppData/Roaming/KeePass/script/backup.cmd"
```

but without luck. For the first two: "eePass is not an executable command", while the last both just seem to do nothing.

Commands like:
```
mintty.exe -d --geometry 260x43+0-0 -B void -h never -e \
  cmd.exe /c timeout 100
```

Are expected to work right out of the box, but they are not executed at all. Does mintty handle the command line parameters as expected? Or does it something like just taking the first white space separated command, ignoring the rest of the line?

**Comment by mintty** [comment] 2024-02-25 17:22
Duplicate of #1244. See there for explanation.

**Closed by mintty** 2024-02-25 17:22 UTC
