### ISSUE TITLE
Path syntax conversion when pasting pathname

### ISSUE THREAD

**Issue by waghcwb** [mintty/mintty#975] opened 2020-03-12 12:21 UTC
It is a common task to copy an path from Windows Explorer and then `cd` in that folder using the terminal. But when I copy an path from Windows Explorer it comes with backslashes (eg: `C:\Users\your-awesome-user\Documents`), so I need to manually convert to this `C:/Users/your-awesome-user/Documents` before I can `cd` in that folder.

**Comment by mintty** [comment] 2020-03-12 14:33
Duplicate of #785 and #644. Use drag-and-drop from Explorer to invoke path syntax conversion.

**Comment by mintty** [comment] 2020-03-12 14:37
There are shortcuts Shift+Insert and [Shift+]middle-mouse-click for pasting.
Actually, I could imagine to add variants Alt+Shift+Insert and Alt+[Shift+]middle-click to enforce path conversion.

**Comment by mintty** [comment] 2020-03-13 10:55
Also, you can already configure this function to be available for keys or in the context menu:
```
KeyFunctions=AS+Insert:paste-path;AS+KP_Insert:paste-path
```
```
CtxMenuFunctions=Paste path:paste-path
MenuMouse=bu
```

**Comment by mintty** [comment] 2020-09-11 18:32
Added example above to the manual page.

**Closed** 2020-09-11 18:34 UTC
Labels: question

**Comment by mintty** [comment] 2020-09-20 02:58
Released 3.4.0.
