### ISSUE TITLE
Lingering "Ctrl" input present after switching back to a fullscreen Mintty window

### ISSUE THREAD

**Issue by tejasvi** [mintty/mintty#1067] opened 2020-12-05 08:01 UTC
Steps to reproduce:
* Open Mintty window in fullscreen.
* Switch to some other window (by <kbd>Alt+Tab</kbd>).
* Switch back to the Mintty window.
* Press any key (e.g. <kbd>D</kbd>).
* The terminal will receive <kbd>Ctrl+D</kbd> instead of <kbd>D</kbd>.

**Comment by mintty** [comment] 2020-12-05 08:44
Cannot reproduce. Please try to narrow down side conditions under which this happens.

**Comment by csdvrx** [comment] 2020-12-05 16:24
Are you using AutoHotKey or similar to remap Caps? I have similar issues with persistent Ctrl,  but only in mintty so I suppose my AHK script is fine.

**Comment by mintty** [comment] 2020-12-05 17:54
Please provide a minimal AHK script and describe how it would persist Ctrl.

**Comment by mintty** [comment] 2020-12-08 07:49
I'll mark this invalid (and eventually close it) as there is no reproducible test case and no evidence of a bug.

**Comment by mintty** [comment] 2020-12-12 19:19
In the past, mintty has already provided a number of workarounds for weird behaviour of various key injection software, but without a reproducible test setup I can't do anything.

**Closed by mintty** 2020-12-12 19:19 UTC
Labels: invalid

**Comment by tejasvi** [comment] 2020-12-15 13:13
I am using [WinCompose](https://github.com/samhocevar/wincompose), [SharpKeys](https://github.com/randyrants/sharpkeys), [TouchCursor](https://github.com/martin-stone/touchcursor), and an AutoHotkey script (`^SPACE:: Winset, AlwaysOnTop, , A`) simultaneously, which made it harder to track down. I found WinCompose responsible, but it is not consistently reproducible. I can work without it running in the background for now.

**Comment by mintty** [comment] 2020-12-15 16:18
Cannot reproduce even with WinCompose. Which Compose key did you configure in WinCompose? Is Compose also enabled in mintty and for which key? Is it reproducible without the other tools running?
