### ISSUE TITLE
workaround ConPTY-spoiled auto-wrap

### ISSUE THREAD

**Issue by rovf** [mintty/mintty#971] opened 2020-02-28 16:11 UTC
My issue sounds absolutely unlikely, but it is reproducible: I am running JRuby, which is a jar-Library, implementing the Ruby language. I am using  the Windows implementation of Java, Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode).

Now the funny thing is that, whenever I run JRuby inside a mintty, and the output (stdout or stderr from either my program or from the JRuby compiler) is wider than the mintty Windows, an I copy this line to the clipboard, there is a \n inserted where the physical line of the Window would end.

OTOH, if I use any Cygwin tool to output a line longer than the Window size, it is shown wrapped too, but when I copy it to the clipboard, no \n is inserted inside the line, as it should be.

This behaviour occured after my most recent update of mintty; before that, it did not matter where the output came from, I always could copy long lines easily. The behavioru is realls strange, because stdout is stdout and mintty can not know, whether it comes from the Java side or from a cygwin program. Still, this is the behaviour I can see reproducibly.

I have mintty 3.1.0 (x86_64-pc-cygwin) on Windows 10

**Comment by mintty** [comment] 2020-02-28 16:24
> This behaviour occured after my most recent update of mintty

Did you happen to update cygwin at the same time? I.e. did you perhaps have cygwin 3.0.7 before this occurred? Can you downgrade either (mintty *or* cygwin) for a test case please?
Either way, if you literally get a backslash and an n, this is certainly not a mintty issue.

**Comment by rovf** [comment] 2020-02-28 16:42
I get a linebreak (0x0a). 

I made for sure the update of cygwin and mintty together, because I always do the update of all packages together. How can I downgrade? Nearly most Cygwin repositories offer only the most recent version of the packages.

**Comment by mintty** [comment] 2020-02-28 21:21
In cygwin setup, in the Category View (top left button, switch Pending to Category), open All - Base, on the cygwin package, from the popup under Keep, select 3.0.7-1.

**Comment by mintty** [comment] 2020-02-29 20:10
Can you try to create a reproducible test case, please, by capturing the output as a mintty log file.
If you can `cat` the file and reproduce your issue, I can analyse what happens.

**Comment by rovf** [comment] 2020-03-02 07:25
On Fri, Feb 28, 2020, at 22:21, mintty wrote:
> In cygwin setup, in the Category View (top left button, switch Pending 
> to Category), open All - Base, on the cygwin package, from the popup 
> under Keep, select 3.0.7-1.

Honestly, I would prefer not downgrading cygwin, but just downgrading mintty, and not the cygwin package itself, if this makes sense to research the issue, because I don't know to what extent the cygwin downgrade would affect my other packages which I have installed.

I went to setup, following your advice, and searched therefore for "mintty". I see that I have installed 3.1.0-1, that there is already a new one available (3.1.4-1), and that I have the choice to downgrade to either 3.0.6-1 or 2.9.6-0. Which one would be best for the test? 

BTW, I also searched for the cygwin base package. "base-cygwin" in category "Base" says that I am currently on 3.8-1, and the only older one available would be 3.6-1.

Neither of these packages matches the 3.0.7-1 you are proposing.

Ronald

**Comment by k-takata** [comment] 2020-03-02 07:36
> BTW, I also searched for the cygwin base package. "base-cygwin" in category "Base" says that I am currently on 3.8-1, and the only older one available would be 3.6-1.

Not the "base-cygwin" package, "cygwin" package in category "Base".
I suspect that this is caused by the ConPTY support which was added at cygwin 3.1.0. So, I think that downgrading cygwin would be the best for the first step.

**Comment by BrianInglis** [comment] 2020-03-02 07:40
The Base category cygwin package is cygwin, versions: 3.1.4-1, 3.1.2-1, 3.1.1-1, 3.0.7-1. 
Other packages with the same versions to keep in sync iif installed are: 
cygwin-{debuginfo,devel,doc} in categories Debug, Devel, Doc respectively.

**Comment by rovf** [comment] 2020-03-02 07:53
On Sat, Feb 29, 2020, at 21:10, mintty wrote:
> Can you try to create a reproducible test case, please, by capturing 
> the output as a mintty log file.
>  If you can `cat` the file and reproduce your issue, I can analyse what 
> happens.

What exactly is meant by "capturing the output as log file"? I guess you don't mean just redirecting the output of the program to stdout, because then we of course don't see any line endings. It happens only if the output goes directly to the tty.

However, here are the steps you can do to reproduce the case:

1. Make sure Java is installed. I have

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

but I don't think it really depends on the actual version.

2. To reproduce exactly my case, you would have to install JRuby as a socalled "complete"-jar, from https://www.jruby.org/download (where the link says JRuby .... complete.jar). I am using for my test the version 9.0.5.0, but here too, I think you can take any newer one.

3. Verify that your installation works, by doing a, say, 

    java -cp jruby-complete-9.0.5.0.jar org.jruby.Main --version

which should output the installed JRuby version.

4. Create a mintty window, at most 100 characters wide.

5. Run the command

    java -cp jruby-complete-9.0.5.0.jar org.jruby.Main -e 'p [999]*22'|tee abc.txt

which should output just a list of "999, 999, ...", slightly longer than the width of the window.

Now, if you look at the file abc.txt with, say, xxd, you can see there is only one 0d0a line ending at the end of the file, but if you copy the line which has been output from the mintty window and paste it somewhere, you see that there is an additional line break inside the string.

In case it matters: My mintty settings are "Copy on select", "Trim space from selection", and I paste it using the right mouse button.

Ronald

**Comment by rovf** [comment] 2020-03-02 08:08
I found out what's going on! Actually, it is much easier to reproduce! The culprit is the CR in the Windows line ending which is produced by console programs intended for Windows. For example, you can see the same effect by doing just a 

    cmd /c echo now type a line which is wider than your terminal ....

Here too, copying the line to the clipboard causes an additional line break in the middle, while a

    echo now type a line which is wider than your terminal ....

behaves correctly. Could it be that older mintty versions filtered out this CR?

Ronald

**Comment by mintty** [comment] 2020-03-02 11:34
Thanks for the simplified test case.
Confirmed it's working as expected in cygwin 3.0.7, no need to downgrade anything on your side.

It's apparently related to the approach of the ConPTY adaptation to interpret and replay the whole screen contents. I'm not sure whether that can be avoided as it works around some subtle issues. Maybe the line wrapping case can be handled specifically, assuming proper auto-wrap mode on the terminal side. Maybe it should be reported on the cygwin mailing list.

**Comment by rovf** [comment] 2020-03-02 12:01
On Mon, Mar 2, 2020, at 12:34, mintty wrote:

> It's apparently related to the approach of the ConPTY adaptation to 
> interpret and replay the whole screen contents. I'm not sure whether 
> that can be avoided as it works around some subtle issues. Maybe the 
> line wrapping case can be handled specifically, assuming proper 
> auto-wrap mode on the terminal side. Maybe it should be reported on the 
> cygwin mailing list.

Great to hear this! Would you create a report for the mailing list, since you have more insight in the details of the issue than I do?

Ronald

**Comment by mintty** [comment] 2020-03-05 16:53
Response: https://cygwin.com/ml/cygwin/2020-03/msg00088.html
So I guess we're stuck in this case.

**Comment by rovf** [comment] 2020-03-05 17:55
On Thu, Mar 5, 2020, at 17:53, mintty wrote:
> Response: https://cygwin.com/ml/cygwin/2020-03/msg00088.html
>  So I guess we're stuck in this case.

How about: Whenever mintty is doing a copy of the buffer, remove "offending line endings" from the text. An offending line ending would be one, which occurs after exactly the screen width of characters.

Since this is a heuristic rule, and we can imagine cases that this is not the desired behaviour, this hack could be controlled by a mintty option.

Ronald

**Comment by mintty** [comment] 2020-03-06 12:23
Well, if you're writing exactly 80 (or whatever) columns, then a newline, it should be included in the paste buffer.
I'm afraid these cases are indistinguishable.

**Comment by rovf** [comment] 2020-03-06 14:26
I was aware of this ambiguity. That's why I proposed to make in an option.

Since, given a windows width of 80 characters, this occurs statistically in just a bit over 1% of all copy operations, and quite some users might be willing to take the effort and enter the new-line manually in this case, I think it would worth providing this feature. I could understand to have this option initially turned off (for reasons of orthogonality), although it would be funny having it turned on by default and see, whether someone ever notices the missing newline at the end and sends you a bug report.

**Comment by ElvenSpellmaker** [comment] 2020-04-01 09:34
I'm also getting bitten by this a lot, and it's any Windows application that runs under Cygwin since their introduction of the Windows <--> Cygwin support.

**Comment by rovf** [comment] 2020-04-01 09:37
> I'm also getting bitten by this a lot.

Maybe if enough users vote for it, the mintty maintainer could be persuaded to implement my proposal on this issue....

**Comment by mintty** [comment] 2020-04-01 11:53
Well, maybe, although I don't really like that approach and it will certainly not be a default.
Unfortunately there is no systematic way to recognize the case, I've tried even detection by timing.
One more to nag me?

**Comment by rovf** [comment] 2020-04-01 12:16
I also think that there is no real way to do it **always** **correctly**, and that why I propsed to make this hack an _option_. My guess is that most users who do understand the problem, will prefer a solution which happens to do the right thing most of the time, even though it does the wrong thing sometimes; in particular, since the cases where the hack would do the wrong thing are easy to recognize and to handle. IMHO we should  see it from the practical viewpoint, i.e. usability.

**Comment by mintty** [comment] 2020-04-01 12:35
Maybe you could submit a change request to the Windows ConPTY to make this case distinguishable?
For example, an auto-wrap line-end could get an additional redundant CR: "\r\r\n".

**Comment by rovf** [comment] 2020-04-01 12:55
[Feature request on ConPTY](https://github.com/rprichard/winpty/issues/177) opened! Please have a look for the safe side whether the description is technically correct.

**Comment by mintty** [comment] 2020-04-01 13:01
Wrong project. It's about the Microsoft Console pty support, now part of the MS terminal project.
https://github.com/microsoft/terminal/issues/

**Comment by rovf** [comment] 2020-04-01 13:07
> 
> 
> Wrong project. It's about the Microsoft Console pty support, now part of the MS terminal project.
> https://github.com/microsoft/terminal/issues/

Interesting. Created there https://github.com/microsoft/terminal/issues/5202

**Comment by mintty** [comment] 2020-04-01 13:43
Thanks.
Apparently they have a fix in their queue already. So no need to fiddle up a workaround for mintty.

**Comment by ElvenSpellmaker** [comment] 2020-04-24 10:24
It seems they released a fix, I don't know what's needed to now get this into Cygwin

**Comment by mintty** [comment] 2020-04-24 13:14
Integration with cygwin is implicit via the Windows environment. Wait for Windows update.

**Comment by ElvenSpellmaker** [comment] 2020-04-24 13:16
Oh OK, thanks!

**Comment by mkq** [comment] 2020-06-15 16:54
In the meantime, a workaround is to set environment variable `CYGWIN=disable_pcon` (or append ` disable_pcon` if already set). This is from [this answer](https://sourceware.org/legacy-ml/cygwin/2020-03/msg00094.html) to [the cygwin mailing list post](https://cygwin.com/ml/cygwin/2020-03/msg00088.html) mentioned above. 
However, it does not work on a command-by-command basis, e.g. with `env`. I had to set it globally in the Windows environment (control panel).

**Comment by ElvenSpellmaker** [comment] 2020-06-15 17:28
Unfortunately this disables the pseudo tty functionality which means Windows apps go back to being 'broken' under Cygwin.

**Comment by Farmbuyer** [comment] 2020-06-16 19:11
Setting `disable_pcon` fixes all the weird and broken linewrapping issues I've been having in cygwin/mintty lately, all at once:

- Lines output from a running program's console logger were getting wrapped a dozen characters early.  Yes, `COLUMNS` was the correct value and was exported.  Other programs could draw all the way to the right edge.  But ongoing logger output with long lines simply got wrapped 12 columns early.  Disabling ConPTY restores long lines being wrapped at the end of the line.

- Pressing Enter while a program is running, in order to create visual space, works once again.  (Obviously when the program exits and the shell wakes back up, there are an equal number of "blank commands" and empty prompts printed, but that's normal and expected and fine.)  With ConPTY, all the Enter keypresses were being sunk and ignored; disabling ConPTY restores Enter making a blank line.

This is great to know about, thank you!

**Comment by avih** [comment] 2020-06-16 19:49
> Setting `disable_pcon` fixes all the weird and broken linewrapping issues I've been having in cygwin/mintty lately, all at once:

Unrelated to mintty or this issue, but FWIW, disabling this pcon thing also fixes the following for me:

- When tmux is running in st terminal and the terminal is closed - the tmux session mostly gets (incorrectly) killed as well. With this pcon disabled this no longer happens. I could not reproduce the issue in mintty or xterm.
- More of an annoyance than issue, with pcon disabled I no longer get at least two additional console-related processes for each cygwin shell (PTY). This is mostly noticeable with tmux which has quite a few shells (PTYs) opened.

I think this native console wrapper got enabled by default prematirely in cygwin. Personally I have no use for it, and there's also always [winpty](https://github.com/rprichard/winpty). I'm keeping it disabled for now.

**Comment by ElvenSpellmaker** [comment] 2020-06-25 20:49
I do think there's some very weird behaviours with `pcon` enabled, Ruby 2.7.0 breaks `irb` because `reline` expects the terminal to be a pipe, but it's a `console` in mintty with pcon enabled.
Any app that has made any previous assumptions based on the `GetFileType` call will be a bit shocked: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype

@mintty If you're interested: https://github.com/ruby/reline/issues/140

I'm not sure how much of it is a mintty problem, but the file type _changes_ in mintty with pcon on, but it _doesn't_ change in cmd (it's always 2 in cmd)

In mintty however it's `3` with `disable_pcon` and `2` with it on.

In this specific case `reline` just need to update code to do better Cygwin detection imho, but you may be interested in this background anyway because I think a load of current issues surrounding Cygwin is this transition to using the pseudo terminal which seems to (wrongly imho) extend well beyond _just_ running Windows apps.

**Comment by mintty** [comment] 2020-06-25 21:17
This issue is not a mintty problem. You can observe the same symptoms in any pty-based terminal.

**Comment by ElvenSpellmaker** [comment] 2020-06-25 21:19
I thought as much, just wanted to check.

I wonder what the overall solution to all this stuff is, it seems the terminal identifying as a console is causing all sorts of havoc, but I've not tested why other programmes have issues so it could just be `reline`.

**Comment by mintty** [comment] 2020-06-26 03:41
The terminal is not identifying as a console. This is done by cygwin via ConPTY support and only towards non-cygwin programs, i.e. those that actually need this mode to work properly.

**Comment by ElvenSpellmaker** [comment] 2020-06-26 03:43
Thanks for the explanation.
I think it's a Cygwin problem then as it's exposing itself as a console to a Cygwin programme (in this case Ruby compiled under Cygwin).

**Comment by mintty** [comment] 2020-06-26 04:35
> exposing itself as a console to a Cygwin programme

Not really, as the program calls GetFileType which is a Windows function, not a POSIX function. So it's a mixed mode program.
Cygwin programs should only use Windows functions if they know what they're doing...

**Comment by rovf** [comment] 2020-06-26 10:37
> 
> 
> Thanks for the explanation.
> I think it's a Cygwin problem then as it's exposing itself as a console to a Cygwin programme (in this case Ruby compiled under Cygwin).

I don't see how this is related to (compiled, i.e. MRI-)Ruby. Actually, when running the Cygwin Ruby, everthing works perfectly fine. This was never a problem.

**Comment by ElvenSpellmaker** [comment] 2020-06-26 10:38
Yeah Cygwin Ruby isn't Ruby 2.7, as soon as Ruby 2.7 lands in Cygwin it'll break because they switch to `reline` for their Readline capabilities.

**Comment by mintty** [comment] 2020-10-23 11:26
Issues still seems to be open in Windows Terminal but being worked on: microsoft/terminal#6901.

**Comment by mintty** [comment] 2021-03-29 17:44
Cygwin 3.2.0 has been released, so at least for cygwin apps this issue should be resolved. Can we close it?

**Comment by ElvenSpellmaker** [comment] 2021-03-29 18:26
I only see 3.1.7

**Comment by mintty** [comment] 2021-07-23 21:29
Closing under the assumption this issue vanished with cygwin 3.2.

**Closed by mintty** 2021-07-23 21:29 UTC
Labels: invalid

**Comment by ElvenSpellmaker** [comment] 2021-07-24 03:06
> Closing under the assumption this issue vanished with cygwin 3.2.

Nope the hard like breaks are still a thing...

**Comment by mintty** [comment] 2021-07-24 05:02
> hard like breaks are still a thing...

When running Windows programs or also cygwin programs?
In either case, it's not a terminal thing, so I think I'll leave it closed...

**Comment by GeekDuanLian** [comment] 2023-10-30 14:32
I used the latest mintty version 3.6.5 (from msys2) and the latest official version python 3.11.6 (from https://www.python.org/ftp/python/3.11.6/python-3.11.6-embed-amd64.zip ), deleted `.minttyrc` and `.bashrc`, and I can still reproduce the problem.
Is it because of msys2 build problem? Or is my Windows version too old? My Windows version is 10.0.19044.2006.

**Comment by mintty** [comment] 2023-10-30 17:02
The test case `cmd /C long line ...` works for me, in cygwin. Maybe python output is different?

**Comment by ElvenSpellmaker** [comment] 2023-10-30 17:07
FWIW, I tried asking when and how here https://github.com/microsoft/terminal/issues/6901#issuecomment-1736253699 and so far no response.

**Comment by GeekDuanLian** [comment] 2023-10-31 02:27
> The test case `cmd /C long line ...` works for me, in cygwin. Maybe python output is different?

Reduce the terminal size to e.g. 30x15.
`/c/Windows/System32/cmd.exe /C echo ====================================================================================`
Select All -> Copy
![image](https://github.com/mintty/mintty/assets/6257434/4e8444b2-4d93-4019-999c-e45905864b3c)

I can't reproduce your situation?

**Comment by GeekDuanLian** [comment] 2023-10-31 02:51
> I've been still getting the hard linebreaks due to ConPTY daily and it's highly annoying.
> 
> I noticed MS recently merged some ConPTY changes into their Terminal repo, but there's zero transparency about when it goes into a new OS version (and which KBs it'd be in) or if Windows 10 will even get the update at all...

I also used their Terminal, which worked perfectly fine for this line wrapping problem, or I used it in cmd or in the VSCode built-in terminal, and they both worked fine.
It's just that the function of `sshpass` is invalid, which may be a problem with the terminal type. Not relevant to this question.

**Comment by GeekDuanLian** [comment] 2023-10-31 02:54
I have a temporary workaround, `stty cols 1000`, which can trick the terminal into saying my width is long, but I don't know if it has any other effects.

**Comment by mintty** [comment] 2023-10-31 09:06
> Reduce the terminal size to e.g. 30x15.
/c/Windows/System32/cmd.exe /C echo ====================================================================================

The visual result is correct, right?

**Comment by GeekDuanLian** [comment] 2023-10-31 09:16
Yes, it only affects the pasted results, and what is more important to me, long url line Ctrl+click to open will open the truncated results.

**Comment by GeekDuanLian** [comment] 2023-11-10 16:53
I directly renamed `OpenConsole.exe` in `Windows Terminal` to `conhost.exe` and replaced it in `C:\Windows\System32`. The problem was solved, despite the possibility raised in https://github.com/microsoft/terminal/issues/1817 There are potential problems, but at least I haven't encountered them yet. Let's try it first.

**Comment by mintty** [comment] 2023-11-10 20:57
Where did you find this OpenConsole?

**Comment by Biswa96** [comment] 2023-11-11 04:05
Windows Terminal provides its own console program, OpenConsole. So, it does not relies on system conhost.exe. cygwin may copy OpenConsole.exe for ConPTY. Compiling it without Visual Studio would be a nightmare.

**Comment by BrianInglis** [comment] 2023-11-11 08:53
If it can not be built under Cygwin, then Cygwin users may do so, but Cygwin project members may not.

**Comment by mintty** [comment] 2023-11-11 17:23
> Cygwin users may do so

Or just copy it as suggested by @GeekDuanLian, if only they knew where to find it. That's why I asked, so I can add a howto to the project homepage.

**Comment by BrianInglis** [comment] 2023-11-11 20:15
This project homepage and/or wiki?

**Comment by mintty** [comment] 2023-11-11 21:53
I'll think about that as soon as I can check whether that's feasible at all. Right now, I have Windows Terminal installed but don't find any OpenConsole.

**Comment by GeekDuanLian** [comment] 2023-11-12 15:51
@mintty 
Sorry for being late, download the zip archive file matching the architecture at https://github.com/microsoft/terminal/releases . OpenConsole.exe will be inside after decompression. It has been digitally signed by Microsoft, so you can be sure it is from an official Microsoft source.

**Comment by mintty** [comment] 2024-06-20 12:10
I've added the workaround to the wiki Tips page:
https://github.com/mintty/mintty/wiki/Tips#text-attribute-handling-from-wsl-and-other-windows-programs
