### ISSUE TITLE
Disabling 'Bold as font' still renders bold

### ISSUE THREAD

**Issue by silverwind** [mintty/mintty#468] opened 2015-08-11 07:23 UTC
Seems like this option is no longer working, fonts are always shown bold regardless if 'bold as font' is enabled or not. I downgraded to 2.1.3 to confirm this is an issue with the new version.

**Comment by mintty** [comment] 2015-08-12 17:25
There has been no change about bold attributes between 2.1.3 and 2.1.4.
Bold cannot be disabled altogether since 2.0.1 (this used to be possible for a while before).
Please describe the issue more clearly. What do you mean by "fonts are shown bold"? What settings are active, what do you output?

**Comment by silverwind** [comment] 2015-08-12 17:50
I'm talking about the 1px "shadow" rendered around text using theANSI bold code. You can see this with

```console
echo -e "\033[1mbold\033[0m text"
````

![bold](https://cloud.githubusercontent.com/assets/115237/9231892/eac8c2d2-412a-11e5-80f6-05542a35b516.png)

The option 'Show bold as font' should remove this shadow, but it has no effect and text is still rendered bold even if it's disabled. Also sorry, I've meant 1.1.3 as the last known working version.

**Comment by mintty** [comment] 2015-08-13 09:44
Changed previous issue title "Unable to disable 'Bold as font' in 2.1.4".
The option "Show bold as font" select a **corresponding** bold font for bold display, if one exists. That is not the case for Monaco which comes in only one style. In that case "bold as font" is not applied. That was like this in 1.1.3 already. The only change since then is that previously the fall-back behaviour was to not display bold at all while now mintty makes sure that one kind of bold display is applied in any case, the fall-back being the overstriking boldened display.
This works as designed; intending to close the issue.

**Comment by silverwind** [comment] 2015-08-13 15:16
Ah. It's the fallback behavious which I'd like to disable. Could you maybe provide an option in `.minttyrc` to disable the fallback? I find it visually unpleasing as it kind of disturbs the ClearType rendering.

**Comment by aethelberht** [comment] 2015-08-13 20:01
> The option "Show bold as font" select a corresponding bold font for bold display, if one exists.

I'm confused: how is that relevant to the fact that fallback modifications are still being done when the "Show bold as font" option is off?

**Comment by mintty** [comment] 2015-08-13 23:51
I'm not convinced that the bold character attribute, which is being used on purpose by applications, should be suppressed by configuration.
As I had explained on the cygwin mailing list already (https://cygwin.com/ml/cygwin/2015-08/msg00122.html): "I don't see why "bold as non-bold" should be an option." (This had been the case for a few mintty versions only until 1.1.3/1.2 but not for earlier versions either.)
If you don't like the fallback, it's a good idea to choose a font that has a bold style. Monaco, as nice as it looks, isn't a good choice anyway as unfortunately, it has a very limited character repertoire, not even supporting the € sign.

**Comment by silverwind** [comment] 2015-08-14 02:37
Well, as I see it, these options restrict which ansi styles get displayed or supressed. I use the same option set in iTerm too, as I don't really care about the information conveyed by the application. I don't want to see any bold text in a terminal, and I think mintty should honor that.

By the way, iTerm on OSX is able to bold Monaco, while still looking fine, but that's probably OSX's font rendering at work:

![screen shot 2015-08-14 at 4 35 50 am](https://cloud.githubusercontent.com/assets/115237/9266211/24e53f04-423e-11e5-8a0a-972612f9a9a6.png)

![screen shot 2015-08-14 at 4 29 27 am](https://cloud.githubusercontent.com/assets/115237/9266128/26903f8a-423d-11e5-9f93-15f1da07643c.png)

**Comment by mintty** [comment] 2015-08-14 09:16
I checked bold font creation in detail and in contrast to my previous comment, Windows does render Monaco in a bold version (Windows-generated), so for me actually the overstriking generated bold mode is not applied. Also it looks good here, I think. So why is there a difference? Two options:
* You don't like the auto-boldening applied by Windows (not mintty).
* You have a different Monaco font installed for which Windows boldening does not work (thus falling back to mintty boldening).
Can you provide a screenshots that exhibits the effect?

About your previous comment, suppressing character attributes is not a traditional feature of terminals, and it's not a feature of xterm which is the mintty model for terminal functionality.

**Comment by stania** [comment] 2015-09-01 09:07
Any fix for this? I agree with silverwind and my previously favorite terminal emulators such as PuTTY and GnomeTerminal supports rendering bold text with non-bold font face and brighter color. I use bold font face default (ex. I'm using "Monaco bold 9px" in font-selection dialog) so that bolder text is ugly for me..

**Comment by mintty** [comment] 2015-09-01 11:43
Unless I misunderstood, your request is different from the previous one.
"Show bold as colour" is an option but is effective only for the "ANSI colours" (not for the 256 colour mode or true colour attributes). This has not changed since earlier mintty versions.

According to the mintty manual, this option could apply also to the default attribute. This did not work, though, in earlier versions. That's why I apply boldening now to enforce one kind of bold display. If you request to fix that to apply "bright" as a better solution, the request is accepted, provided a consistent way to apply brightening to any colour can be identified.

**Comment by mintty** [comment] 2015-09-02 16:23
Actually, the mechanism to brighten plain (non-ANSI-coloured) text was already there. Just the function to compute the bright value (brighten) failed (so mintty detected the colour had not changed and applied the fall-back then).
Tweaked the function so "BoldAsBright" (i.e. BoldAsColour with automatically derived colour) should work now, in general. There may still be interference with background colour.
Please test.

**Comment by stania** [comment] 2015-09-03 09:40
I've tested master HEAD. But this version still renders bold face with auto-boldened text.

![image](https://cloud.githubusercontent.com/assets/903320/9655307/32911b36-526b-11e5-8233-c53c7275abfc.png)

Tested text is
```
echo -e "\033[38;5;226;1mbold\033[0m text"
```

If my settings are wrong, please let me know.
(And I confirmed that there's no problem with ansi-colors)

**Comment by stania** [comment] 2015-09-03 10:56
And I found that something went wrong. Look the screenshot below.

(Left: master HEAD, Right: 2.1.5)
![image](https://cloud.githubusercontent.com/assets/903320/9656745/cb4c76e0-5275-11e5-9f3d-4c37b1a26141.png)

**Comment by mintty** [comment] 2015-09-03 11:14
1. I extended BoldAsColour to plain text (not having a colour attribute), not to text having a 256-colour or true-colour attribute, and I don't think that can reasonably be done - which means the fallback is applied.

2. The "bold" in the left screenshot looks slightly darker than "text" which is a result of the "brighten" algorithm. If the colour to be brightened is already so bright that a significant difference would not be achieved (arguably not the case in your screenshot), it is made darker instead (again arguably with not enough delta in your case). That's also how predefined colour settings of other terminals are crafted (e.g. bright white is usually grey and then also used for bold white). These two are intrinsic problems of any automatic brightening approach and you are welcome to suggest better algorithms.

**Comment by stania** [comment] 2015-09-03 11:33
I'm reading code and finally have understand your opinion and current implementation. I'll try to find better algorithms and make some patch for this problem.

**Comment by silverwind** [comment] 2015-09-03 11:53
On topic of my original request: I still feel that the overstrike bolding should at least have an config file option to disable it. If I don't want to distinguish bold and non-bold, mintty should honor that choice.

**Comment by stania** [comment] 2015-09-03 11:59
I've checked behavior of PuTTY and Gnome Terminal on non-ANSI-colours.
They just discard bold attribute and doesn't change color at all. Gnome Terminal has the option with name just "Allow bold font".

I'm agree with silverwind's last comment. How about make a new config option which is distinguished one from 'disable bold as corresponding font'?

**Comment by mintty** [comment] 2015-09-03 14:46
I have implemented xterm's OSC sequence ^[]5;0;rgb^G (with e.g. rgb=200,200,200) to define a colour value for the bold attribute. Maybe we can also talk about something like xterm's config option colorBDmode to use a fixed color to indicate the bold attribute.
Please check (both of you) whether that serves your purpose.

Whenever the derived colour turns out to be the same as the foreground colour, the overstrike fallback is applied, though. I still see no use case for the idea to disable that altogether. If you don't want bold, don't use the bold attribute. (I know it's not you but your application... but simply ignoring the attribute isn't a good thing to do, and not a traditional feature.)

Looking forward to your input about improving the brightening approach.

**Comment by mintty** [comment] 2015-09-03 15:56
Please also check the uploaded improved brightening algorithm, without using the new sequence.

**Comment by alexeiz** [comment] 2015-09-11 14:51
There is code in wintext.c that deletes the bold font if its metrics don't match the normal font:

    if (bold_mode == BOLD_FONT && fontsize[FONT_BOLD] != fontsize[FONT_NORMAL]) {
      bold_mode = BOLD_SHADOW;
      DeleteObject(fonts[FONT_BOLD]);
      fonts[FONT_BOLD] = 0;
    }

This can silently prevent the bold font from being used despite the option bold_as_font.

**Comment by mintty** [comment] 2015-09-11 15:29
... in which case the overstrike fall-back would be applied.
Did you mean to indicate anything specific with this observation?

**Comment by alexeiz** [comment] 2015-09-11 15:39
It would appear as if 'bold as font' option doesn't do anything.  The font size check fails for many monospace fonts which makes 'bold as font' option pretty much useless.

**Comment by mintty** [comment] 2015-09-11 16:14
Certainly not. Some fonts come as a single style, in which case the option may have no effect. Many fonts, however, including monospace fonts, come in families, with a matching bold style. That's what the option aims at.

**Comment by alexeiz** [comment] 2015-09-11 16:35
Can you check this font? https://github.com/be5invis/Iosevka
It has the bold style, but the bold as font option doesn't work on it.

**Comment by mintty** [comment] 2015-09-11 17:38
I would like to check it but there is no font on that page, just a big package that does not build on my system. This is not a way to distribute fonts.

**Comment by alexeiz** [comment] 2015-09-11 19:07
The release zip file contains all fonts: https://github.com/be5invis/Iosevka/archive/v0.1.11.zip

**Comment by mintty** [comment] 2015-09-11 19:13
OK, I didn't check that download archive because it's misleadingly called "Source code".

**Comment by mintty** [comment] 2015-09-11 19:34
For me, the bold as font option does work nicely, and italic looks nice, too.
![iosevka](https://cloud.githubusercontent.com/assets/12740416/9824393/c9d3612c-58cc-11e5-8ddb-f21cd521b8a4.png)

**Comment by alexeiz** [comment] 2015-09-11 19:47
This is 12 points?  Looks like the bug happens only on 11 points and below.

**Comment by mintty** [comment] 2015-09-11 20:12
I tried various sizes, including 11pt and smaller, and changing other options. It always looks fine here.

**Comment by mintty** [comment] 2015-09-25 16:05
Changing policy; with the latest change, overstriked bold display is not enforced anymore if the colour that the bold attribute gets mapped to is explicitly redefined (and happens to be the same as the non-bold colour).
This applies to the default foreground colour (mapped to the new bold colour which is configurable with option BoldColour or with the corresponding xterm control sequences), and the ANSI colours 0 to 7 (which are mapped to ANSI colours 8 to 15).

Default behaviour (i.e. without colour redefinitions) is still (and will remain to be) overstriking bold mode (if BoldAsFont=false).

**Closed by mintty** 2015-09-25 16:05 UTC

**Comment by mintty** [comment] 2015-11-03 17:19
Revised in 2.2.1.

**Comment by Swoorup** [comment] 2016-05-30 13:56
I have getting this weird issue again in 2.3.7
![image](https://cloud.githubusercontent.com/assets/3408009/15651314/53d266d6-26b1-11e6-8c98-e9966392fba4.png)

**Comment by mintty** [comment] 2016-05-31 08:36
I see no difference between 2.3.6 and 2.3.7. What are your settings?

**Comment by Swoorup** [comment] 2016-05-31 12:52
```
Font=Sauce Code Powerline
ForegroundColour=131,148,150
BackgroundColour=0,11,17
CursorColour=220,50,47
Black=7,54,66
BoldBlack=0,43,54
Red=220,50,47
BoldRed=203,75,22
Green=133,153,0
BoldGreen=88,110,117
Yellow=181,137,0
BoldYellow=101,123,131
Blue=38,139,210
BoldBlue=131,148,150
Magenta=211,54,130
BoldMagenta=108,113,196
Cyan=42,161,152
BoldCyan=147,161,161
White=238,232,213
BoldWhite=253,246,227
Transparency=off
FontHeight=8
Scrollbar=none
BoldAsColour=no
CursorType=block
AllowBlinking=yes
AltFnShortcuts=no
CtrlShiftShortcuts=yes
FontSmoothing=default
Columns=274
Rows=73
BoldAsFont=no
Term=xterm-256color
```

![image](https://cloud.githubusercontent.com/assets/3408009/15674835/8e113604-2771-11e6-9d6f-27b114f43618.png)

**Comment by mintty** [comment] 2016-05-31 14:30
I guess what you want is actually option `BoldAsColour=yes`, please try that.
If that's not it, please describe which version exposed a different display for you (maybe with screenshot), what exactly you would expect to see, and why you would prefer "bold as non-bold".

**Comment by mintty** [comment] 2018-09-20 11:51
Released 2.9.1.

**Comment by mintty** [comment] 2019-11-23 18:58
Released 3.1.0.

**Comment by oshverdas** [comment] 2020-05-12 04:52
Hi! I'm running mintty 3.1.4 and faced the same problem with bold font. I'm using mintty to work in a virtual machine via ssh, and despite my settings aimed to never see bold as font, some apps, like htop are still able to render it. Kindly take a look at the screenshot.
![image](https://user-images.githubusercontent.com/6496483/81639473-5fe70100-945f-11ea-851a-bd705a7a3260.png)
This light gray bold font annoys me a lot. Is there an option (or a plan to add such option) like "Render in regular font style only"? I believe, it shouldn't be very hard.
Thank you.

**Comment by mintty** [comment] 2020-05-12 06:13
The "light gray" is caused by setting "bold as colour".
You can disable the bold character attribute by setting SuppressSGR=1 in the config file.

**Comment by oshverdas** [comment] 2020-05-12 06:45
It worked, thanks a lot!
The light grey color is likely a part of the UI, since it remained after SuppressSGR=1.
Moreover, "show bold" section now doesn't change anything:
![mintty-bold-variants](https://user-images.githubusercontent.com/6496483/81647220-fde2c780-946f-11ea-811f-14d2241aac98.png)

**Comment by mintty** [comment] 2020-05-12 14:34
> The "light gray" is caused by setting "bold as colour".

Try to disable that.

**Comment by oshverdas** [comment] 2020-05-13 11:17
> Try to disable that.

When I'm disabling the "as colour", the "xterm" checkbox gets automatically checked. "Show bold" section doesn't allow the state with all checkboxes unchecked. I've tried all possible combinations and stitched the results into one image in my previous reply.

**Comment by mintty** [comment] 2020-05-13 11:41
Yes but it should disable the light gray effect. Also even if "as bold" is checked it will remain disabled if overriden by `SuppressSGR=1`.
