### ISSUE TITLE
"Copy as HTML" rely on IME/codepage

### ISSUE THREAD

**Issue by xuefer** [mintty/mintty#838] opened 2018-12-19 14:06 UTC
IME set to microsoft pinyin. i can copy from 😀 https://emojipedia.org/grinning-face/ and paste it into mintty without problem, but when i copy it from mintty and paste it to anywhere (including mintty), two question mark is pasted (??)

terminal encoding is set to UTF-8
mintty version 2.9.4
Windows 10 Version 1809 Build 17763.194

possible same problem with copying Chinese characters: success only if IME is set to one of the Chinese IME (e.g. microsoft pinyin), garbage otherwise.

**Comment by mintty** [comment] 2018-12-19 14:14
Works fine for me.
Note that for emoji sequences, you'd need to make sure you select enough character cells on the terminal to catch all the components, or you'll copy only part of it.

**Comment by xuefer** [comment] 2018-12-19 14:18
actually you have to copy it twice to reproduce the problem
copy any text from notepad make it success to copy in mintty once, but latter copies from mintty fail

**Comment by mintty** [comment] 2018-12-19 14:25
Cannot reproduce; still works fine for me.

**Comment by xuefer** [comment] 2018-12-19 14:30
fixed in 2.9.5, i thought 2.9.4 was latest

**Comment by mintty** [comment] 2018-12-19 14:40
Oh, so I guess this is related to the "Copy as HTML" option which was the default in 2.9.4.

**Comment by xuefer** [comment] 2018-12-19 17:40
yes it is, enabling "copy as html" reproduce this issue in 2.9.5

**Comment by mintty** [comment] 2018-12-20 06:36
So the background is clear now, right? Why did you reopen the issue, what's the problem in 2.9.5?

**Comment by xuefer** [comment] 2018-12-20 06:38
it's clear, but "Copy as HTML" is buggy, should it be fixed?

**Comment by mintty** [comment] 2018-12-20 07:08
Works fine for me. I can "Copy as HTML" e.g. into a Thunderbird sending message window and it shows all emojis.

**Comment by mintty** [comment] 2018-12-20 09:55
Assuming "English IME" means default (not familiar with setting up IMEs), and furthermore, wondering how IME should have any impact on copying what is already on the screen;
your test case description is fuzzy (what should be done with the clipboard between the two copies?);
I still don't see any problems, other than notepad does not display emojis. Copying back into mintty works fine. Unless you provide a reproducible test case or at least a screen video as bug evidence, I intend to close the issue.

**Closed** 2018-12-29 00:33 UTC
