### ISSUE TITLE
In Cygwin please make control-C and control-V keys also do copy and paste ...

### ISSUE THREAD

**Issue by GuyLarri** [mintty/mintty#817] opened 2018-11-06 14:38 UTC
Under cygwin (in Windows 10 for example) currently Ctrl+Ins invokes 'copy' and Shift+Ins invokes 'paste'.

It would be very helpful for me if control-C also invoked copy and control-V invoked paste.
This is because (a) muscle memory of using control-C and control-V in Microsoft Office programs etc., and also (b) because many laptop keyboards and also Apple keyboards don't have an insert key. [Apple keyboard relevant when I run Windows under a VM].

If it is possible for an application to also capture Windows-key-V and Windows-key-C it would be create to map them as well, since that is what copy and paste are on a Mac (well it is the mac cmd 'flower' modifer key, which maps to the windows key), and people like me who move between Windows and Mac a lot would welcome that working too.

Yet I know I can edit the source code myself and recompile, but it would be nice to have it in upstream so I don't have to make the edit every version, and it is such a trivial change that someone who already knows the source code and the revision control system etc. etc. can probably do it very quickly.

**Comment by mintty** [comment] 2018-11-06 14:58
Note this is not only a trivial implementation issue but also a design issue as has been extensively discussed in other issues. Meanwhile it is already possible. Duplicate of #645, #602. Read the manual.

**Closed by mintty** 2018-11-06 14:58 UTC

**Comment by mintty** [comment] 2022-02-02 20:52
This is unacceptable discussion style. And it's not my opinion, it's the legacy of terminals. Mintty is a terminal. Many traditional users expect control characters to be what they are.

**Comment by CadetSparklez** [comment] 2022-02-08 23:18
cygwin is mostly used by windows uses to git clone and then make, this is 99% of what it is used for. in windows ctrl c and v are used. its inconsistant with platform. not mention many laptops or new keyboard form factors dont even have an insert key

**Comment by BrianInglis** [comment] 2022-02-09 00:40
*Git for Windows* does not provide `mintty` but runs *Msys2*/*Mingw64* ported native *Windows* `bash` and `git` under a `cmd` console host, and launches `git-gui` from that. 

Cygwin is also used by Unix developers who *MUST* use *Windows* as a desktop, those who *HAVE* to use apps requiring *Windows* , and as a POSIX environment hosting development tools for a variety of embedded systems and devices, some of which have been ported to *Cygwin*, some under native *Windows*.

**Comment by mintty** [comment] 2022-02-09 09:04
This is still a duplicate (see above, to find all the arguments). ^V might be dispensible but ^C as the default interruption function in command-line interaction is essential, 99% of bash users will expect and rely on it.
@BrianInglis, do you think mintty should allow plain control characters to be remapped (via KeyFunctions, without Exchange...) to user-defined functions?

**Comment by BrianInglis** [comment] 2022-02-09 09:53
I believe in letting people hang themselves and shoot themselves in the foot! 
But *nice* people don't let regular users easily disable themselves, as it can lead to more support requests. ;^> 
Couldn't they do that in readline (or using similar features in other shells), so that `mintty` doesn't have to change anything, just teach them the beautiful *GNU* command:
```
$ info readline command 'readline init file' 'readline init file syntax'
```
I've found ctrl-/shift-/arrow/delete/insert more consistent and useful across Unix since CDE Motif and Windows since 95, and those work as window operations, below the application operations level, so that you can clip and paste stuff unsupported by application operations, such as control labels and message content.

**Comment by mintty** [comment] 2022-02-21 09:39
Also note that `Copy` isn't actually needed in mintty at all, with default setting `CopyOnSelect=yes`.

**Comment by CadetSparklez** [comment] 2022-02-22 01:27
well yes paste is reallly all i need but everyone with a laptop or small form factor or mac keyboard with no insert key is having a great time out here

**Comment by CadetSparklez** [comment] 2022-02-22 01:28
just how hard is it to have an option in settings? i feel like it couldnve been done 15 times over in the time explaining why not to do it

**Comment by mintty** [comment] 2022-02-22 05:02
Add the following to your .bashrc file:
```
paste () {
  CLIP=$(cat /dev/clipboard)
  COUNT=$(echo -n "$CLIP" | wc -c)
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}${CLIP}${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$(($READLINE_POINT + $COUNT))
}
bind -x '"\C-v": paste'
```
and the following to your .inputrc file:
```
set bind-tty-special-chars off
```

**Comment by mintty** [comment] 2022-02-28 00:01
@BrianInglis, I plan to let modified character keys (e.g. letters) to catch with function and cursor keys to allow user-defined mappings with other modifiers than Shift+Ctrl. Thus Super and Hyper will be supported as well in the next version.
For consistence and completeness, I'd allow Control and Alt, too, safeguarded by a setting that needs to be added to enable people to shoot themselves in the foot as you say. Therefore the name of the option shall be `ShootFoot`.

**Comment by BrianInglis** [comment] 2022-02-28 00:20
The "proper" colloquial/vernacular/jargon term is [FootGun](https://www.urbandictionary.com/define.php?term=footgun)

**Comment by mintty** [comment] 2022-02-28 00:34
Thanks for the hint; I think I'll stay with ShootFoot because it rhymes so weirdly.

**Comment by mintty** [comment] 2022-03-25 18:23
Released 3.6.0.

**Comment by Xii-Nyth** [comment] 2022-04-19 21:08
> Add the following to your .bashrc file:
> 
> ```
> paste () {
>   CLIP=$(cat /dev/clipboard)
>   COUNT=$(echo -n "$CLIP" | wc -c)
>   READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}${CLIP}${READLINE_LINE:$READLINE_POINT}"
>   READLINE_POINT=$(($READLINE_POINT + $COUNT))
> }
> bind -x '"\C-v": paste'
> ```
> 
> and the following to your .inputrc file:
> 
> ```
> set bind-tty-special-chars off
> ```

Oh hey first thing I found online which actually worked in this version. Found something else before but nothing changed.
Didn't know which one of the 3/4 of each file it was so just added to all.
Also just noticed that its added in the new version, but hey I avoided the odd chance something broke when I updated by manually adding it in.

Thanks!

**Comment by manishie** [comment] 2022-10-05 18:05
> > Add the following to your .bashrc file:
> > ```
> > paste () {
> >   CLIP=$(cat /dev/clipboard)
> >   COUNT=$(echo -n "$CLIP" | wc -c)
> >   READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}${CLIP}${READLINE_LINE:$READLINE_POINT}"
> >   READLINE_POINT=$(($READLINE_POINT + $COUNT))
> > }
> > bind -x '"\C-v": paste'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the following to your .inputrc file:
> > ```
> > set bind-tty-special-chars off
> > ```
> 
> Oh hey first thing I found online which actually worked in this version. Found something else before but nothing changed. Didn't know which one of the 3/4 of each file it was so just added to all. Also just noticed that its added in the new version, but hey I avoided the odd chance something broke when I updated by manually adding it in.
> 
> Thanks!

wow, this is also the only solution that worked for me.  thanks!
