### ISSUE TITLE
Pressing Up while a program is running moves the cursor up

### ISSUE THREAD

**Issue by orgads** [mintty/mintty#630] opened 2017-02-13 12:30 UTC
Then the output of the running program overwrites previous lines.

On Linux bash, pressing Up writes `^[[A`, leaving the cursor on the same line.

**Comment by mintty** [comment] 2017-02-13 12:44
*Which program?*
Your report is very sparse. Needing to close. Anyway, it's certainly a duplicate of many reports about Windows console/Cygwin pty incompatibility, all grounding to #56.

**Closed by mintty** 2017-02-13 12:44 UTC

**Comment by mintty** [comment] 2017-02-13 12:47
particularly duplicate of #556 in this case

**Comment by elieux** [comment] 2017-02-13 13:09
@mintty, I verified that even in Cygwin/MSYS2 `cat` MinTTY behaves this way while neither PuTTY nor Linux terminals/emulators do not. I'm still not 100 % sure it's MinTTY's fault, but even in case it's not, I would be glad if you could provide your expertise to help diagnose the problem.

**Comment by mintty** [comment] 2017-02-13 13:48
Sure I will, but a reproducible description of a problem is always a good starter, in general.
As you mention `cat`, it seems you mean *any* program. Well, except those that explicitly interpret cursor key sequences. And it's not one of the issues I referred before.
It's not a mintty issue either, to state that right away. You have the same behaviour in xterm and also Cygwin console; these are always good cross-checks for all kinds of keyboard-related issues.

It's likely different handling of "cooked mode" keyboard input by the readline library, compared with typical Linux/Unix systems. I remember it's been discussed somewhere...
You can test that the keys are actually processed normally, e.g. with `cat > test`, then enter some cursor keys. They are written to the output as expected, and they are echoed literally, rather than escaped on some other systems. Why that's different is beyond my knowledge.

**Comment by orgads** [comment] 2017-02-13 14:23
Here is an example:
![MinTTY arrows](https://ibin.co/3CG8n60DzylK.gif)

Cygwin doesn't allow movement while a process is running, but it also moves on cat, which accepts input:
![Cygwin arrows](https://ibin.co/3CG99GO1SWfm.gif)

**Comment by elieux** [comment] 2017-02-13 14:33
You're right, I should've tried other Cygwin emulators first.

1) I'm discussing the `cat` thing in #cygwin, so far no definitive answer, but it seems to be in Cygwin's tty.

2) The `sleep` thing seems to be in MinTTY.

**Comment by mintty** [comment] 2017-02-13 14:37
The "sleep thing" isn't a mintty issue either. You're right, it's different in Cygwin console (probably related to the fact that is doesn't use pty as mintty does), but it's the same in xterm.

**Comment by elieux** [comment] 2017-02-13 14:43
Seems like `cat` here sees the same in both scenarios, just the things that appear on terminal are different. Possibly interesting is that while PuTTY copies the Linux behavior, ssh'ing from MSYS2 to a Linux keeps the MSYS2/Cygwin behavior.

**Comment by mintty** [comment] 2017-02-13 16:29
Is that MSYS putty or Windows putty?
Does anything change if you vary the putty Terminal – Line discipline options?

**Comment by elieux** [comment] 2017-02-14 16:30
It's Win32 PuTTY.

when I press an arrow key | Local editing on | Local editing off
--|-------------------|-------------------
**Local echo on** | writes `^[[X`  | cursor moves and then writes `^[[X`
**Local echo off** | nothing happens | writes `^[[X`

... where `^[[X` is one of `^[[A`, `^[[B`, `^[[C`, `^[[D`.

**Comment by mintty** [comment] 2019-12-16 23:35
Cygwin 3.1.0 has been released with ConPTY support. Might affect this issue.
