### ISSUE TITLE
Adding Tabs support.

### ISSUE THREAD

**Issue by dxhisboy** [mintty/mintty#944] opened 2019-11-21 01:42 UTC
I'm adding tab support. Previous discussions is available at #8 .
Currently it is shown like this.
![image](https://user-images.githubusercontent.com/3888709/69293041-9ecf9300-0c42-11ea-9720-5d5b3e64dcfc.png)
Development branch is at https://github.com/dxhisboy/mintty/tree/dev .
The difference to current master branch of mintty is at https://github.com/mintty/mintty/compare/master...dxhisboy:dev .
@mintty The feature like GeomSync is almost the same. But I prefer a feature is that do geometry only when a mintty window wakes up another. Maybe I can merge the feature to GeomSync latter.

**Comment by dxhisboy** [comment] 2019-11-21 08:13
@mintty I found using title bar color requires the interaction with DWM after windows 7. Using the old API will produce:
![image](https://user-images.githubusercontent.com/3888709/69319130-8fb80780-0c79-11ea-9eef-f7f8161f9b33.png)
Since the theme color is handled by DWM, so `GetSysColor()` does not return the color we see.
Using DWM API may cause the program incompatible with XP?

**Comment by mintty** [comment] 2019-11-21 10:17
> But I prefer a feature is that do geometry only when a mintty window wakes up another.

You mean if you click on the tab, *that* window will be moved over the current one? Isn't that the same as `SessionGeomSync=1`: sync. position/size when switching/launching a session?

> GetSysColor() does not return the color we see.

Oh really... I'm fine with GetSysColor then. If MS applies additional theme magic and makes things inconsistent again, it's their problem, not ours...

**Comment by mintty** [comment] 2019-11-22 10:38
Test case:
* compile and run mintty-dev
* click on other tab, which captures previous (non-dev) mintty
* move the overlaid mintty away
* refocus mintty-dev

The movement leaves artefacts in the window. Apparently screen refresh is somehow postponed.
![mintty-tab](https://user-images.githubusercontent.com/12740416/69419326-88960580-0d1c-11ea-9084-0f34029f6932.png)

(Also the active tab background is very dark, text unreadable.)

**Comment by dxhisboy** [comment] 2019-11-23 13:37
Yes, that is the title bar color. Since you do not enable DWM.
I also find some screen refresh issues. Switching tabs causes the bottom 3 lines of the terminal not refreshed.
An idea is we should send message to mintty which will be put to foreground, and the receiver handle the switching procedure like sizing, positioning and refreshing.

**Comment by mintty** [comment] 2019-11-23 18:06
Do you see the same effects if you switch with the "session switcher" instead (Ctrl+click on title bar)?

**Comment by dxhisboy** [comment] 2019-11-25 06:49
I did not see same effects when doing:


> Test case:
> 
> * compile and run mintty-dev
> * click on other tab, which captures previous (non-dev) mintty
> * move the overlaid mintty away
> * refocus mintty-dev

Maybe a newer version during development handle this problem silently, or I have to disable DWM to reproduce the problem. So which windows version do you use? @mintty . I did not find a way to disable DWM.
The newer code is pushed to https://github.com/dxhisboy/mintty/tree/dev .

**Comment by dxhisboy** [comment] 2019-11-25 07:04
The bottom 3 lines problem did not go.
![image](https://user-images.githubusercontent.com/3888709/69519348-d157f380-0f94-11ea-83f1-d81b2a4b030d.png)

**Comment by dxhisboy** [comment] 2019-11-25 07:24
Now the bottom 3 lines problem is fixed by newest commit.

**Comment by dxhisboy** [comment] 2019-11-25 07:39
I found the `GeomSync=1` feature. It did not work when I use KeyFunction, now I added corresponding logic in `win_switch`, as well as tabbar initialized tab switch.

**Comment by mintty** [comment] 2019-11-25 08:09
```
if (win_tabbar_visible()) sy += TABBAR_HEIGHT;
... 2 * PADDING + sy
```
I had thought about PADDING already. It's used a number of times throughout mintty and I'm afraid all instances should be checked. My initial idea was to 1. separate PADDING into HPADDING and VPADDING, 2. make VPADDING a macro like `(PADDING + TABBAR_HEIGHT)` but that wouldn't go along well with cases of `2 * PADDING`...

**Comment by dxhisboy** [comment] 2019-11-25 08:21
> make VPADDING a macro like `(PADDING + TABBAR_HEIGHT)` but that wouldn't go along well with cases of `2 * PADDING`...
I'm formerly a Web developer, then we can consider make separate `PADDING` to `PADDING_TOP`, `PADDING_BOTTM`, `PADDING_LEFT`, `PADDING_RIGHT`.
Then I need to judge the padding should be for top or bottom, but this allows us to add more and more side bars, then the mintty becomes maxtty :fearful:.

**Comment by mintty** [comment] 2019-11-25 08:26
I'll look into the PADDING issue and check the instances, just wanted to note the issue already.
This is a big feature, so in fact max in a sense. There have been other big features before (like dynamic DPI handling, Sixel support) which took weeks or even months to get ready for integration. Good news is, you'll get an entry on the credits page :)

**Comment by mintty** [comment] 2019-11-25 08:42
I was about to say it seems to work now and suggest some layout tweaking: may make the font a pinch bigger again, e.g. size * 8 / 9 instead of * 4 / 5, leave out the initial letter (just start with three dots), and ensure some visible gap between tabs if all texts are long...

**Comment by mintty** [comment] 2019-11-25 08:44
Then I ran into this test case:
From old mintty, start tab mintty, start a third instance.
Resize window by dragging its height a bit smaller from top.
Resize again by dragging larger on top.
The window goes into endless resize flickering.

**Comment by dxhisboy** [comment] 2019-11-25 09:02
> Then I ran into this test case:
> From old mintty, start tab mintty, start a third instance.
> Resize window by dragging its height a bit smaller from top.
> Resize again by dragging larger on top.
> The window goes into endless resize flickering.

Which option value is used for SessionGeomSync in the test case? I cannot reproduce it without SessionGeomSync or `SessionGeomSync=4` and old mintty version 3.0.6.
I met many issue in synchronization between new and old mintty, and I think it will also be an idea to add some feature name suffix when registering the window class.

**Comment by mintty** [comment] 2019-11-25 09:09
This is with SessionGeomSync=4.
It also happens with only new instances running, and resizing just once.

**Comment by dxhisboy** [comment] 2019-11-25 09:10
Now I reproduced the problem randomly in mintty 3.0.6 without using the tab mintty with `SessionGeomSync=4`:
1. open several (2 or 3) mintty window from desktop shortcut.
2. iconize the last one.
3. open another mintty window, and restore the window.
Which will also cause the endless resizing loop. I think I can start debugging on this.

**Comment by mintty** [comment] 2019-11-25 09:16
Oh, really? That would be my task then, actually, but if you find a cause, that'll be great.

**Comment by dxhisboy** [comment] 2019-11-25 11:36
A basic idea: do not call other processes sync geometry when current process processing the sync message.
I pushed the code to https://github.com/dxhisboy/mintty/tree/dev .
This is done by move all `PostMessage` for `geom_sync` to `win_post_sync_msg`, and handle `WM_USER` in `win_handle_sync_msg`. In `win_handle_sync_msg`, I set a flag to determine whether the window is handling the geom_sync message, and then I immediately exit `win_post_sync_msg` if the flag is set.
This brings a side effect: when I launch a new window, its position will override the existing windows. I'm now processing this problem.

**Comment by dxhisboy** [comment] 2019-11-25 12:11
I have it work by adding a function like this:
```
void
win_init_position() {
  BOOL CALLBACK wnd_call_sync(HWND curr_wnd, LPARAM lp)
  {
    lp ++;
    WINDOWINFO curr_wnd_info;
    curr_wnd_info.cbSize = sizeof(WINDOWINFO);
    GetWindowInfo(curr_wnd, &curr_wnd_info);
    if (class_atom == curr_wnd_info.atomWindowType) {
      if (curr_wnd != wnd && !IsIconic(curr_wnd)) {
        PostMessage(curr_wnd, WM_USER, 0, WIN_INIT_POS);
        return false;
      }
    }
    return true;
  }
  if (cfg.geom_sync == 4) {
    if (EnumWindows(wnd_call_sync, (LPARAM)4)){
      win_synctabs(4);
    }
  }
///...
//In handling WM_USER
        if (!wp && lp == WIN_INIT_POS) {
          win_synctabs(4);
        } else {
          win_handle_sync_msg(wp, lp);
        }

```
When a window start separately, it firstly looks for an existing peer windows which is not iconic, if found, it post a message to the existing window, and the existing window will call the tab sync.
I'm not sure about the exact behavior of `SessionGeomSync=4`: 
1. place old windows in the position of new window.
2. place new window in the position of old windows.
If it is 1, then the last commit is right, else I will push the new code.

**Comment by mintty** [comment] 2019-12-03 11:42
I think to have fixed the mutual resize/flickering problem, as easy as possible, rather than checking your more complex patch, sorry.

**Comment by dxhisboy** [comment] 2019-12-03 12:35
Have you fixed it? 
Should I merge the tabs feature to the newest commit of mintty and prepare for further test?

**Comment by mintty** [comment] 2019-12-03 14:02
Yes.

**Comment by dxhisboy** [comment] 2019-12-07 05:58
Merged version is here: https://github.com/dxhisboy/mintty/tree/dev-merge
I'd test it for an afternoon now.

**Comment by dxhisboy** [comment] 2019-12-07 06:18
Flickering problem randomly occur in 3.1.0:
![looped](https://user-images.githubusercontent.com/3888709/70369970-20d6e180-18fc-11ea-85f1-afc0429064bc.gif)
Especially when maximizing window or opening new window. But I cannot find the cause now.
Also, trying my patch should make things clearer, while it seems complexed.

**Comment by dxhisboy** [comment] 2019-12-07 06:29
Also, the maximize is not correctly handled, in `geomsync=4`, try:
1. new terminal (term1).
2. WIN+UP to maximize it.
3. new terminal (term2).
4. WIN+UP to maximize term2.
5. WIN+LEFT to drag term2 to the left.
Then term1 is not synced.

**Comment by mintty** [comment] 2019-12-07 10:48
I think I had fixed the flickering but not yet in 3.1.0. Please recheck.

**Comment by dxhisboy** [comment] 2019-12-08 06:06
That occurs when I compiled code from master branch, commit `f63d541`.
I changed the text display strategy to remove first letter. And leave the `cell_width` as the gap between the text and tab border. The result is shown like this:
![image](https://user-images.githubusercontent.com/3888709/70384996-e769a900-19c3-11ea-89e4-e7c21d19f921.png)

Code is here: https://github.com/dxhisboy/mintty/tree/merge

**Comment by mintty** [comment] 2019-12-09 15:08
> That occurs when I compiled code from master branch, commit f63d541.

Here "That" means the double-WIN+UP issue, right? The flickering should not occur anymore.
I could reproduce the WIN+ problem on one system but not on another. Whatever, it's not intended behaviour in the first place that the second window starts at normal size. It should be captured by the previously maximized window. And you're right, full-size vs maximized is also sometimes inconsistent. Some revision to do. Not so soon, though...

The revised layout looks good, however, colour seems to be fixed. I would derive it from the system window title colour. (GetSysColor(COLOR_CAPTIONTEXT) on GetSysColor(COLOR_ACTIVECAPTION) and maybe also GetSysColor(COLOR_ACTIVECAPTION) ...)
Maybe cell_width / 2 gap would be sufficient.

**Comment by dxhisboy** [comment] 2019-12-10 01:35
`GetSysColor` seems only works in classic windows style. In my DWM eanbled system, the active tab is with color `GetSysColor(COLOR_ACTIVECAPTION)`, but the color did not look the same. I also tried `GetThemeSysColor`, it the color is also different from the title bar.
![image](https://user-images.githubusercontent.com/3888709/70487231-a098c200-1b2f-11ea-8ea2-7c0a25665498.png)
Also, using a different color on inactive tabs can leave some border with the bottom, maybe I need to draw the tabs manually instead of using builtin `TabCtrl`?

**Comment by dxhisboy** [comment] 2019-12-10 03:19
I found a piece of code to get DWM color via reading registry, maybe I will try it later.

**Comment by dxhisboy** [comment] 2019-12-10 04:29
So I also wonder why you can disable DWM to get a classic window look.

**Comment by dxhisboy** [comment] 2019-12-10 05:56
![image](https://user-images.githubusercontent.com/3888709/70499714-b1a7fa00-1b54-11ea-93c2-23fea6a39761.png)
Got it! The drawback is we need to link to a dll for DWM. Code will be pushed soon.

**Comment by dxhisboy** [comment] 2019-12-10 08:32
Self drawn tabs:
![image](https://user-images.githubusercontent.com/3888709/70512109-b5df1200-1b6a-11ea-91ac-142d95c01389.png)

**Comment by Biswa96** [comment] 2019-12-10 09:20
> I found a piece of code to get DWM color via reading registry

Say no to registry, this may help https://docs.microsoft.com/en-us/windows/win32/dwm/composition-ovw

**Comment by mintty** [comment] 2019-12-10 10:19
I was about to say, let's not tamper with themes and self-drawing here. But you've already implemented something self-drawn and it looks nice, so well.
About supporting Windows add-on features, see also my first comment above. If we decide to support e.g. GetThemeSysColor (is that DWM, actually?), we should add a generic function (extending win_get_sys_colour) that tries it first and calls GetSysColor as a fallback; also note that until now I've still maintained backwards-compatibility with Windows XP, so all newer functions should be invoked dynamically with proper fallback handling. See SetWindowTheme from uxtheme in winmain.c for an example.

**Comment by mintty** [comment] 2019-12-10 10:29
DwmGetColorizationColor is described as follows:
> Retrieves the current color used for Desktop Window Manager (DWM) *glass* composition.

So how is "glass" involved here? I'd prefer if we don't use that stuff. Glass mode doesn't seem to work anyway...
Let's do this instead:
```
  *activebg = get_win_sys_colour(COLOR_ACTIVECAPTION);
  *activetext = get_win_sys_colour(COLOR_CAPTIONTEXT);
  *inactivebg = get_win_sys_colour(COLOR_INACTIVECAPTION);
  *inactivetext = get_win_sys_colour(COLOR_INACTIVECAPTIONTEXT);
```
I'll update get_win_sys_colour to support that.

**Comment by dxhisboy** [comment] 2019-12-10 12:23
Yes, supporting both DWM and Windows XP is difficult. So I prefer registry based approach to find the color.
Tampering with self drawing is necessary to get tabs with customized color.
There is two ways:
1. one is handling TabCtrl's `WM_DRAWITEM` event, it provides the rectangle to be filled and we can position the text according to the rectangle, not many risks.
2. using windows GDI to draw the tabs, it is difficult, and handling mouse events like hover and click is complex. An advantage is this can easily handle the refreshing flickers.
I now prefer the first way because I wasted an afternoon for adjusting the layout...

**Comment by mintty** [comment] 2019-12-10 12:42
> supporting both DWM and Windows XP is difficult

I've uploaded an attempt to achieve that.
However, I don't know how to get GetSysColor and GetThemeSysColor ever return different values for testing (uncommented printf in function win_get_sys_colour in winmain.c).

**Comment by hanxi** [comment] 2019-12-17 07:12
I suggest draw min/min/close button in tab bar. like Windows Terminal.
![image](https://user-images.githubusercontent.com/1185757/70972904-77ec6b80-20df-11ea-854a-b4a09ab6a887.png)

**Comment by Biswa96** [comment] 2019-12-17 08:22
@hanxi Windows Terminal not only uses Win32 APIs but also GDI, WinRT, XAML islands, UWP and many other sooky things. Those are not avalaiable in older Windows OS versions.

**Comment by hanxi** [comment] 2019-12-17 10:15
@Biswa96 I saw this tabs feature use `WM_DRAWITEM`. So also can use Win32 API draw three buttons. And hide windows title bar.

**Comment by dxhisboy** [comment] 2019-12-17 11:06
@hanxi This may be available in maxtty... Using `WM_DRAWITEM` does not mean this is ready for creating a good artwork, I just want to switch the color of tabs.

**Comment by dxhisboy** [comment] 2019-12-17 11:53
New code is here: https://github.com/dxhisboy/mintty/tree/merge
While the windows theme can not still return the DWM colorized color correctly, I think this is also acceptable.
I'd work for modify `win_get_sys_colour` to make it support DWM if possible. Maybe via @Biswa96 's approach.

**Comment by dxhisboy** [comment] 2019-12-17 12:40
The DWM colour handling is now added in `win_get_sys_colour`.

**Comment by dxhisboy** [comment] 2019-12-30 12:42
Is there more responses or suggestions?

**Comment by mintty** [comment] 2019-12-30 16:00
When you're ready to provide a patch, I'll take a closer look, but right now it's holiday time...

**Comment by mintty** [comment] 2020-01-27 12:19
Apart from having limited time for review, the biggest issue I have with this otherwise great proposal is the location of the tab bar in the client area. This causes two problems:
* Design issue: double title area, with local tab above the tabbar.
* Implementation issue: position and size of the client area. There are lots of instances of using PADDING throughout the code. These had to be tweaked already when introducing the search bar, but some occurences had been overlooked and needed to get fixed later. Since that was at the bottom and the new change is at the top, handling is not 100% identical, and I guess we won't be able to issue this bug-free initially.

To cover both issues, it would be great to have a title-bar replacement instead. I am aware this needs additional and awkward implementation effort, since Windows does not make it easy to draw above the title bar. A starting point seems to be https://docs.microsoft.com/en-gb/windows/win32/dwm/customframe.
An alternative idea (which I had originally) would be to create a tabbar as an independent window, floating above the mintty windows' title bar. Would be tricky to keep that under control, I guess...

**Comment by dxhisboy** [comment] 2020-02-03 04:29
title-bar replacement should be a good idea to avoid padding and sizing issues, but currently I'm working on my thesis so I do not have enough time on this.
If no one helps, it is possible for me to have enough time in the April.

**Comment by mintty** [comment] 2020-02-03 09:31
I'm fine with that. Wish you good progress with your thesis.

**Comment by mintty** [comment] 2020-03-10 15:14
Not meaning to disturb your thesis, just a different and possibly much easier solution to my concerns comes to my mind: the text pane could be managed in its own subwindow, replacing the main window in all text-related use cases, and positioned properly; addressing within the text window would not need to be changed in that case (just the height is reduced, like for the search bar).
The tricky part is that right now, the text pane window is the same as the main window with all borders and title frames. A bit fiddly to set up, but likely much less error-prone than the two approaches previously discussed...

**Comment by hanxi** [comment] 2020-04-26 10:28
Found a Custom Titlebar demo here. http://www.catch22.net/tuts/win32/custom-titlebar

**Comment by BrianInglis** [comment] 2020-04-26 12:31
Article is irrelevant as it says:
> Important
Note that this article was originally written in 2001 - it is only relevant for Windows 95/98/ME and Windows NT/2000/XP. Customizing the titlebar in Vista and Windows 7 (using the Aero theme) requires overlaying windows on top of the titlebar.

**Comment by mintty** [comment] 2020-06-21 11:27
Concerning the original approach of this proposal (i.e., modifying the upper PADDING to insert the tabbar):
I have finally taken the time to check some interworking places in mintty code.
Only a few places had been patched to compensate for the new tabbar offset, so some size and position-related features would not work correctly with the previous patch. I hope to have caught the cases properly, in files winimg.c wininput.c winmain.c wintext.c.

It seems the previous solution was inconsistent (by padding pixels) whether TABBAR_HEIGHT includes PADDING:
	win_text, translate_pos:
		max(PADDING, TABBAR_HEIGHT)
or not:
	win_get_pixels: sy += TABBAR_HEIGHT
Therefore I defined an OFFSET which can be used for the tabbar; the normal upper PADDING would be located below this space.

My changes can be tested with something like int OFFSET = 40 in wintext.c.

For compatibility and some formatting, please apply the following patch to wintab.c:
[wintab.patch.txt](https://github.com/mintty/mintty/files/4809352/wintab.patch.txt)
and check two places marked with "///".

One more issue I had noted from my previous testing (not yet retested): if you click your own tab , it defocusses your window.

I'd appreciate a rebased patch proposal, only adding wintab.* and hooking into winmain.c (with small footprint appreciated) please. Config option is already provided.

**Comment by paolo-sz** [comment] 2020-07-02 14:03
Just my 2 cents...
Did you have a look to fatty project originally forked from mintty https://github.com/paolo-sz/fatty (this is my fork of fatty project which I keep aligned with mintty latest commits)?
The intent of fatty is exactly to add the tabbar...

**Comment by mintty** [comment] 2020-07-02 14:50
See my previous comments about criteria how to integrate tabs with mintty terminal code (don't find the issue right now)
and on fatty (mintty/wsltty#245) which does not meet the criteria and is hopelessly outdated anyway.

**Comment by mintty** [comment] 2020-07-22 09:55
For the records: For drawing on the title bar, in addition to creating a window floating on top of it, there seem to be two easier options:

- GetWindowDC (mentioned in the reference above) which however does not affect the title bar anymore (as Brian noted) but maybe there is some tricky "style" setting that would reactive this feature

- GetDC(0), which allows to paint on the whole screen. Problems are positioning and clipping (which would need to be done explicitly)

**Comment by mintty** [comment] 2020-08-19 16:53
I have rebased the tabbar implementation to the current repository version of mintty, adjusting to my recent patch to provide for a tabbar OFFSET consistently. It seems to work, although I did not include some of the changes in winmain.c (win_init_position, win_handle_sync_msg, dont_post_sync_msg).
Please check whether those are needed. Also there are some places marked "///" in winmain.c and wintab.c, please check them too.
[mintab.patch.txt](https://github.com/mintty/mintty/files/5097986/mintab.patch.txt)

**Comment by mintty** [comment] 2020-08-28 19:55
I have further tweaked the patch and committed it (`--author="Xiaohui Duan <dxhisboy>"`).
Please test and comment.

**Comment by mintty** [comment] 2020-09-02 10:59
I hope to have fixed a few artefacts of background padding. Frame border 3D effect was inconsistent among tabs and setting `Padding=` to a higher value produced a broken gap (red marker in image). There is still an artefact marked violet in the image but that's a minor issue.
![tabbar](https://user-images.githubusercontent.com/12740416/91973192-1aa35380-ed1c-11ea-944e-cb3718c2b4c3.png)

**Comment by mintty** [comment] 2020-09-02 11:06
These are open issues:
* Interworking with background image (setting `Background=`) is broken; the tabbar would not be shown.
* The tab highlighting in the tabbar should be cleared when activating another tab, in case of un-synced window positions.
* Configuration is not very comfortable as you need to combined settings `ShowTabBar` and `SessionGeomSync` right now.

Further issues (not specific to the tabbar but more apparent and disturbing with it):
* If you move the window, overlayed windows will be visible below until moved. Maybe they should be hidden to prevent this.
* If the window is maximized, others are resized to full-size too but not technically maximized. This causes title bar appearance to flip when switching tabs.

**Comment by mintty** [comment] 2020-09-05 06:42
Fixed: background image.
New: initial activation of tabbar display (was previously not discovered as my prompt sets a window title); check from original patch.

**Comment by mintty** [comment] 2020-09-06 06:02
Fixed initial display of tabbar.
The technical feature is now ready for release.
Still thinking about better configuration (and some minor issues).

**Comment by mintty** [comment] 2020-09-11 15:29
There are still some quirks when resizing or minimizing a window; the other tabs don't always follow as they should.
This isn't new, it's been a bug of the synchronization mechanism already, it just becomes more apparent via the tabbar.
Any opinion whether the feature should be released as-is?

**Comment by mintty** [comment] 2020-09-11 17:38
I guess I have to withdraw my previous comment. Observed behaviour happens after starting one terminal with tabbar enabled, then adding more with Alt+F2, without that setting.
If all tabbed windows are consistently configured to a common synchronization level, behaviour seems to be fine.

**Comment by mintty** [comment] 2020-09-17 17:12
Released 3.4.0.

**Closed by mintty** 2020-09-17 17:12 UTC

**Comment by sarim** [comment] 2020-11-14 17:58
What is the recommended config for enabling tabbar?  I have 
```
ShowTabBar=yes
SessionGeomSync=4
```

I tried SessionGeomSync to 1,2,3,4 but the tabbar isn't showing up. It moved to tabbed mode I guess, bcz when I hit alt-f2 new window is created at the same location, If I drag all goes to same position etc... But tabbar isn't showing up.

Also I have `Transparency=medium`, and other unfocused tabs can be seen in background, which kinda breaks transparency .... 
Unfocused tabbed should be hidden, right?

**Comment by mintty** [comment] 2020-11-14 18:33
Option SessionGeomSync existed before the tabbar. The tabbar is enabled with option ShowTabBar. Above configuration is OK, ShowTabBar=4 would also be sufficient.
About transparency, that's a deficiency indeed.

**Comment by sarim** [comment] 2020-11-14 18:38
Umm not sure what I'm doing wrong, but adding `ShowTabBar` to  `C:\Users\Sarim Khan\AppData\Roaming\wsltty\config` isn't working. ` --tabbar` Flag is working though. Not sure what is the issue.

**Comment by sarim** [comment] 2020-11-14 18:43
Ok I took a quick peek at https://github.com/mintty/mintty/blob/master/src/config.c#L496. The option is `TabBar`. Setting `TabBar=yes` is working.

> ShowTabBar=4 would also be sufficient
Umm in config.c its boolean. Why 4?

**Comment by mintty** [comment] 2020-11-14 18:54
Yes, the option name had changed from a preliminary version.
The data type in config.h is int. The OPT_BOOL class in the options table of config.c enables value `yes` for backwards compatibility with initial release.

**Comment by sarim** [comment] 2020-11-14 19:08
Thanks, makes sense. Is there a option to hide tabbar when only one windows is present?

**Comment by mintty** [comment] 2020-11-14 22:53
No. A tabbar is a tabbar. When such "clever" feature came with the introduction of tabbars in web browsers, I felt quite annoyed...

**Comment by sarim** [comment] 2020-11-14 23:02
Okey. What is the end goal of the tabbar feature? It looks a bit ugly, especially in a dark themed system... (I already fiddled with Tab-foreground-background-colors.) Also keeping all windows open and visible also looks broken, when I drag the foremost window, I can see other windows behind. Also the issue with transparency. I see this issue is closed, Do you have plans to polish it further?

**Comment by mintty** [comment] 2020-11-15 06:58
The transparanecy and bottom windows issues are something to be tweaked, and layout may be tweaked too.
Also, as I had suggested earlier, an alternative tabbar might be displayed above the window title bar instead of below it.
However, especially the latter is a tough implementation challenge.
And the whole tabbar feature was contributed by K. Takata, I only supported the integration. Meaning I am not really motivated to spend huge effort into it.

**Comment by k-takata** [comment] 2020-11-15 10:23
> And the whole tabbar feature was contributed by K. Takata,

It's not true. I only tweaked it after 3.4.0.
The whole work before 3.4.0 was done by Xiaohui Duan.

**Comment by mintty** [comment] 2020-11-15 10:39
> The whole work before 3.4.0 was done by Xiaohui Duan.

Oh right, sorry. Fixing my previous comment.

**Comment by rbreaves** [comment] 2020-12-03 06:31
Well I am ecstatic that mintty finally has tabs, even if a bit rudimentary! I think this is one of the best terminals on Windows by miles and has simply always lacked the tab feature. To me it is insane how well it runs how few issues I have with it compared to everything else I have tried on Windows.

Might I suggest that mintty hooks on Ctrl+T to open new instances/tabs? As well was Ctrl+W to close them?

**Comment by mintty** [comment] 2020-12-03 07:38
Control characters are expected to work verbatim in a terminal as they are often used by applications, such as text editors. If you really want them reused, there is option CtrlExchangeShift. And then there are user-definable key assignments. So you can achieve your suggested configuration with `-o "KeyFunctions=t:new-window;w:close" -o CtrlExchangeShift=yes`.

**Comment by rbreaves** [comment] 2020-12-03 17:37
I am actually more than happy to not use the "CtrlExchangeShift=yes" portion of your suggestion as the ```KeyFunctions=t:new-window;w:close``` part of your suggestion was perfect on its own!

I am the author of [kinto.sh](https://github.com/rbreaves/kinto) which tries to make things more mac like hotkey wise on Windows and Linux, and while I fake things out where it seems like single pair hotkeys are being pressed I am actually making the typical Alt key perform as Ctrl+Shift, Win as Alt and Ctrl as Ctrl. When making my suggestion earlier I should have specified with Ctrl+Shift - but I sometimes forget about what it is that is actually going on behind the scenes myself 😅.

Thank you for maintaining and creating mintty! It is without a doubt the best terminal emulator on Windows.

**Comment by mintty** [comment] 2021-07-23 13:20
Implemented tab management, including tab transparency support by hiding background tabs, and regular checks to keep the tabbar consistent in case a tab window is killed.
Available in the repository, testing is appreciated.

**Comment by mintty** [comment] 2021-09-03 20:02
Had to revert transparency support (see https://github.com/mintty/mintty/commit/71a1475c9e1412e08a36124028dfbada8d982f37).
Released 3.5.1 with tabbar consistency management.

**Comment by DanKaplanSES** [comment] 2022-02-01 22:09
It was difficult for me to figure out how to turn this feature on. The answer is sprinkled through the comments of this issue, but not in one place. Therefore I'm posting this to save time for others. Here's how you turn the feature on:

Add `--tabbar` to the windows shortcut that opens mintty:

![image](https://user-images.githubusercontent.com/373675/152059464-991b3439-34b5-4650-9627-6781a6393be3.png)

If you'd like to create new tabs with `ctrl-t`, close tabs with `ctrl-w`, and switch tabs with `ctrl-shift-t`, add `-o "KeyFunctions=t:new-window;w:close" -o CtrlExchangeShift=yes` to the same line.

**Comment by mintty** [comment] 2022-02-01 22:48
There is a manual page with a section about Virtual Tabs and all options.

**Comment by DanKaplanSES** [comment] 2022-02-01 22:57
@mintty Yeah found that in there after my comment, sorry. 

I'm inferring that each tab requires a separate window, but I'm not 100% sure. Is that the case? I'd personally prefer every session to share a single window so I don't have to click twice to open the terminal from the taskbar (once to click the icon, another click to choose the session). I'm not sure if that'd be a new feature request or an existing setting that needs to be turned on.

Also, is there a way of making `ctrl-t` open a new tab without `CtrlExchangeShift=yes`? I like all the other shortcuts exactly the way they are. I only want to add `ctrl-t`, like a browser works. Again, I'm not sure if that'd be a new feature request or an existing setting that needs to be turned on.

**Comment by mintty** [comment] 2022-02-01 23:28
> I'm inferring that each tab requires a separate window

Yes, that's why it's called Virtual Tabs mode. It's a concept restriction to ensure stability which was sufficiently discussed above. Not sure what you mean about clicking twice. A mintty terminal session is started from the taskbar like all other applications, you can also just double-click.

> Also, is there a way of making ctrl-t open a new tab without CtrlExchangeShift=yes

Certainly not. Control-t is a normal ASCII character. All control characters are expected to be available verbatim by traditional terminal users, so it's not a good idea to redefine them.

**Comment by DanKaplanSES** [comment] 2022-02-01 23:33
> Not sure what you mean about clicking twice. A mintty terminal session is started from the taskbar like all other applications, you can also just double-click.

To create the first session, that's true. But when there are multiple windows, double-clicking works the same way as single clicking: it just shows thumbnails of all the open windows. Windows only focuses one of those sessions after I click on a thumbnail.

**Comment by mintty** [comment] 2022-02-01 23:50
You select one of the thumbnails and get it focussed, sounds correct.

**Comment by DanKaplanSES** [comment] 2022-02-01 23:54
For me that's two clicks. One to popup the thumbnails, another to click the thumbnail. Based on your reply, I'm assuming there's no way to choose the first/any window when I click the icon. Thanks for your time.

**Comment by mintty** [comment] 2022-04-15 16:28
> Also, is there a way of making ctrl-t open a new tab without CtrlExchangeShift=yes

Yes, meanwhile, with 3.6.0, there is option ShootFoot which allows you to redefine Control+letter combinations via setting KeyFunctions.
