### ISSUE TITLE
Fullscreen is sometime masked by the taskbar

### ISSUE THREAD

**Issue by nowox** [mintty/mintty#681] opened 2017-08-21 15:23 UTC
I still haven't figured out what cause this issue to happen, but sometime when I hit <Alt-Enter> my mintty session enters in fullscreen mode, but the taskbar still masks my terminal. The workaround is: 

- Exit fullscreen
- Change the focus for another window
- Re focus on Mintty

Is this a mintty bug?

**Comment by mintty** [comment] 2017-08-21 17:06
If you configure your taskbar to automatically fade in/out, it is not accounted for the screen work area.
If it then fades in, it will overlap fullscreen windows.
If you fix the taskbar, the work area is considered without the taskbar space.
If that's not the effect, please describe in more detail.

**Comment by nowox** [comment] 2017-08-22 09:02
Not sure I perfectly understand what you're saying. My taskbar is locked on my screen. It doesn't fade in/out. 

Just now I have the issue. I just hit `<Alt+Enter>` several times and the taskbar is still masking my terminal. 

![image](https://user-images.githubusercontent.com/1132849/29557315-f7fb5c44-8728-11e7-90da-25f1f282ec11.png)

Now I am writing this reply, I changed my focus to chrome. If I go back to my terminal by just clicking into it works: 

![image](https://user-images.githubusercontent.com/1132849/29557416-4b5cfd84-8729-11e7-83c2-a9d560068f59.png)

**Comment by mintty** [comment] 2017-08-22 21:57
For me, if I fix the taskbar, Alt+Enter brings mintty on top of it. So there must be more system configuration parameters that have an impact on the issue. I cannot reproduce it.

**Comment by mintty** [comment] 2017-10-23 08:27
> Is this a mintty bug?

Likely not. Closing, but we can reopen if you provide more background to make it reproducible.

**Closed by mintty** 2017-10-23 08:27 UTC
