### ISSUE TITLE
MinTTY hanging on node script readline

### ISSUE THREAD

**Issue by Tobbe** [mintty/mintty#965] opened 2020-02-17 03:49 UTC
At first I thought this was a node.js problem, and filed a bug report with them. But they seem to think it might actually be a problem with MinTTY, so I'm adding a bug report here as well.

It is not reproducible in Command Prompt or PowerShell, only MinTTY. That's why they don't think it's a node issue.

This is a copy/paste of the original bug report, https://github.com/nodejs/node/issues/31762

---

* **Version**: node v13.8.0
* **Platform**: Win 10 64-bit
* **Subsystem**: Git For Windows 2.25.0, mintty 3.1.0 (x86_64-pc-msys)

### What steps will reproduce the bug?

```
#!/usr/bin/env node

const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
});

readline.question('> ', answer => {
    console.log('answer', answer);
    readline.close();
});
```

Running the above relying on the hash-bang/she-bang, `./readline.js`, will make it hang. 

Running the above using node, `node readline.js`, everything works as expected

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

The program should exit back to the shell after the user has pressed <kbd>Enter</kbd>

### What do you see instead?

The program hangs and I can't kill it either by Ctrl+D nor Ctrl+C

### Additional information

A workaround is to wrap the `close()` call in a `setTimeout` like so

```
#!/usr/bin/env node

const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
});

readline.question('> ', answer => {
    console.log('answer', answer);
    setTimeout(() => readline.close());
});
```

This comment is similar, but that one states that it works in Win 10. That is not my experience. 
https://github.com/nodejs/node/issues/17495#issuecomment-414333565

**Comment by k-takata** [comment] 2020-02-17 03:57
It's not a mintty issue. Use winpty.
(ConPTY should also fix the issue, but Git for Windows doesn't support ConPTY yet.)
See #56 and related issues for detail.

**Comment by mintty** [comment] 2020-02-17 08:19
Could also be a duplicate of #540.

**Comment by Tobbe** [comment] 2020-02-17 13:32
Found this old SO question https://stackoverflow.com/questions/34559978/node-js-on-windows-git-bash-shebang-failure

The suggested solution, to first run `winpty bash`, worked (but seems a bit slow)

**Comment by mintty** [comment] 2020-05-20 16:25
So it should also work in cygwin 3.1.0 or later on a recent Windows release. Closing.

**Closed by mintty** 2020-05-20 16:25 UTC
