### ISSUE TITLE
Very slow scrolling with Neomutt

### ISSUE THREAD

**Issue by Noomene** [mintty/mintty#898] opened 2019-08-05 16:07 UTC
Dear Devs,

First, Thank you for Mintty.

I've started using Neomutt in Mintty (Cygwin on Windows 7 Pro) recently and I have noticed Mintty becomes extremely slow. When scrolling through the message index in Neomutt using the keyboard, the scrolling is ridiculously slow. The same Neomutt works rather fast in all other terminals I tried it on, including cmd.exe and Powershell.

I excluded mintty, bash and neomutt from my antivirus because I read that could cause the issue, but that didn't help.

Tried to tweak around the config file testing different options I found on the mintty official manual, but nothing helped.

Here is my version :

mintty 3.0.2 (x86_64-pc-cygwin)
© 2013/2019 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later

Thank you for your help,

**Comment by mintty** [comment] 2019-08-05 20:24
A reproducible test case is needed. In this case, since I'm not familiar with neomutt, this includes:
* description how to configure neomutt to expose a message index
* description how to scroll the message index (and produce the effect)

**Comment by mintty** [comment] 2019-08-06 06:08
Alternatively, you can make a terminal log (`mintty -l logfile.txt`) and check whether the effect is reproduced when catting it (`cat logfile.txt`).

**Comment by Noomene** [comment] 2019-08-06 13:34
**Thank you very much for your reply.**

Here are the steps to set up neomutt on cygwin for testing. I suggest using a spare email account for this.

1. Install Neomutt through the package manager of Cygwin on Windows 7 x64 Pro 

2. In the home directory of Cygwin create the following folders :

> ~/.neomutt/user.gmail/
and
> /.config/neomutt/

in the latter folder create the file 

> neomuttrc

Enter the following settings in this rc file substituting 'user' with some spare email account and substituting a password (in this case plain text) :

> set from = user@gmail.com
> set realname = 'user'
> 
> set hostname = 'gmail.com'
> set folder = 'imaps://user@imap.gmail.com:993/'
> 
> set ssl_force_tls = yes
> set imap_user = user@gmail.com
> set smtp_url = 'smtps://user@smtp.gmail.com:587/'
> 
> set header_cache = '~/.neomutt/user.gmail/.cache'
> set message_cachedir = '~/.neomutt/user.gmail/.cache/bodies'
> 
> set imap_pass = XXXXXXXX
> set smtp_pass = XXXXXXXX
> 
> set spoolfile = 'imaps://user@imap.gmail.com:993/INBOX'
> set postponed = "+[Gmail]/Drafts"
> set trash = "+[Gmail]/Trash"
> unset record
> 
> unset imap_passive
> set mail_check = 60
> set mbox_type = Maildir
> set mailcap_path = ~/.neomutt/mailcap
> set tmpdir = ~/.neomutt/tmp

> set abort_nosubject = ask-no
> set abort_unmodified = ask-no
> set askbcc = yes
> set askcc = yes
> set beep_new = yes
> set content_type = 'text/html'
> set delete = ask-yes
> set delete_untag = no
> set mark_old = no
> 
> set fast_reply = yes
> set forward_format = "Fwd: %s"
> set edit_headers = yes
> set editor = 'nano %s'
> set forward_quote = yes
> set include = yes
> set sig_dashes = yes
> set mime_forward = no
> set menu_scroll = yes
> set mail_check_stats = yes
> set mail_check_stats_interval = 30
> set menu_context = 1
> set pager_index_lines = 10
> set pager_stop = yes
> set quit = yes
> set reply_to = ask-yes
> 
> ## index menu
> set date_format = '%d.%m.%y  %H:%M'
> set index_format = '%3C %Z %-60.60s %-35.35L %-15.15d'
> set to_chars = 't>gc<l'
> 
> ## sidebar
> set sidebar_visible = yes
> set sidebar_delim_chars = '/'
> set sidebar_format = "%B %> %?N?[?%?N?%N?%?N?]?
> set sidebar_short_path = yes
> set sidebar_folder_indent = no
> set sidebar_width = 27
> set sidebar_divider_char = ' | '
> set sidebar_indent_string = '  ''
> set sort = 'reverse-date-received'
> 
> set sleep_time = 0
> set strict_threads = yes
> set text_flowed = yes
> set tilde = yes
> set timeout = 0
> set use_from = yes
> set smart_wrap = yes
> set time_inc = 500
> set ascii_chars = no
> set arrow_cursor = no
> set charset = "utf-8"
> set assumed_charset = "ascii:utf-8:windows-1252:iso-8859-1"
> set header_cache_pagesize = 131072
> 
> set header_color_partial = yes
> color attachment   brightblack default
> color error        brightred  default
> color hdrdefault   brightblack default
> color indicator    default    red
> color markers      brightcyan default
> color message      default    default
> color normal       default    default
> color quoted       cyan       default
> color search       default    green
> color signature    brightblue default
> color status       yellow     blue
> color tilde        magenta    default
> color tree         magenta    default
> color header 	    green		default "Date:|From:|To:|Subject:"
> 
>
>macro index <f4> '<enter-command>set index_format = "%3C %Z %?X?\"& ? %-60.60s %-35.35L %-15.15d"<enter>'
>macro index <f5> '<enter-command>set index_format = "%3C %Z %-60.60s %-35.35L %-15.15d"<enter>'
>
> bind pager [ half-up
> bind pager ] half-down
>
> source "~/.neomutt/.noomen.belmechri.gmail"

> mailboxes "[email 1]------" 'imaps://user@imap.gmail.com:993/INBOX' 'imaps://user:993/[Gmail]/Sent Mail' 'imaps://user@imap.gmail.com:993/[Gmail]/Drafts' 'imaps://user@imap.gmail.com:993/Archives' 

3. Start 'neomutt' from mintty

4. try to scroll the messages using the arrow keys. The Scrolling is so slow, that pressing the key once makes the indicator scroll almost one full page before stopping.

**Comment by Noomene** [comment] 2019-08-06 13:48
I got the logfile. Is there a way to direct message it to you because it has some private information?

**Comment by mintty** [comment] 2019-08-06 14:00
Oh! I guess most of that config is not necessary but I can copy it and maybe use some test account.
Does the log file exhibit the issue? Can you blank out the personal info with an editor?

**Comment by mintty** [comment] 2019-08-06 15:30
I've run neomutt now. Apparently, configuration failed and it accesses a local mailbox file.
This should not affect screen behaviour, though. I can scroll seamlessly through the mail list.
I guess you may be having some mailbox access problem perhaps?
Please cross-check with another cygwin-based terminal, e.g. xterm.

**Comment by Noomene** [comment] 2019-08-07 00:51
Thank you for your reply.

I've attached the logfile.txt below. How do I check in it if the issue is there. When I run the cat command in cmd.exe it scrolls extremely fast.

The strange part is that when I run 'cat logfile.txt' in cmd.exe it shows a fast and clean output of the full neomutt index etc, but when I run the same command in mintty it only shows the first few lines then stops!! I can't explain this. When I tried the same command in Cmnder for example, the output was complete but all scrambled up. Don't know what's wrong with my terminal emulators.

If you can run neomutt with an email account that has around 3000 emails like mine and you cannot reproduce the slow scrolling issue then it's something unique to my system maybe and has nothing to do with mintty. What made me think it's mintty is that the scrolling is relatively ok on other emulators and only with mintty do I see the slow scrolling.

Finally I don't think it's a connection problem because all email headers are cached locally.

Thanks again. Sorry if this issue is probably due to my system.

[logfile.txt](https://github.com/mintty/mintty/files/3474689/logfile.txt)

**Comment by mintty** [comment] 2019-08-07 05:17
I checked whether there are a bunch of report requesting or window operations in the log, but there are only a few window title push/pop operations, no indication of a problem.
Note that cmd.exe and cmder are not really "terminal emulators". If you want to cross-check, as I said, you should compare with something like xterm.

**Comment by mintty** [comment] 2019-08-08 07:56
Closing this as there is no indication of a mintty issue.

**Closed by mintty** 2019-08-08 07:56 UTC

**Comment by Noomene** [comment] 2019-08-08 15:41
Thank you very much for taking the time to answer my questions.
I have checked with xterm, it's normal. Scrolling is as fast as the other terminals.
The issue appears only with Mintty on my system. I can't explain why exactly, so for now I will be switching to xterm and will update if I find out the reason why mintty is so slow on my system.

Thanks again for trying to help.

**Comment by mintty** [comment] 2019-08-08 20:53
I've now configured neomutt to use a real imap account (also on gmail) - no scrolling problems.
Have you, by any chance, used the new fun option `Baud`?

**Comment by Noomene** [comment] 2019-08-13 01:39
What is the `Baud` option. How do I try it?

**Comment by Noomene** [comment] 2019-08-13 01:49
Ah yes, now I remember I tried that just to see what it does, and I also tried DisplaySpeedup. I think my install already feels like a serial terminal and does not need mote of it.

**Comment by mintty** [comment] 2019-08-13 11:42
The question was, particularly as you have indeed tried that option, whether it is active while you experience the slow scrolling, as it would completely explain the effect.

**Comment by Noomene** [comment] 2019-08-13 13:50
Nope, it was not active. I tried it out of curiosity then turned it off. I was hoping DisplaySpeedup would help at value 9 but it didn't. I tried a few other options too from the manual but nothing helped. I turned off my antivirus protection and set the executables as exceptions to the realtime protection, still nothing. So .. I now installed a light weight linux and am using it with mutt and surprisingly, even though it is inside an actual virtual machine, it runs pretty smoothly.

**Comment by mintty** [comment] 2019-08-13 13:58
But still, you've experienced this issue only within mutt, right?

**Comment by Noomene** [comment] 2019-08-13 18:01
While trying it in a linux VM with a clean config I found the reason why it was slow. It was a neomutt issue not a mintty issue. There was one parameter, `timeout`, that I had set to 0, and by just changing it to 5, the issue magically disappeared, and it ran as fast as a text based app should run.

So yeah, it was not mintty. Although, the fact that it ran faster on other emulators could be something to look at.

The advantage that I found in mintty now is that mintty has a much better support for 256  colors, which was a pain to configure in other emulators.

Thanks again for your help.

**Comment by mintty** [comment] 2019-08-13 21:19
So what does that parameter `timeout` do? It's not described in `man neomutt`.

**Comment by mintty** [comment] 2019-08-14 06:39
OK, `man neomuttrc` mentions a timeout setting and a timeout-hook command (do you use that?).
Still not reproduced.
Trying your full neomuttrc, neomutt reports errors for the two 'macro' lines and does not find the 'source' file. What if you disable those?

**Comment by Noomene** [comment] 2019-08-14 14:52
It's actually here http://www.mutt.org/doc/manual/#timeout
Here is what it does :

> Type: number
>Default: 600
>When Mutt is waiting for user input either idling in menus or in an interactive prompt, Mutt would block until input is present. Depending on the context, this would prevent certain operations from working, like checking for new mail or keeping an IMAP connection alive.
> This variable controls how many seconds Mutt will at most wait until it aborts waiting for input, performs these operations and continues to wait for input.
>A value of zero or less will cause Mutt to never time out. 

It's really counter intuitive, I put it at 0 initially thinking it would have the opposite effect.

As for your question, you can remove the two macros, they're optional, and you can remove the source files too, those are just if one wants to use more than one email account. But with just one account you can define everything in the main config file without having to call external files. So as long as you have your imap/smtp server setup, your username, your password, and the main configs set up, no need for the source file. Here is the basic config :

>set from = user@gmail.com
>set realname = 'user'
>
>set hostname = 'gmail.com'
>set folder = 'imaps://user@imap.gmail.com:993/'
>
>set ssl_force_tls = yes
>set imap_user = user@gmail.com
>set smtp_url = 'smtps://user@smtp.gmail.com:587/'
>
>set header_cache = %HOME%/.neomutt/user.gmail/.cache
>set message_cachedir = %HOME%/.neomutt/user.gmail/.cache/bodies'
>
>set imap_pass = XXXXXXXX
>set smtp_pass = XXXXXXXX
>
>set spoolfile = 'imaps://user@imap.gmail.com:993/INBOX'
>set postponed = "+[Gmail]/Drafts"
>set trash = "+[Gmail]/Trash"
>unset record
>
>unset imap_passive
>set mail_check = 60
>set mbox_type = Maildir

The other settings are mainly optional. They are quoted in my second comment from above where I listed my mutt settings.

ps: I moved to mutt now. Neomutt is a branch that was supposed to be better by adding a couple of patches while using the same configs. But surprisingly it turned out to be worse, and much less maintained than the main mutt. And the dev is absent. I directed my question about this issue to him initially before asking here, but he never responded. So I moved to mutt which is much better maintained.

**Comment by Noomene** [comment] 2019-08-14 14:59
And nope I don't use the timeout-hook command.
