### ISSUE TITLE
Windows 7 DPI setting distorts pixel fonts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#352] opened 2015-06-04 13:04 UTC
```
What steps will reproduce the problem?
1. Set a non-standard DPI setting in Windows 7 (eg. 125%)
2. Set a pixel font in mintty.

What is the expected output? What do you see instead?
Crisp, clear, perfectly aligned pixels. Instead the font is distorted due to 
the DPI scaling.

What versions of mintty, Cygwin/MSYS, and Windows are you using?
mintty 1.1.1

Please provide any additional information below.
I realise that this is not so much an issue with mintty, but perhaps there is 
some way to reverse the scaling? I need the scaling system-wide, but it would 
be nice if I could disable it in mintty. Setting "Disable display scaling on 
high DPI settings" under shortcut -> Properties -> Compatibility doesn't seem 
to have any effect. I also tried compensating for the adjustment by setting the 
font size to 9.6, but point sizes aren't allowed (is that a Windows thing?).
```

Original issue reported on code.google.com by `kelseyjudson` on 17 Sep 2012 at 3:11

**Comment by mintty** [comment] 2016-02-21 07:21
Same effect with simply scaling the font, without tweaking the DPI.
This is the normal manifestation of pixel fonts.
Marking invalid.

**Comment by chainjazz** [comment] 2019-06-06 21:40
I know how to bypass the scaling.

Essentially, mintty is not "high-dpi aware", but that can be said for numerous built-in Windows utilites (such as mmc, msi GUIs, etc.)

Normally, you would disable high DPI scaling in the Compatibility tab of an executeable property page. (By default, Windows 7 has a hack activated under custom DPI settings to use "XP-mode style scaling" but that's really a hack and has side-effects)

High-DPI compatibility switch is not available for 64-bit applications under Windows 7.

A working trick is to spawn mintty from a 32-bit terminal (which is not present on 64-bit Windows). I believe there's a 32-bit mintty?

On a side note, why do we need 64-bit terminal emulator in the first place?

Hope this helps.
Cheers

**Comment by mintty** [comment] 2019-06-06 22:03
Mintty does handle DPI scaling. There is an option HandleDPI to adapt to system capabilities. See #824 for a recent issue. Do you use a current version?

In a cygwin 32-bit installation, you'll use the 32-bit mintty, in 64-bit cygwin the 64-bit mintty. It's a cygwin condition.

**Comment by chainjazz** [comment] 2019-06-07 12:20
OK, I was misinformed. I'm guessing the parameter you're talking about is in the .ini file? I'll check, but it took me a while to figure it out. Yeah, I'm using 3.0.0 x86_64

**Comment by chainjazz** [comment] 2019-06-07 12:32
Apparently, and according to the manpage, HandleDPI is for Windows 10. Unfortunately, I'm using Win 7.

**Comment by mintty** [comment] 2019-06-07 13:23
HandleDPI is only about changing DPI value, especially between multiple monitors with different DPI scaling; this is only supported by Windows 10.
Before DPI handling mode V2 recently introduced, Windows DPI handling was in fact poor and ill-designed; there isn't much an application could do about it.

**Comment by chainjazz** [comment] 2019-06-07 17:16
I beg to differ. How would you explain then, for example, latest Visual Studio Installer running on Win 7? Or a more relevant example - Windows Command Prompt or Powershell? Maybe we are not talking about the same thing. I'm not trying to waste your time - I am not a professional programmer, so I don't know much, just talking from experience with Windows.

**Comment by chainjazz** [comment] 2019-06-07 17:24
There is the matter of DPI/PPI, and there is also the matter of scaling. I guess scaling is not the same as adapting.

Win 7 uses Vista's technology for scaling, which, AFAIK, is a primitive DirectX raster thing. It pixelates the visible text.

Per-monitor DPI is something I probably haven't seen, I don't think Win 7 supports it. However, there are two things going on there: the "Disable high DPI scaling..." switch, and programs which do not require this to display crisp stuff. Whether they adapt to multi-monitor setup, I don't know.

**Comment by mintty** [comment] 2019-06-08 07:03
I'm not involved with Visual Studio and I don't see what you're trying to point it here.
However, please note that the DPI issue has been extensively discussed and kind people supplied patches to mintty to handle it - as far as possible, i.e. not really well in Windows 7.

**Comment by chainjazz** [comment] 2019-07-02 17:19
Mentioned VS *installer*, since the latest version is kind of a backwards-compatible windows software. It has perfect font scaling on Win 7, so "there isn't much an application can do about it" doesn't fit into the evidence.

**Comment by BrianInglis** [comment] 2019-07-02 17:48
Does not sound like the kind of package which supports much user choice of window sizes, fonts, and graphics or themes: often just a series of dialogue boxes, so they can just select or bundle alternatives which look and work well in each supported environment, and add spacing to fit larger areas. 
Other packages allow any supported window size, spanning multiple monitors, with user selected fonts, and graphics or themes, so have to handle all the possibilities just to display properly, and may need tweaks to display as clearly and cleanly as possible in all configurations.

**Comment by mintty** [comment] 2019-07-04 10:21
I was distracted by the fact that this issue was originally reported against mintty 1.1.1.
However, I could reproduce blurred font rendering on Windows 7 at 150% screen scaling.
The issue does *not* happen with mintty 2.1.5; apparently it was introduced (reintroduced?) with per-monitor DPI support in 2.2.1 (#470), and not reported by anyone else since.

**Comment by mintty** [comment] 2019-07-07 10:18
Actually, this issue was originally reported about "pixel fonts", which is another issue. So I'm closing it again.
I've entered a new issue about Windows 7 DPI scaling.
A solution is available.
As a workaround, you can also open the properties of your mintty desktop shortcut and enable the "DPI ... whatever" option you'll find on the "Compatibility" tab.

**Closed by mintty** 2019-07-07 10:18 UTC
Labels: bug
