### ISSUE TITLE
Failed to compile in current MSYS2 environment

### ISSUE THREAD

**Issue by kangjianbin** [mintty/mintty#668] opened 2017-06-27 08:49 UTC
```bash
gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  -fstack-check child.c -o ../bin/msys64/child.o
```
```
In file included from child.c:18:0:
child.c: In function ‘child_proc’:
child.c:379:15: error: expected identifier before ‘=’ token
           if (WIFSIGNALED(status) || WEXITSTATUS(status) != 255)
               ^
```

Need I install other packages?

**Comment by elieux** [comment] 2017-06-27 08:59
We are aware of this issue, it's not caused by you nor MinTTY.

The problem is that w32api (specifically `sal.h`) mangles some internal Cygwin names (in `string.h` and `wait.h`), specifically `__in` and `__out`. I've discussed this with @DavidEGrayson and Corinna and the only reasonable solution seems to be to change the internal Cygwin names to something else.

The process is currently stuck on me -- I have yet to write and send the patch. It will probably take me a day or two to find some free time for it.

**Comment by kangjianbin** [comment] 2017-06-27 09:10
Thanks a lot for your advance!

**Comment by mintty** [comment] 2017-06-28 12:13
Cannot reproduce with any gcc version, including 6.3.0.
Unless the context is further specified, please close the issue.

**Comment by kangjianbin** [comment] 2017-07-10 05:56
Hi mintty,

I can reproduce in this commit: 15a346c298a49c0a2fae3ba5428155891c8aaf78
My gcc version is:
```
[mintty]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-msys/6.3.0/lto-wrapper.exe
Target: x86_64-pc-msys
Configured with: /msys_scripts/gcc/src/gcc-6.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread model: posix
gcc version 6.3.0 (GCC)

```

**Comment by elieux** [comment] 2017-07-10 10:41
@mintty, should be reproducible with the current MSYS2 `gcc`, `msys2-w32api-headers`, `msys2-runtime-devel`.

@kangjianbin, the patch is prepared, we need to integrate it into our runtime and release a new version.

**Comment by elieux** [comment] 2017-07-10 10:42
@kangjianbin, this is the patch, you can apply it manually in the meantime: https://cygwin.com/ml/cygwin-patches/2017-q3/msg00002.html

**Comment by mintty** [comment] 2017-07-10 11:54
@kangjianbin, that commit only changes one string and can hardly be causing a compile error.
@elieux, installing freshly from https://msys2.github.io/ comes with the same gcc version I had (5.3.0) and does not expose the problem

**Comment by elieux** [comment] 2017-07-11 07:44
@mintty

> that commit only changes one string and can hardly be causing a compile error.

I don't think they meant to imply that that commit is at fault, just giving a reference point for reproducing their results.

> installing freshly from https://msys2.github.io/ comes with the same gcc version I had (5.3.0) and does not expose the problem

Run a full system update (`pacman -Syyuu` and follow instructions). If the update doesn't give you GCC v6.3.0, something's wrong.

**Comment by mintty** [comment] 2017-07-11 09:19
OK, can we change the title to something suitable? (Like Failed to compile with 6.3.0 and ...)
It works with 6.3.0 on cygwin, so I'm not yet sure what exactly makes this fail.

**Comment by elieux** [comment] 2017-07-11 10:11
I'm not sure what's the difference in Cygwin that makes it not fail, but see [my comment above](https://github.com/mintty/mintty/issues/668#issuecomment-311297260) for explanation of the failure. The commit resolving the conflict is already in Cygwin master branch, but we still need to include it in the MSYS2 runtime build and publish the new version.

**Comment by mintty** [comment] 2017-07-11 10:34
It's actually not gcc 6.3.0 either (tested by updating gcc only in my previous MSYS2 installation).

**Comment by elieux** [comment] 2017-07-11 12:26
Correct, it's the w32api.

**Comment by elieux** [comment] 2017-07-11 13:26
Here's a short program that triggers the conflict:
```
#include <w32api/sal.h>
#include <sys/wait.h>

int main() {
  WEXITSTATUS(0);
  return 0;
}
```

**Comment by elieux** [comment] 2017-07-17 06:34
`msys2-runtime` v2.8.2 contains the fix. Assuming I didn't miss anything, the ticket can be closed.

**Closed** 2017-07-17 11:31 UTC
