### ISSUE TITLE
2.7.9 introduces an input bug (enter causes paste)

### ISSUE THREAD

**Issue by deuberger** [mintty/mintty#698] opened 2017-10-17 16:46 UTC
It seems that with mintty 2.7.9, "enter" causes paste rather than just EOL. This seemed like a very unlikely bug to me, but I can't find any other explanation. I've tried replacing mintty.exe 2.7.9 in my cygwin install with both the 2.7.3 and 2.7.8 versions and the issue does not show up with either of those. It also doesn't show if I execute Cygwin.bat, which uses cmd.exe. The issue shows up with both the 32 and 64 bit versions of mintty.

**Comment by deuberger** [comment] 2017-10-17 16:52
Hmm, that's not quite right actually. If I rename the 2.7.8 version to mintty.exe (I had it called mintty8.exe) and the 2.7.9 version to mintty9.exe, then I have the reverse problem. 2.7.8 shows the problem, but 2.7.9 does not in that case. So it only shows up when the exe is named mintty.exe. I can't figure out why though. I feel like it must be a configuration issue, but I can't figure out what. It's showing up both in a plan 64 bit cygwin install and a 32 bit cygwin install (via babun). I also tried another new 64 bit cygwin install and had the same issue.

**Comment by mintty** [comment] 2017-10-17 18:47
Please provide your config file.
Do you mean the main "Return" key (right of jkl...) or the keypad-Enter key?
Please type Ctrl+V then Enter. What appears on the command line?

**Comment by deuberger** [comment] 2017-10-17 18:59
I don't have a config file. At least I don't see one in any of the locations listed at https://github.com/mintty/mintty/wiki/Tips. I haven't created one, so unless there's a default somewhere?

I was meaning the main "Return" key, but I tested and the same behavior is exhibited with the keypad-Enter key.

There is no difference when typing CTRL+V then Enter. So if highlight "foo" from somewhere (e.g. notepad) and then press CTRL-C, and then open cygwin/mintty, type CTRL+V then Enter, I get "foo" and an error from bash saying the command isn't found. The exact same behavior is exhibited without the CTRL+V.

**Comment by mintty** [comment] 2017-10-17 19:01
Please provide a screenshot.

**Comment by deuberger** [comment] 2017-10-17 19:31
Unfortunately I can't provide a screenshot due to organizational IT policies. It looks exactly like:

```
user@computer ~
$ foo
- bash: foo: command not found

user@computer ~
$
```

The above is what's shown on the last few lines of a cygwin/mintty window.

**Comment by mintty** [comment] 2017-10-17 19:36
I asked for a screenshot because I have the suspicion that you may accidentally not be running mintty.
Please right-click and check the menu, to be sure; also open the system menu (top-left frame-icon click), Options - About for the version info.
If this was really a mintty bug, many people would have reported it soon after the 2.7.9 release. Weird.

**Comment by deuberger** [comment] 2017-10-17 19:42
I wondered about that myself, so I've tried running mintty directly to be absolutely sure. So I've been doing WINDOWS+R and running `D:\cygwin64\bin\mintty.exe -`. When I open the Options window from the system menu, and click "About", it shows "mintty 2.7.9 (x896_64-pc-cygwin)".

I agree. On one hand I can't think how this could be a mintty bug considering that no one else has seen it, but I also can't find anything on my system causing it.

**Comment by deuberger** [comment] 2017-10-17 19:44
If it's a system issue though, it's strange that no one else has run into the problem and reported a fix. I tried googling a fair amount and couldn't find anything. The description "enter and paste" is ambiguous though so that could make it hard to find.

**Comment by mintty** [comment] 2017-10-17 19:51
Do you have any hotkey definitions in Windows, or a separate hotkey tool?
You could compile mintty with #define debug_messages enabled in winmain.c and check what is sent if you hit Enter.

**Comment by deuberger** [comment] 2017-10-17 20:38
I'm not aware of any hotkey definitions or a separate hotkey tool on the system. I don't see anything suspect in the list of installed programs. I'll see if I can figure out how to compile mintty and report back what I find.

**Comment by mintty** [comment] 2017-10-20 15:02
Please cross-check with 1. a different shell (/bin/dash), 2. another terminal (xterm).

**Comment by mintty** [comment] 2017-10-23 08:25
We can analyse this further if you provide diagnostics but I'm closing the issue now because there is no hint it might by any means be caused by mintty.

**Closed by mintty** 2017-10-23 08:25 UTC

**Comment by deuberger** [comment] 2017-10-23 20:46
Sorry, was busy and unable to get back to this.

I tried /bin/dash and the issue still shows up. The issue does not show up in mobyxterm or the xterm from Cygwin/X. It also doesn't show up if I run cygwin's bash via cmd.

Took me a bit to figure out how to compile mintty (didn't see the instructions in INSTALL) and then it took a while to figure out how to reproduce the problem and still get the messages. For some reason the messages don't show up when I copy mintty.exe to my existing install. Eventually I figured out that if I ran it from the compile location from within my existing install, it still exhibits the problem and prints messages. I can't copy over the log (again due to IT policy), but I did notice that 0040 IDM_COPASTE is being received in win_proc, which is strange. I also noticed that if I rename the executable (which causes the issue to go away), then that code isn't sent.

I suspect this means you're right that it's not a mintty issue, but I'm not sure whether it gives a clue as to what the issue is?

**Comment by mintty** [comment] 2017-10-23 22:11
What if you redefine IDM_COPASTE to an unused value in winids.h, e.g. 0x0300?

**Comment by mintty** [comment] 2017-10-23 22:31
Do you have any strange application running that's sending other windows messages, perhaps? Any special keyboard driver?

**Comment by deuberger** [comment] 2017-10-24 13:46
Just tried redefining IDM_COPASTE to 0x0400 (0x0300 was already defined to IDM_USERCOMMAND). The behavior went away, but I could see that the command was still being sent and printed as "IDM_?". That still goes away if I rename the binary to something else (e.g. "mintty8.exe").

I don't think I have anything running sending other windows messages, but I can try doing a clean start maybe into safe mode to try to minimize what's loaded/running.

**Comment by mintty** [comment] 2017-10-24 14:46
This sounds as if some application is maliciously sending mintty processes confusing messages...

**Comment by deuberger** [comment] 2017-10-24 16:46
Hmm, it happens even in safe mode it turns out. Not sure what would be sending it, but I'm going to do a little more digging.
