### ISSUE TITLE
Option to disable right-to-left

### ISSUE THREAD

**Issue by TxHawks** [mintty/mintty#592] opened 2016-09-20 13:48 UTC
Is there a way to disable the reordering and right-alignment of `rtl` languages like Arabic and Hebrew? It really messes up `vim` and `tmux`

**Comment by mintty** [comment] 2016-09-20 15:07
No. “It’s not a bug, it’s a feature.”
Without this feature, you should probably not try to display RTL anyway, or does vim have its own RTL approach?

**Comment by mintty** [comment] 2016-09-21 07:54
Actually, I don't even see any issue with either tmux or vim. All looks fine here for me. What do you mean by "messes up"?

**Comment by TxHawks** [comment] 2016-09-22 09:20
Thanks for the quick reply.

Of course it's a feature, and a great one. But at times, I'd like to be able to disable it.

The feature works great when there is some `rtl` text mixed inside an otherwise `ltr` paragraph, however, in `vi`, a line that either starts or ends with rtl` text in it, be indented to the right, or worse - part of the line will be indented to the right and and some to the left. When split windows are involved, it gets really difficult to handle.

Here is a screenshot, see line 2 and 3:
![image](https://cloud.githubusercontent.com/assets/5658514/18742774/aa0815b6-80be-11e6-9bbd-806f1280689b.png)

I doubt mintty can do anything to handle it better, but an option to runt mintty without the bidi feature enabled would be helpful

**Comment by mintty** [comment] 2016-09-22 14:05
In theory, I see two possibilities to handle RTL in a context-dependent way that could meet the use case:
* Support DEC margin mode and apply RTL only within current margins.
* Support the Unicode RTL direction control characters.

In both cases, however, your application would need to support the mechanism, too, to achieve the desired effect (e.g. draw each panel with respective margins set).
In my own text editor (MinEd) I had the same problem when opening a menu that overlays a bidi line. This was solved by clearing such lines before drawing the menu.

About a global option to disable bidi, I'm still hesitating whether to consider that a good idea. I acknowledge, though, that putty (from which mintty was once derived) has such an option. Maybe some more discussion or nagging is needed...

**Comment by TxHawks** [comment] 2016-09-25 13:29
Both these possibilities seem like nice additions, but as you mention yourself, they cannot guaranty a working solution.

Bidi is indeed a nice feature for a terminal emulator, but since it often ends up being more trouble than it is worth, I think it's a god idea to allow users to disable it at will. And, indeed, Putty, too, provides an option to disable. And, in my opinion, for a good reason.

**Comment by mintty** [comment] 2016-09-26 13:53
As I don't want people to accidentally misconfigure mintty with respect to its default behaviour,
I'm considering a command-line-only option, like
`--disable-bidi`
or (shorter?) 
`--nobidi`.

**Comment by TxHawks** [comment] 2016-09-26 16:11
+1 for --nobidi

**Comment by mintty** [comment] 2016-10-07 17:48
Released in 2.6.2.

**Closed by mintty** 2016-10-07 17:48 UTC

**Comment by TxHawks** [comment] 2016-10-07 18:58
Thanks!

**Comment by mintty** [comment] 2017-04-12 18:31
While implementing partial support for bidi markers, it became apparent that this is not sufficient to control absolute positioning. A switching sequence may be added.

**Comment by mintty** [comment] 2017-04-13 23:22
Released 2.7.6.

**Comment by mintty** [comment] 2017-05-19 20:35
Released 2.7.7.
