### ISSUE TITLE
Mintty as distributed with CYGWIN, v 3.1.0, has mouse issue in Application mode

### ISSUE THREAD

**Issue by mercster** [mintty/mintty#970] opened 2020-02-26 23:04 UTC
Have used mintty for years. I use irssi in a tmux session. One of my scripts is a userlist (Advance Window List) allows mouse input, to select channels, etc.

I got a new PC, installed cygwin/ssh/etc... now, mintty is not passing the mouse clicks to irssi. It is selecting text right off the bat. I see the setting Mouse -> Application Mouse Mode -> Default click target is set to "Application". I don't remember having to set any special settings with my previous install of mintty.

Mintty 3.1.0 has this issue.  KDE Terminal, RXVT, Xterm, etc do not.

**Comment by mintty** [comment] 2020-02-27 07:01
This is a duplicate of your own report #961 which appears to be finally resolved, after using the cygwin version of ssh. What's the point now?

**Comment by mintty** [comment] 2020-02-27 08:23
OK, so this report was timed before the issue was resolved in the other report. Closing.

**Closed by mintty** 2020-02-27 08:23 UTC
