### ISSUE TITLE
mintty 2.2.3 crashes on Windows 8.1

### ISSUE THREAD

**Issue by KptainBiwouak** [mintty/mintty#535] opened 2016-04-01 05:57 UTC
Hi,
As soon as mintty session has started, my PC (Windows 8.1) is crashing providing message: UNEXPECTED_KERNEL_MODE_TRAP issue.
However same configuration is working well from Windows 7.

Do I have to change Windows setup or do you have seen already this issue?

Rgds,

**Comment by mintty** [comment] 2016-04-01 13:21
Have you started mintty as Administrator?
It might also be interesting to know whether the current repository version, which has a workaround for some other mysterious problem, removes the issue.
In either case, it is extremely unlikely that mintty, as a mere user application, can actually *cause* such an error. It could happen to reveal the error, though. Googling for the message shows that it's likely a driver or even hardware problem.
Intending to close.

**Comment by KptainBiwouak** [comment] 2016-04-02 09:35
Same behavior starting mintty as Administrator. PC crashes immediatly.
Probably root cause is coming from my PC environment, but what?
I would try to test one of latest revision of mintty to check if status remains the same or not.
Nothing to report for Windows 7, it concerns ONLY windows 8.

**Comment by mintty** [comment] 2016-04-05 12:09
Closing this under the assumption it's a duplicate of #473, see also last comment there.

**Closed by mintty** 2016-04-05 12:09 UTC
