### ISSUE TITLE
Command windows remain open on Windows 10 Build 9926

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#439] opened 2015-06-04 13:05 UTC
```
Windows 10 Pro Technical Preview build 9926

cygwin               1.7.33-1
mintty               1.2-beta1-1

When launching mintty, 2 additional console windows appear visible as shown in 
screenshot attached.

Appears to be another instance of this old issue: 
https://code.google.com/p/mintty/issues/detail?id=39

Running in compatibility mode for Windows 8 fixes the issue, so I'm guessing 
the check for which OS the "Windows 7 hack" needs to be applied to simply needs 
to be updated.
```

Original issue reported on code.google.com by `cl...@clintarmstrong.net` on 24 Jan 2015 at 11:03

Attachments:
* [Screenshot (1).png](https://storage.googleapis.com/google-code-attachments/mintty/issue-439/comment-0/Screenshot (1).png)

**Comment by mintty** [comment] 2015-06-30 10:43
Hopefully fixed for next release by adding respective resource magic values.

**Comment by mintty** [comment] 2015-08-07 12:14
Any such incidents with recent versions? Otherwise I'll close the issue soon.

**Comment by mintty** [comment] 2015-09-04 12:32
I had previously overlooked the detail that the issue occurs also on ^C a in 'screen' - which is clear evidence that at least this instance of the issue is **not** related to mintty.

**Closed by mintty** 2015-09-04 12:32 UTC
Labels: Type-Defect
