### ISSUE TITLE
Windows taskbar integration broken since 2.2.1

### ISSUE THREAD

**Issue by HakanSiktas** [mintty/mintty#486] opened 2015-11-04 13:54 UTC
With the previous versions of Mintty I used a file shortcut with the following target.
`C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico /bin/zsh --login`

This worked well with Mintty <= 2.1.5 pinned to my taskbar until the recent update.
Now when I start Mintty over this pinned taskbar entry I get:

1. A blank icon
2. A new taskbar entry while the pinned item is still shown as "not running"

I can live with keeping the default Mintty icon but the new taskbar entry is unfortunate. It seems to be caused by the non-default shell I am using but I prefer to start my zsh directly with Mintty.

**Comment by mintty** [comment] 2015-11-04 16:19
I cannot reproduce 1. (the blank icon) but I guess I know the reason for 2. and will check how to sort that out.

**Comment by mintty** [comment] 2015-11-04 16:45
It's a side effect of an attempt to solve #420 issue 2. There are different pinning scenarios, pinning a shortcut or pinning a running process. Unfortunately, if grouping behaviour is optimised for one, it gets worse for the other...

**Comment by mintty** [comment] 2015-11-04 17:26
Can you test the fix attempt uploaded?

**Comment by mintty** [comment] 2015-11-04 17:27
(off-topic side-note: a commit message "attempt to fix #..." is interpreted as "fix #..." by github which automatically closes the issue - kind of over-clever...)

**Comment by HakanSiktas** [comment] 2015-11-04 18:05
Now it behaves as previously. :smiley: Even the blank icon issue does not appear anymore.
Thank you for this quick fix.

**Comment by mintty** [comment] 2015-11-05 09:16
There is interaction with #420 and #471 which I may need to tweak after this fix – which may in turn affect this fix... Let's wait until this is settled.

**Comment by elieux** [comment] 2015-11-07 14:03
For current and future reference, (unless I'm mistaken) the issue here is not that grouping stopped working, but that shortcuts pinned pre-v2.2.1 don't group with mintty-v2.2.1 windows. If a mintty-v2.2.1 window is pinned, the shortcut will group will open windows correctly. And all this applies only if an icon is specified. Without the `-i` argument, mintty-v2.2.1 should behave the same as before. Please correct me if I'm wrong.

**Comment by elieux** [comment] 2015-11-07 14:25
The blank icon issue seems to show up when multiple instances of mintty-v2.2.1 with an icon specified get grouped into one taskbar item (for example when there's not enough space on the taskbar).

![mintty-486-taskbar-pin](https://cloud.githubusercontent.com/assets/1399406/11015556/916ff2d2-8563-11e5-8c8c-ec54c6210bd6.png)

**Comment by elieux** [comment] 2015-11-07 14:30
Maybe that happens when an AppId is specified and the window icon is changed at runtime? This hypothesis needs some testing though.

**Comment by mintty** [comment] 2015-11-07 17:57
I will need to check details from your comments next week when I'll have the nerve again to think about this insane Windows magic, but this is obvious already and I've prepared a hint on it for the manual page and wiki hints page:
AppId interferes heavily with other mechanisms that affect the pinning behaviour. Depending on your use case (pinning a shortcut, pinning a running instance), different ways of gaining control are necessary. And for proper grouping of pinned shortcuts, you will even need to set a consistent AppId explicitly to the shortcut, for which no Windows GUI configuration feature exists... Don't know whether that affects the blank icon issue.

**Comment by PhilBarila** [comment] 2015-11-09 22:46
I can confirm that setting the icon with the -i switch can break the grouping and the taskbar icon.
Using the default cygwin shortcut results in the broken icon on the taskbar, multiple instances being grouped together.
C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -

Modifying a pinned shortcut to C:\cygwin64\bin\mintty.exe -i ../Cygwin-Terminal.ico - results in a dialog that the system can't find the icon:
---------------------------
mintty
---------------------------
/usr/bin/mintty: could not load icon from '../Cygwin-Terminal.ico': The system cannot find the file specified. 

---------------------------
OK   
---------------------------
After clicking OK, the mintty window opens with the broken icon on the taskbar.

Changing the / to \ results in no dialog, but still a broken icon on the taskbar.
C:\cygwin64\bin\mintty.exe -i ..\Cygwin-Terminal.ico -

Giving it an absolute path in unix format:
C:\cygwin64\bin\mintty.exe -i /cygdrive/c/cygwin64/Cygwin-Terminal.ico -
results in the same broken icon.

Giving it this command line:
C:\cygwin64\bin\mintty.exe -i C:\cygwin64\Cygwin-Terminal.ico -
results in the correct icon, but not grouped with the pinned shortcut.

Lastly, removing the -i switch entirely:
C:\cygwin64\bin\mintty.exe -
changed the the icon in the system menu from the cygwin icon to the mintty icon, but the instance grouped with the pinned shortcut.

**Comment by JayBofMA** [comment] 2015-11-10 19:06
@PhilBarila provides the working solution for this issue that I started having after a recent update of my Cygwin instance.  It seems that having the icon switch is the problem.  Yet this is a Windows shortcut, so you can define the icon, anyway, without the switch.  Thanks, Phil.

**Comment by mintty** [comment] 2015-11-11 17:12
Please retest taskbar grouping behaviour with the current git version (Download ZIP).

**Comment by PhilBarila** [comment] 2015-11-11 17:58
Works just like I expect.  If I give it the icon switch, I get the icon requested in the system menu.  If I don’t give it the icon switch, I get the default icon.  In either case, it groups on the pinned taskbar object, just as expected.

**Comment by gallagherrchris** [comment] 2015-11-13 12:31
Hi, I was having this issue as well.  With the latest checkout, this issue has been resolved for me.

**Comment by mintty** [comment] 2015-11-13 13:50
Fixed in 2.2.2.

**Closed by mintty** 2015-11-13 13:50 UTC

**Comment by mintty** [comment] 2016-02-05 18:02
Release 2.2.3: Deriving icon from desktop shortcut.

**Comment by huettenhain** [comment] 2016-06-14 11:25
I am using Version 2.3.7 on Windows 10 with the shortcut
`C:\cygwin\bin\mintty.exe -`
and have the original problem.

**Comment by mintty** [comment] 2016-06-14 12:23
There have been a range of symptoms in this context.
Please describe your problem precisely.
Also which version did you run before that did not have the problem?

**Comment by huettenhain** [comment] 2016-06-14 13:31
I am glad to help in any way possible. When I launch MinTTY from the shortcut, which is pinned to the taskbar, an "orphan" taskbar icon for the new MinTTY process appears and the original pinned shortcut sits there unchanged, displayed as not running. This is Windows 10 Pro, Version 1511, Build 10586.318. 

I have tried to modify it several times in attempts to fix it, changing the parameters - sometimes when I did that (I see no pattern), the orphan taskbar icon snaps back and the original pinned shortcut appears as running, i.e. everything looks the way it is supposed to look. However, when I close MinTTY and launch it from that modified shortcut, the same problem occurs again.

If you require any other information, let me know. 

I have had this problem for a while, also with earlier versions, and I honestly do not remember if or when it behaved differently in the past.

**Comment by elieux** [comment] 2016-06-14 14:47
I suggest you try to [reset the taskbar](http://www.tenforums.com/tutorials/3151-taskbar-pinned-apps-reset-clear-windows-10-a.html) first and test again. At least unpin mintty and make sure the relevant shortcut is gone from AppData if you don't want to zap all the other pinned shortcuts.

The feature is known to remember some stuff from previous pins.

**Comment by mintty** [comment] 2016-06-14 14:55
Thanks, elieux, for that hint. I had this behaviour myself on my previous laptop after having tested mintty taskbar integration, and couldn't get rid of it. After switching to a new laptop, same mintty binary, it behaves as it should. This whole taskbar stuff is simply utterly broken in Windows...

**Comment by huettenhain** [comment] 2016-06-14 17:00
Yes thanks a lot indeed, after a complete reset the problem is gone. I am sorry for blaming it on MinTTY, I was unaware how broken this was.
