### ISSUE TITLE
Pasting does not convert windows filename to cygwin filename

### ISSUE THREAD

**Issue by cy18** [mintty/mintty#644] opened 2017-03-18 02:30 UTC
Pasting does not convert windows filename to Cygwin filenames. 
I tried drag & drop, and it works as expected.
Did I miss anything?

**Comment by mintty** [comment] 2017-03-18 22:34
???
"It works as expected" - so what's the issue?

**Comment by cy18** [comment] 2017-03-18 23:23
I'm sorry I didn't say it clearly. Drag & drop also has the feature that converting filenames, and it works as expected. However, pasting does not convert windows filenames to Cygwin filenames.

**Comment by mintty** [comment] 2017-03-18 23:37
Unlike drag-and-drop, pasting can come from an arbitrary source, e.g. a text file. In this case conversion is not desirable.

**Comment by cy18** [comment] 2017-03-19 00:03
Do you mean pasting does not convert at all or it only convert when necessary?

According to the document https://mintty.github.io/mintty.1.html, pasting should also convert filenames when necessary. It makes me think it's a problem of my configuration. Furthermore, I don't think it's hard to judge if a string is a filename/path or normal text.

**Comment by mintty** [comment] 2017-03-19 15:43
Where do you read that in the manual page?
It's not a question of the pasted contents but of the pasting method. Pasting with mouse or a keyboard shourtcut is not drag-and-drop, it's plain text pasting. Plain text means unmodified text.

**Comment by cy18** [comment] 2017-03-19 15:49
The manual in https://mintty.github.io/mintty.1.html says 

The clipboard contents can be pasted using either the Paste menu command, the Shift+Ins or Ctrl+Shift+V keyboard shortcuts (Ctrl+V with option CtrlExchangeShift=yes), or the middle mouse button. Not only text but also files and directories can be pasted, whereby the latter are inserted as Cygwin file names. Shell quoting is added to file names that contain spaces or special characters.

**Comment by mintty** [comment] 2017-03-19 15:59
OK, that case. But it actually works; if I "copy" a path name in Windows Explorer and paste it into mintty, the path name is being converted. If that does not work for you in a specific situation, describe the issue *precisely*.

**Comment by cy18** [comment] 2017-03-19 16:09
I'm sorry for the confusion I have made. 

I have a fresh installed mintty running in Windows 10, and the convert just doesn't work. 

Though I don't think it's a problem of shell, just FYI, I have tried both fish and bash.

What I think may be a useful information is that drag&drop works as expected. I tried drag & drop and pasting the filename of a same file and the converting does not happen when paste. 

Any suggestions on debugging so I can provide more information or find the cause?

**Comment by mintty** [comment] 2017-03-19 16:19
I can only repeat: Describe the problem. *Precisely*. From where and how do you copy?

**Comment by cy18** [comment] 2017-03-19 16:27
I copy a path from the address bar of the explorer with ctrl-C, then paste it to mintty by ctrl+shift+V, the pasted contest is the origin windows path. I have also tried right click and paste from the menu. Since my keyboard does not have an insert key , the shift+insert way is not tried.

**Comment by mintty** [comment] 2017-03-19 18:47
I see, thanks. I had copied from the panel of Explorer in which case it works.
The issue is probably that when copied from the address bar, the clipboard type is set to text while the other copy sets the clipboard type to some special object mode. I'll check that but if it's confirmed, it means the clipboard contents cannot be distinguished from "normal" text (like copied from some text file) and there will be nothing that mintty can do about it.

**Comment by cy18** [comment] 2017-03-20 05:29
I have tried to read the source of mintty and found nothing related to converting filenames when pasting. I also have made a very dirty patch to try to fix this.

https://github.com/cy18/mintty/commit/92e3401e6b9bb7b16aca9f4ea19b8912ee703289

I found the file name is converted by the function path_win_w_to_posix, and the pasting starts in winclip.c line 716

    win_paste(void)
    {
      if (!OpenClipboard(null))
        return;
      HGLOBAL data;
      term.selected = false;
      if ((data = GetClipboardData(CF_HDROP)))
        paste_hdrop(data); //the function path_win_w_to_posix is called
      else if ((data = GetClipboardData(CF_UNICODETEXT)))
        paste_unicode_text(data); // the function path_win_w_to_posix is not called
      else if ((data = GetClipboardData(CF_TEXT)))
        paste_text(data); // // the function path_win_w_to_posix is not called
      CloseClipboard();
    }

Is there another function to convert the filename? Or I missed something else?

**Comment by mintty** [comment] 2017-03-20 06:48
Thanks for willing to support; Windows-specific clipboard code would go into winclip.c where all those includes are already given.
Anyway, with your patch, try to copy the following sentence from a text file, e.g. opened in notepad:
`Windows path C:\cygwin\home is converted to /home.`
And you see what I mean when referring to the clipboard mode. The conversion is not acceptable in this case.

**Comment by cy18** [comment] 2017-03-20 06:58
Well, this is one of the advantages of opensource. When I found some problem, I can try to fix it by myself.

Do you mean the conversion should not happen for files under cygwin installation directory? Why this is not acceptable? BTW, I found the problem you mentioned also happens in drag&drop.

**Comment by mintty** [comment] 2017-03-20 07:43
Change the example to
`C:\cygwin\home is converted to /home.`
Your patch only converts if the text begins with a Windows path. But yet this context-dependent conversion is unexpected and violates the design principle of least astonishment.

**Comment by cy18** [comment] 2017-03-20 08:03
Finally I think I get your idea. Do you mean copy a file in **Explorer panel** will lead to a converting, but copy the **filename** from the **address bar** of Explorer **as text** won't do the convert?

I read the document again and I found I have misunderstood the feature.

Any way, I feel converting the filename is useful, maybe we can add this feature with an new option, which is turned off by default?

**Comment by mintty** [comment] 2017-03-20 17:58
The paste operation lands in function win_paste (winclip.c). Tracing it reveals that a dedicated file name is copied and pasted as CF_HDROP, while text is handled as CF_UNICODETEXT.
Copy/paste from any plain text will also appear as CF_UNICODETEXT, so that's not distinguishable, and I hope you understand my argument that plain text should not be converted.
Note, however, that while marking the Explorer address bar, then copying with Ctrl+C, will yield CF_UNICODETEXT, you can also right+mouse-click in the address bar and select the Copy address item;
in this case you'll get a CF_HDROP which is then converted.
This should be sufficient to achieve what you want.
Converting within CF_UNICODETEXT is really not an option, so I'm closing the issue.

**Closed by mintty** 2017-03-20 17:58 UTC
