### ISSUE TITLE
Textmode console only for mintty.exe 

### ISSUE THREAD

**Issue by lars18th** [mintty/mintty#822] opened 2018-11-21 12:56 UTC
Hi,

Some tools use the `mintty.exe` to launch external tools from the Cygwin environment (or MSYS, WSL, etc.). Typically these tools are a Shell (bash) plus a script. And in fact these tools doesn't use any graphical output, just textmode. However, if we like to launch these tools from a SSH session, in this case all fails, as the `mintty.exe` can't open the graphical window.

My suggestion is then to include some command line parameter to work only in textmode. That's to not open a new window and use only the console support.

What you think?

**Comment by mintty** [comment] 2018-11-21 13:07
This is something that should be added case-by-case for each such remote invocation as they are specific for their use cases anyway. If a remote scripts wants to open a new window, this would be an X window. Whether that's possible can be determined by the existence of a DISPLAY environment variable. The point is therefore to carefully craft your profile scripts for the remote case to not set this variable, so you'll even have a generic indication.
On the other hand, if you have a local X server running, you can tunnel its access through ssh, so the remote script can also start a new window.

**Comment by lars18th** [comment] 2018-11-22 08:19
Hi,

I feel like I'm not explaining it well, or you don't understand the problem.

>> these tools doesn't use any graphical output

No graphical environment is needed!

>> if we like to launch these tools from a SSH session, in this case all fails, as the mintty.exe can't open the graphical window.

Please, try to open one SSH to your Windows machine. And from this session call to `mintty.exe`.
What happens?

> On the other hand, if you have a local X server running, you can tunnel its access through ssh, so the remote script can also start a new window.

I know it! This isn't the problem!

> This is something that should be added case-by-case for each such remote invocation as they are specific for their use cases anyway.

No. It's a **generic** issue. When you call to `mintty.exe` you assume that you're insde a Windows session with a GUI activated. However, this isn't true when connecting through a CONSOLE session. And almost _two_ different console connection exists in Windows: with SSH server and RDP in Console Mode (mstsc /console).

So, my request/suggestion is to add support for a "console only mode".
After all the `mintty.exe` is a Terminal tool for text console programs. Right?

Please, reconsider it.
Regards.

**Comment by mintty** [comment] 2018-11-22 08:37
Oh, it's the other way round...
Mintty is in fact a GUI window, I don't think it's possible to run it "as a console".
But it is possible to start it from a remote login. If that's blocked for you, it's due to Windows security configuration. There have been some comments about this on the cygwin mailing list, please try to search that (cygwin.com/ml/cygwin). It's not specific to mintty.

**Comment by mintty** [comment] 2018-11-22 08:50
To start it from ssh login, you should actually be logged in at the desktop too, already.
If you're not, you'd need to login with admin rights at least, if it works at all.

**Comment by lars18th** [comment] 2018-11-22 09:32
> To start it from ssh login, you should actually be logged in at the desktop too, already.
If you're not, you'd need to login with admin rights at least, if it works at all.

It depends on the method used to access. For example, with OpenSSH for Windows 10 this isn't required.

> There have been some comments about this on the cygwin mailing list, please try to search that (cygwin.com/ml/cygwin). It's not specific to mintty.

OK. I'll search for it. And I'll write about the results.
So, please, can you reopen the issue and mark it as "enhancement"? We can work to improve it.

Regards.

**Comment by mintty** [comment] 2018-11-22 11:45
Reopening to receive your findings on the solution.
However, as I expect a solution to be based on Windows configuration, and I do not expect a solution to be feasible from mintty, this is likely not an enhancement.

**Comment by avih** [comment] 2018-11-22 11:59
To be honest, the use case is still entirely not clear to me. Does the OP want to ssh into windows/cygwin and then run mintty through the ssh connection?

**Comment by mintty** [comment] 2018-11-22 12:47
After clarification, I understand that's roughly the case, except that mintty is not run *through* ssh but only started through ssh and should then be run remotely (from the original user point of view), or locally (from the ssh target point of view) on the desktop of the machine to which the user logged in.

And this works fine, as long as the same user is already logged in to the desktop. So actually, I'm not sure again myself what the problem is.

**Comment by lars18th** [comment] 2018-11-22 13:09
Thank you to reopen it! :wink: 

> Does the OP want to ssh into windows/cygwin and then run mintty through the ssh connection?

Yes, and no.

Yes, because I like to start `mintty.exe` in a CONSOLE session.
No, becuase I don't like to "tunnel" the GUI over the connection (so _no_ logged in the Windows machine).

Please, do **this** simple test:
1. Install _native_ OpenSSH in a Windows 10 machine.
2. From _another_ machine (Linux or Windows) open one SSH session to the previous machine.
3. From this SSH shell (CMD.EXE) call to `mintty.exe /usr/bin/bash --login`.
4. What's the result?

For sure, you can request: Why not call directly to "bash"? Because the `mintty.exe` can handle a variety of command line parameters: WSL integration, logging, etc.

The objective is to have a TTY only version of MinTTY.
I hope now it's more clear.

**Comment by avih** [comment] 2018-11-22 13:15
So basically you want to ssh into WSL from a remote machine?

Please describe your use case (or cases) exactly, what you expect/want to happen, and what happens instead. Not with sentences like "mintty can do this and that and it's great".

**Comment by mintty** [comment] 2018-11-22 13:37
As said before, if you log into some console-like remote environment, mintty cannot run *inside* that thing because most of the Windows API it uses to implement its features depends on the mintty window being a Windows window.
Spawning a mintty window from that command-line login is possible, but the same user used for ssh login needs to be the current owner of the desktop. This is a quite obvious security limitation, no serious operating system will allow anything else, except you'd be running as root. (This kind of thing used to be possible in earlier versions of Windows, reportedly.)
The same limitations would apply with any other terminal or whatever window application. Closing again.

**Closed by mintty** 2018-11-22 13:37 UTC
Labels: question

**Comment by lars18th** [comment] 2018-11-22 14:40
> So basically you want to ssh into WSL from a remote machine?

No. WSL is not the only console shell that you can use over SSH. Think on: cygwin-bash, CMD, PowerShell, etc. Therefore, the objective is to execute _any_ cygwin console tool over a SSH **inside** a MinTTY process.

> Spawning a mintty window from that command-line login is possible

Yes. It's true, but this isn't the objective.

>  mintty cannot run inside that thing because most of the Windows API it uses to implement its features depends on the mintty window being a Windows window.

Ah! OK. So the problem is that the MinTTY **requires** the "GUI winAPI" and can't work with the "console winAPI". Then correct. Yet thank you very much.
