### ISSUE TITLE
I18N (Request for gettext-ifing mintty)

### ISSUE THREAD

**Issue by Gozer-404** [mintty/mintty#537] opened 2016-04-01 12:52 UTC
Hi,
is there any wish to have an i18n process on mintty ?
I had a quick look at the code and everything is english hard coded. 
It might be a good idea to prepare for being able to translate the buttons/dialogs:
- the easiest method is with gettext, but can it be added easily to mintty which is kinda windows oriented?
- use the old windows method with different rc files and a dll for each. Might be more tricky.

BTW I'm available for doing a french translation :-)

**Comment by mintty** [comment] 2016-04-01 13:02
This is actually a duplicate of issue #1, but I'm leaving it open for now for discussion.
I'm not in favour of a Windows method involving additional dll files.
Is there any other terminal program (e.g. on Linux) that supports this, to compare with?
In any case, priority for this is lower than for a number of other issues...

**Comment by Gozer-404** [comment] 2016-04-01 14:58
Sorry for the duplication...

I actually already played with some changes and gettext seems to be usable. I'll try to continue as much as possible and show you the result. A quick look at the dll change involved:

> $ ldd /usr/bin/mintty.exe
>         ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x777e0000)
>         kernel32.dll => /cygdrive/c/Windows/system32/kernel32.dll (0x775c0000)
>         KERNELBASE.dll => /cygdrive/c/Windows/system32/KERNELBASE.dll (0x7fefd7f0000)
>         cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
>         COMCTL32.dll => /cygdrive/c/Windows/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18807_none_fa381d5f175bfb52/COMCTL32.dll (0x7fefbfb0000)
>         msvcrt.dll => /cygdrive/c/Windows/system32/msvcrt.dll (0x7fefedb0000)
>         GDI32.dll => /cygdrive/c/Windows/system32/GDI32.dll (0x7feff4f0000)
>         USER32.dll => /cygdrive/c/Windows/system32/USER32.dll (0x776e0000)
>         LPK.dll => /cygdrive/c/Windows/system32/LPK.dll (0x7feff740000)
>         USP10.dll => /cygdrive/c/Windows/system32/USP10.dll (0x7fefece0000)
>         SHLWAPI.dll => /cygdrive/c/Windows/system32/SHLWAPI.dll (0x7fefee50000)
>         comdlg32.dll => /cygdrive/c/Windows/system32/comdlg32.dll (0x7feffa20000)
>         SHELL32.dll => /cygdrive/c/Windows/system32/SHELL32.dll (0x7fefdf50000)
>         IMM32.dll => /cygdrive/c/Windows/system32/IMM32.dll (0x7feffac0000)
>         MSCTF.dll => /cygdrive/c/Windows/system32/MSCTF.dll (0x7feff750000)
>         ole32.dll => /cygdrive/c/Windows/system32/ole32.dll (0x7fefdca0000)
>         RPCRT4.dll => /cygdrive/c/Windows/system32/RPCRT4.dll (0x7fefef00000)
>         WINMM.dll => /cygdrive/c/Windows/system32/WINMM.dll (0x7fefbcf0000)
>         WINSPOOL.DRV => /cygdrive/c/Windows/system32/WINSPOOL.DRV (0x7fef82c0000)
> 
> $ ldd ./mintty.exe
>         ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x777e0000)
>         kernel32.dll => /cygdrive/c/Windows/system32/kernel32.dll (0x775c0000)
>         KERNELBASE.dll => /cygdrive/c/Windows/system32/KERNELBASE.dll (0x7fefd7f0000)
>         cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
>         cygintl-8.dll => /usr/bin/cygintl-8.dll (0x3e2670000)
>         cygiconv-2.dll => /usr/bin/cygiconv-2.dll (0x3e6120000)
>         COMCTL32.dll => /cygdrive/c/Windows/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18807_none_fa381d5f175bfb52/COMCTL32.dll (0x7fefbfb0000)
>         msvcrt.dll => /cygdrive/c/Windows/system32/msvcrt.dll (0x7fefedb0000)
>         GDI32.dll => /cygdrive/c/Windows/system32/GDI32.dll (0x7feff4f0000)
>         USER32.dll => /cygdrive/c/Windows/system32/USER32.dll (0x776e0000)
>         LPK.dll => /cygdrive/c/Windows/system32/LPK.dll (0x7feff740000)
>         USP10.dll => /cygdrive/c/Windows/system32/USP10.dll (0x7fefece0000)
>         SHLWAPI.dll => /cygdrive/c/Windows/system32/SHLWAPI.dll (0x7fefee50000)
>         comdlg32.dll => /cygdrive/c/Windows/system32/comdlg32.dll (0x7feffa20000)
>         SHELL32.dll => /cygdrive/c/Windows/system32/SHELL32.dll (0x7fefdf50000)
>         IMM32.dll => /cygdrive/c/Windows/system32/IMM32.dll (0x7feffac0000)
>         MSCTF.dll => /cygdrive/c/Windows/system32/MSCTF.dll (0x7feff750000)
>         ole32.dll => /cygdrive/c/Windows/system32/ole32.dll (0x7fefdca0000)
>         RPCRT4.dll => /cygdrive/c/Windows/system32/RPCRT4.dll (0x7fefef00000)
>         WINMM.dll => /cygdrive/c/Windows/system32/WINMM.dll (0x7fefbcf0000)
>         WINSPOOL.DRV => /cygdrive/c/Windows/system32/WINSPOOL.DRV (0x7fef82c0000)

I'll have to recheck but I think rxvt on cygwin had some i18n (....). On linux, I'm sure that konsole  [http://blog.roozeec.fr/2005/06/17/konsole-le-terminal-de-kde/](url) or gnome-terminal [https://upload.wikimedia.org/wikipedia/commons/8/84/Gnome-terminal-2.8.2-screenshot-ja.png](url) have translated menus and dialogs.

**Comment by mintty** [comment] 2016-11-11 13:59
I guess the localization transformation is now done.
While some of the effort went into transformation of individual messages to be better translatable,
most of the effort went into enabling Unicode for all message paths (Options dialog, menus, invocation and inline messages).

Please review the solution and you are welcome to provide an initial French translation.
What is missing is a howto for later changes. What is the recommended workflow if during further development message are deleted, added, or even modified?

**Comment by mintty** [comment] 2016-11-11 14:05
Note that the treeview labels in the left panel of the Options dialog ("Looks", "Text", ...) are currently not translatable. This is due to technical issues with Windows; all attempts to enable Unicode for these labels failed (see the comments within `#ifdef Unicode_TreeView` in source file windialog.c).

**Comment by mintty** [comment] 2016-11-12 11:17
Added localization support in 2.7.0.

Please contribute localization files, whoever is interested.

**Closed by mintty** 2016-11-12 11:17 UTC
Labels: duplicate, enhancement, Priority-Low

**Comment by mintty** [comment] 2016-12-04 21:54
Release 2.7.1: Tweaked and polished localization support.

**Comment by mintty** [comment] 2016-12-10 02:05
Release 2.7.2: Supposedly finalised localization support.
Further translation files are welcome.

**Comment by Gozer-404** [comment] 2017-02-02 12:45
_Sorry I've lost the last email_, here is a patch 
[mintty_fr_po.patch.txt](https://github.com/mintty/mintty/files/747714/mintty_fr_po.patch.txt)
based on git clone from yesterday of the **fr.po** file.

**Comment by mintty** [comment] 2017-02-02 13:29
Thanks;
you don't like my enhanced font sample?
How about "AaBbŒœYyZz", to include some specific French letters at least?
