### ISSUE TITLE
Can't set a background image

### ISSUE THREAD

**Issue by Bilge** [mintty/mintty#666] opened 2017-06-20 20:39 UTC
😞

**Comment by mintty** [comment] 2017-06-21 05:53
Your are welcome to propose an implementation.

**Comment by Bilge** [comment] 2017-06-21 18:20
& u

**Comment by mintty** [comment] 2017-06-28 09:44
Actually, this is a duplicate of #18, so I'm closing it.

**Closed by mintty** 2017-06-28 09:44 UTC

**Comment by thorstenkampe** [comment] 2018-04-07 07:52
I propose an implementation based on the [background image functionality](http://www.9bis.net/kitty/?page=covidimus&zone=en) in `KiTTY`. `KiTTY` is a well known PuTTY enhancement. Since to my knowledge `mintty` was heavily based on terminal code from PuTTY in the beginning, it may be possible to incorporate that `KiTTY` patch into `mintty`.

The problem with that particular implementation seems to be the inability to display Hindi, Korean, Chinese, and Japanese characters. Greek, Cyrillic, and Vietnamese seem to be fine. Arabic better than in `mintty`.

**Comment by mintty** [comment] 2018-07-01 22:50
Released 2.9.0.

**Comment by mintty** [comment] 2018-09-20 11:56
Released 2.9.1. Image prefix '%' scales window to image aspect ratio.

**Comment by mintty** [comment] 2018-11-10 18:12
Released 2.9.4 with option `Background==`.
