### ISSUE TITLE
Copy on Select option causes SPACE DEL to be output every 5 seconds

### ISSUE THREAD

**Issue by eric-marshall** [mintty/mintty#608] opened 2016-11-17 19:49 UTC
I'm currently using mintty v2.5.0.

I think because of a change to my corporate Windows account profile, mintty just
started behaving differently. I've been able to trace it down to the "Copy on Select"
option. If the option is enabled (the default), mintty will emit the two characters
SPACE DEL every 5 seconds when a running program has caused the terminal to
enter raw mode, e.g., more. If I more a long file, the first page of the file is displayed
as expected, and then every 5 seconds automagically scrolls to the next page. This
continues ad infinitum. If I disable the "Copy on Select" option, the above aforementioned
SPACE DEL problem disappears, but the Enter key then emits the three characters
SPACE DEL CR, rather than the expected single CR character.

Any ideas?

Thanks in advance.

**Comment by mintty** [comment] 2016-11-18 15:20
Cannot reproduce. `PAGER=more man ls` is stable here.
Please analyse your environment for anything weird.

**Comment by eric-marshall** [comment] 2016-11-18 15:27
Any suggestions on what to look at?

I have the same version of mintty installed on another computer which does *not*
behave this way. I've looked at $TERM and stty -a output, and both are the same.

**Comment by mintty** [comment] 2016-11-18 20:33
> I have the same version of mintty installed on another computer which does not behave this way.

Which more or less indicates that this is *not* a mintty issue. Therefore I'll probably just close it soon.
I cannot remotely analyse your system, if you don't even provide a reproducible test case.

**Comment by mintty** [comment] 2016-11-22 16:01
Also, does it happen with any other terminal (xterm)?

**Closed by mintty** 2016-11-22 16:01 UTC
