### ISSUE TITLE
PS1 Prompt doesn't refresh when a new prompt is displayed

### ISSUE THREAD

**Issue by Saurutobi** [mintty/mintty#521] opened 2016-03-01 23:28 UTC
I have my .bashrc configured to display a bunch of information in the prompt. Here are the last few lines in my .bashrc:
```
Grey="\[\e[1;30m\]"
Purple="\[\e[0;35m\]"
Cyan="\[\e[0;36m\]"
LightGreen="\[\e[1;32m\]"
LightRed="\[\e[1;31m\]"
Default="\[\e[0m\]"

#only works on first load
PS1="$LightRed+-[$Purple\h$LightGreen $(get_branch_name) $Cyan\w$LightRed]\n$LightRed+->$Default "
```
The problem here is this only works the first time the shell is run. I have to manually run PS1="blablabla" each time I want the prompt updated.
This started happening when I upgraded from Github For Windows's older version to the new one that includes Mintty(latest version).

I found a StackOverflow article from 2011, well before this even started happening.
http://stackoverflow.com/questions/5379986/why-doesnt-my-bash-prompt-update

**Comment by mintty** [comment] 2016-03-02 09:26
The issue is hardly reproducible from the sparse description. What does "first load" mean? .bashrc? How does it not work later? What version of mintty? Which other environment does it work in?
Anyway, prompt display problems are most unlikely related to the terminal. Also, please test with another terminal to compare.
Closing; if you think you can demonstrate how this is related to mintty, feel free to respond or reopen.

**Closed by mintty** 2016-03-02 09:26 UTC

**Comment by mintty** [comment] 2019-01-01 09:14
Possibly missing `export PS1`. Yet not related to mintty.
