### ISSUE TITLE
Request for option to fold pasted text into one line

### ISSUE THREAD

**Issue by Zexaron** [mintty/mintty#768] opened 2018-05-05 00:17 UTC
Hello

Git windows version uses mintty for it's bash shell, not sure how it's on other OS. 

Seems like either windows or whoever adds a newline or line-ending to the end of copied stuff from other applications like browsers, or some kind of rich-text character.

The Bash shell interprets that as a freaking RETURN and executes the line, the worst possible thing, makes it dangerous when not finishing a sentence in git and possibly doing something wrong or even a irreversible action.

There should be an option to PASTE AS PLAIN TEXT and FORCE IGNORE ANY NEW LINES and SPECIAL CHARS at the end.

I'm also in favor of https://github.com/mintty/mintty/issues/645 since git uses mitty on windows, then why mintty shouldn't recognize that.

EDIT: This has been going on for more than a  year now for me, I had to get to the bottom of it, all the clues lead me here.

EDIT: The basic "copy paste" of a github clone link has this problem. I'd say that's a pretty good enough reason this should be regarded as urgent!

EDIT3: Sometimes the bash goes crazy and spams hundreds of loops if the characters in the pasted string are resembling that of an URL, so it'll go for like several pages trying to execute a hundred versions of the pasted text.

**Comment by Biswa96** [comment] 2018-05-05 06:31
Git-for-Windows has some conflict with end-of-line. Use git in cygwin. I personally see those problems.

**Comment by mintty** [comment] 2018-05-05 06:36
About issue 645, please go to that issue and make a design proposal that handles the inconsistency issues discussed there and in related issues, as I requested there before.

**Comment by Zexaron** [comment] 2018-05-05 10:10
Okay, ofcourse, I wrote that late at night yesterday, I'm re-explaining it in a better mood right here:

No it's not mintty fault, I may have not been clear enough.

Now I have trouble recreating it at this moment, the same "copy github clone link" now doesn't produce the problem anymore, I did do some closing and reopening of the bash it self tho, I didn't even reboot the machine, I'm on Win10 in this case, but it's been same on Win7.

Seriously this is ridicolous, It's not a false report, I'll reboot and keep trying until I get it to recreate, I wasn't making things up! This could be some kind of a windows or browser, in this case it was opera, the PC was left completely idle and for some reason the effect is gone right now.

I was able to force it by copying a line with CRLF, CR, and LF and all of the cases produced the effect, something must be messing with the copying from other applications.

The thing is, that when I paste the same text to Notepad++ or Programmer's Notepad it would never have a visible new line but it would still produce the RETURN effect in Bash.

I'll keep an eye on this as time goes, ofcourse I'll keep, since I'm switching between multiple OSes by switching storage disks (not a fan of dual boot) so I'll boot into Win10 fresh once again and try it again then.

So yesterday, pretty much any kind of text I would copy would have the RETURN effect in Bash, I would copy article text from opera, or the git clone link by pressing CTRL+C and not clicking the COPY TO CLIPBOARD button on the page, same results, overnight, the thing is mysteriously gone.

**Comment by mintty** [comment] 2018-05-05 10:43
If you paste multiple lines, you can obviously not ignore line ends.
The only conceivable workaround would be to ignore a final line end but that's kind of very unexpected information stripping for most people. Better apply some care when pasting, especially into a shell. Such an intrusive workaround would certainly not be the default.
Having said that, before we can consider an optional workaround, a reproducible demonstration of the problem is needed. Maybe we should close the issue meanwhile?

**Comment by Zexaron** [comment] 2018-05-05 12:08
I'll get back when I find more info today asap.

**Comment by Zexaron** [comment] 2018-05-06 01:40
Unfortunately I just can't recreate the original bug at this time, the freak effect that would RETURN on any copied text. It could be some other application messing with things, I tried opening firefox and VS2017 (which seems to lock the hosts file) but it didn't work. The original freak effect happened when I rebooted fresh just after installing git and VS2017.

However, that doesn't mean it's not okay when line endings really are present, that is perfectly recreatable, it doesn't matter which flavor (Win, Linux, Mac) it is, all of them do it.

The workaround should still be valid imo. Here's a demo webm video but 24hr lifetime -
 should be up most of sunday https://a.uguu.se/wR1YzTK3KiRe_GitBashLineEndingReturn

Indeed I am perfectly okay with such a workaround not being the default behavior, the workaround to ignore line endings might fix the freak-effect too.

**Comment by mintty** [comment] 2018-05-06 05:36
The first action seen in the video is: you copy 7 lines, then you paste 7 lines. The behaviour is absolutely normal; I have no idea what you are objecting to. If you stripped the final CRLF, you would still be pasting 6 full lines with CRLF into the shell. The freak effect is that you are pasting useless input into a shell.

**Comment by Zexaron** [comment] 2018-05-06 11:05
Oh, I meant stripping ALL the newline characters completely, not just at the end, if those are a problem too, I don't need to paste any lines, ofcourse this wasn't a normal use case, it was a demo, I was doing that to show it where CRLF is perfectly seen, previously when the shell was acting weird or the copy-paste function was borked it was doing that on any piece of code, you can see in the video copying without CRLF worked fine, until CRLF was present, I already tested with CR and with LF and all of them produce the same thing, but it's not in this video, so it's not OS-specific.

The behavior is unwelcome as normal it may have been in history for various shells, it's quite a stupid behavior IMO, but as I said I don't mind it being default, while still having an option to **forcefully** remove all line endings and never recognize them, it's ALWAYS a mistake and it's never intended by me and probably other people too, so why respect newline chars at all. If that's not a valid point I don't know what is.

**Comment by Zexaron** [comment] 2018-05-06 12:15
I find it bizzare it's considered normal behavior, just look at what it does, it doesn't support multi-line, so why treat it as normal. 

If that could be a workaround, it's not the most optimal one, but at least exposing it in the GUI could be nice, otherwise I'd never knew about it.

**Comment by mintty** [comment] 2018-05-06 12:45
Pasting is effectively like entering the respective text from the keyboard. If you type something and then Enter, you expect the shell to interpret a command, so why it should it be different after pasting? You may like to try a few other terminals to see the behaviour is definitely normal. It's the same in the Windows command console, by the way.
I wasn't aware of the configuration option suggested by avih; it's a shell configuration, though (or more precisely, a readline feature), not a mintty option.

**Comment by Zexaron** [comment] 2018-05-06 13:34
So mintty isn't THE shell, ah. 

This behavior could be a leftover from 1990ies from MS-DOS or something, I'm not against traditions, but this is a pretty weird one.

**Comment by mintty** [comment] 2018-05-06 13:58
It is weird to expect that a terminal should magically detect your mistakes and prevent you from them.

**Comment by Zexaron** [comment] 2018-05-06 18:04
Yes, that's why it would be considered as an extra bonus low-priority feature.

**Comment by mintty** [comment] 2018-05-06 18:10
I do not generally object to provide workarounds, or safeguards, for certain issue.
But you'd need to describe precisely what the feature should be like, and, considering this is a non-standard thing, perhaps collect a few supporters on the issue.

**Comment by Zexaron** [comment] 2018-05-06 18:26
Sounds good.

**Comment by Zexaron** [comment] 2018-05-14 13:19
I was busy but I kept an eye on this, I tested the bracketed mode and surprisingly it's close to what I wanted, it doesn't execute on the line endings immediately. In my cases I was having single lines with a line end character without anything afterwards , that's what the elusive BUG was probably about, I didn't actually copy multi-line text, I copied a single line and it  was executing after pasting that and I couldn't figure out why on earth would it do that for a single line. Several days passed and I haven't seen that behavior yet.

Bracketed mode is nice, but not quite, because the goal is not multi-line support, the goal is to just paste a single line because I'm building a command right there in the bash, I keep pasting a few tens of characters at a time, several times, pieceing the full command together, and it shouldn't be executing by the time I didn't complete it.

So what I had in mind is a pretty strong bug very effective option, ofcourse non default as we speak, if it would be up to me, is to just ignore everything else except the first line, so when I would paste multi-line or a single line with line endings, as soon as the first instance of either CR, LF, or CRLF is detected, it would not only ignore that line ending, but all the text after it, everything, If I pasted 1000 lines, only first line will make it to the bash, without any line endings, so it would not execute, and it wouldn't need bracketed mode, it would be a standalone option.

Unfortunately the title of this issue would have to be edited again - if this is accepted, I know it sounds shocking, but it's exactly what would fix such a thing completely, forever.

**Comment by BrianInglis** [comment] 2018-05-14 15:29
If you have problems dealing with multiline pastes, start a shell command line with 'echo "', then paste, so you can edit the pasted content. 
Multi-line paste is too useful to disable its normal operation. 
However an alternative could be a Paste Special context menu selection with alternatives, as in LO/OO calc/spreadsheet products, offering options such as strip newlines, convert to spaces or semicolons.

**Comment by Zexaron** [comment] 2018-05-14 15:39
Oh, I guess this option wouldn't be able to be enabled while bracketed mode is enabled, and vice versa, should solve that, no.

**Comment by mintty** [comment] 2018-05-14 18:02
I still think the use case is a bit obscure; why would you select 1000 lines in the first place if you want to copy only one?

**Comment by Zexaron** [comment] 2018-05-14 20:19
It probably would never happen unless it's really a misclick and being distracted by something, it would just work in any case, if it's just the most tricky one line ending without any text afterward, or a few lines.

**Comment by avih** [comment] 2018-05-14 20:48
It's not the role of the terminal to edit pasted text on the fly or decide where it's required (shell prompt where you mis-copied more than you wanted to) or not required (text editor where you don't want to trim the pasted text).

Just be careful when you paste text into a shell - which is a good practice regardless, and configure your shell to support bracketed paste.

It's really that simple.

**Comment by mintty** [comment] 2018-05-14 21:04
Bracketed paste wouldn't really help with his issue, unless it were changed to bracket per line.
@Zexaron, have you tried the DropCommands option as suggested? However, it only affects drag pasting. Maybe an additional option could do the same for all pasting, so you would have all flexibility to adjust your own pasting policy.

**Comment by Zexaron** [comment] 2018-05-23 03:21
Wasn't able yet. But I can. 
If you want to go that far, you could possibly have a few choices, for my idea, like "ignore all text after this character" -LF -LF -STX .etc with a checkbutton to "include the character that triggeres this" or something worded like that, if that's what "own pasting policy" could also stand for.

Since you mentioned all pasting, like having a section on pasting with multiple options, I suppose, but I don't know if it's mintty's scope to edit lint config files, right? Some of these options should be kept separate and not active simultaneously, to avoid weird behavior which might be unwelcome to others.

**Comment by mintty** [comment] 2018-06-22 19:34
I've made a proposal for criteria to suppress multi-line pasting in https://github.com/mintty/mintty/issues/777#issuecomment-399557977, maybe this is acceptable?
Another idea would be to detect whether the current foreground process is a shell.

**Comment by BrianInglis** [comment] 2018-06-22 20:46
While the current process may be a shell, I often paste multi-lines after ```$ echo '``` or ```$ command <<< '```

**Comment by mintty** [comment] 2018-07-11 17:44
xterm 333 introduces option disallowedPasteControls to a similar aim; this may make it appropriate to do something about it

**Comment by mintty** [comment] 2018-09-08 18:04
Taking the aforementioned xterm option as a model, I've implemented option `FilterPasteControls`.
(Note also to @jsneerin from the chat issue.)

**Comment by mintty** [comment] 2018-09-20 11:49
Released 2.9.1.

**Closed by mintty** 2018-09-20 11:49 UTC

**Comment by Zexaron** [comment] 2018-09-29 21:07
Sorry, wasn't able to follow and respond further, I was quite busy. I appreciate the fact that this was taken care of and I'll try it out when I get a chance or when this gets into Git For Windows, unfortunately the latest release happened just a while ago.
