### ISSUE TITLE
Missing glyphs

### ISSUE THREAD

**Issue by Perlence** [mintty/mintty#605] opened 2016-10-22 20:17 UTC
I feel kind of bad for creating two issues revolving around same particular font (Iosevka) 😄 

So, I've got tofu when trying to print 'warning sign' `\u26a0`. This time, top window is mintty, bottom is st:

![Missing glyph](https://cloud.githubusercontent.com/assets/1044300/19622219/788261ca-98ad-11e6-94fc-64af7cced023.png)

**Comment by mintty** [comment] 2016-10-23 07:00
> I feel kind of bad for creating two issues revolving around same particular font (Iosevka)

No problem with that; however, this is a duplicate of #573.
If you can help out with why and how font fallback works in st but not in mintty, that would be great.

**Comment by Perlence** [comment] 2016-10-23 19:18
I think, fontconfig is responsible for font fallback, because st is an X11 application http://git.suckless.org/st/tree/st.c#n3711

**Comment by mintty** [comment] 2016-10-23 21:22
It would be good to identify the font fallback procedure in fontconfig, or maybe X11, on Windows, so it could be reused for mintty.
Or maybe there is a library already that could be used for this purpose?

**Comment by arcanis** [comment] 2016-11-05 13:04
I have zero experience in developing on Windows, but after searching for some time I've found [the following thread](https://groups.google.com/forum/#!topic/scintilla-interest/F_5tqDtFP_M) which might be useful. I copy here the most interesting part, a `ExtTextOutW` wrapper which apparently solve this issue:

```
#include <Usp10.h> 
#pragma comment(lib,"Usp10.lib") 
bool TextOutUniscribe(HDC hdc, int x, int y, UINT fuOptions, RECT *prc, LPCWSTR psz, int cch) 
{ 
    if (cch == 0) return true; 
    SCRIPT_STRING_ANALYSIS ssa; 
    HRESULT hr = ScriptStringAnalyse (hdc, psz, cch, 0, -1,SSA_FALLBACK | SSA_GLYPHS, MAXLONG,NULL, NULL, NULL, NULL, NULL, &ssa); 
    if (SUCCEEDED(hr)) { 
        hr = ScriptStringOut(ssa, x, y, fuOptions, prc, 0, 0, FALSE); 
        ScriptStringFree(&ssa); 
    } 
    return SUCCEEDED(hr); 
} 
```

**Comment by mintty** [comment] 2016-11-05 22:23
Thanks a lot for digging this out. It works indeed for missing characters. For others (like Arabic) it seems to break proper display, however.
Also there is still a positioning inconsistency, as also mentioned in your references, along with an idea to fix it.
These issues need to be checked.

**Comment by mintty** [comment] 2016-11-15 16:00
`ScriptStringAnalyse` can be fixed to obey the monospace character distribution by adding the piDx parameter. But:
* its font substitution differs from that of ExtTextOut (where it works) in unpleasant ways, e.g. CJK characters are tinier than they would need to be
* it fails miserably on some script ranges, e.g. Arabic or Hangul Jamo, for no apparent reason
* it does not seem to combine ligatures (#601) (likely not supported in Uniscribe "basic" mode)

If someone demonstrates how this can be managed, we'll get a step further...

**Comment by mintty** [comment] 2016-12-04 21:51
Release Uniscribe support in 2.7.1.
This does not solve *all* font fallback cases, though.

**Closed by mintty** 2016-12-04 21:51 UTC
Labels: duplicate, help wanted

**Comment by mintty** [comment] 2017-03-11 20:35
Released 2.7.5 with default FontRender=uniscribe.

**Comment by yossizahn** [comment] 2017-03-25 20:09
> This does not solve all font fallback cases, though.

I am using Consolas which does not contain Hebrew characters. Attempting to display Hebrew fails without even showing a box character - just an empty space. Using Windows Font Linking as mentioned in #573 also doesn't help even though it works for me in cmd.exe.
- Can Uniscribe rendering be enabled for RTL when --nobidi has been passed in?
- Why does font linking not help? Why am I not at least shown a box character? (not that a box character will help much, just it seems as though Hebrew characters are being explicitly filtered out).

**Comment by mintty** [comment] 2017-03-25 21:56
The box glyph is taken from the font, so it may vary, even with font fallback.
Why would you use the --nobidi option, actually?
Uniscribe for RTL may be an option.

**Comment by yossizahn** [comment] 2017-03-25 22:44
>The box glyph is taken from the font, so it may vary, even with font fallback.

Oh, I forgot to mention that the .notdef glyph (AKA box glyph) does appear for missing glyphs when they are LTR. 

>Why would you use the --nobidi option, actually?

Because bidi breaks curses apps when there are ui elements on the same line. e.g. mutt with sidebar enabled. (Perhaps there can be an option to disable/enable bidi on the fly? It would be useful.)

**Comment by mintty** [comment] 2017-03-25 23:19
I assume the .notdef glyph is taken from different fonts, according to script-dependent font fallback maybe.

My text editor mined supports bidi terminals; it clears lines below menus and repaints them after closing the menu.
Anyway, dynamic bidi control has already been suggested in #392. It might even match to the intended meaning of some special Unicode chars (to be verified); however, modifying the bidi algorithm to this aim is a tricky thing... Also, would that really help with an existing text editor? If a bidi line is already displayed, even if the program would then use those characters, previous text would not flip to non-bidi. There are quite a few subtle design issues to consider. If you can contribute with a convincing design, that will be appreciated.

**Comment by yossizahn** [comment] 2017-03-25 23:43
> I assume the .notdef glyph is taken from different fonts, according to script-dependent font fallback maybe.

I'd be surprised if that's the case since the .notdef glyph exists for cases where fallback fails.

> If you can contribute with a convincing design, that will be appreciated.

Yeah, Bidi is tricky... I haven't studied it in depth but in my opinion, bidi should only be enabled by default for plain text output - not for fullscreen apps, as often it will break them (unless they explicitly support it). It probably makes a lot more sense for the app itself to implement bidi display than for the terminal to force it upon it.

**Comment by yossizahn** [comment] 2017-03-26 00:16
A quick google around also seems to agree that bidi in terminals is problematic.
see:

- [Bug #263822 “RTL (right to left) support in terminal (BiDi)”](https://bugs.launchpad.net/ubuntu/+source/vte/+bug/263822/comments/46) on launchpad (comment 46 and on).
- [Bug 321490 – arabic, hebrew: character alignment not working properly](https://bugzilla.gnome.org/show_bug.cgi?id=321490#c29) at gnome [vte].
- [Re: Bidi terminal emulation considered harmful](https://lists.debian.org/debian-i18n/2001/11/msg00022.html) on debian mailing list.

**Comment by mintty** [comment] 2017-03-27 20:21
Thanks for the links. I guess I'll *try* to implement Unicode directional isolate characters.
Also, I tried to enable Uniscribe for RTL. It actually worked but the order of characters was corrupted. Also, I don't see how to configure that with Uniscribe. First quick attempt failed thus.
About enhancing the minibidi algorithm in mintty with Unicode bidi formatting, that will be tricky as well. May take a week or a year, who knows.

**Comment by yossizahn** [comment] 2017-04-02 11:48
BTW (not really the subject of this thread, but I'll point out anyway) mined also has issues with scrollbar being mangled when bidi is enable. So enabling bidi globally by default definitely doesn't seem a good idea.

**Comment by mintty** [comment] 2017-04-02 12:26
Mined should be disabling the scrollbar when it detects a bidi terminal; does that not always work?
With the bidi controls enabled, this would no longer be necessary.

**Comment by mintty** [comment] 2017-04-12 18:29
While implementing partial support for bidi markers, it became apparent that this is not sufficient to control absolute positioning (like for the application scrollbar or menu). A switching sequence may be added.

**Comment by mintty** [comment] 2017-04-13 23:22
Released 2.7.6.

**Comment by mintty** [comment] 2017-05-19 20:35
Released 2.7.7.

**Comment by cup** [comment] 2018-10-06 21:07
https://github.com/mintty/mintty/issues/573
https://github.com/mintty/mintty/issues/580
https://github.com/mintty/mintty/issues/605

**Comment by mintty** [comment] 2019-08-29 14:01
> `FontChoice=Common:6`

`Common` is not supported as it covers a set of basic punctuation and other symbols, not a script.

**Comment by mintty** [comment] 2022-03-20 10:50
For right-to-left scripts there is now a generic implicit font fallback mechanism: #1148
