### ISSUE TITLE
When a program accepts input, the arrow keys can move the cursor and program receives invalid input

### ISSUE THREAD

**Issue by Jimmio92** [mintty/mintty#556] opened 2016-05-29 07:18 UTC
Hello all,

I've noticed a very annoying problem with mintty in msys2. When a program requests input and you try to press the up arrow to select previously entered text/commands, the cursor moves instead. If you then ~~move the cursor back into its previous location and~~ hit enter, you can get trapped in a loop waiting for valid input as it never will be thanks to the cursor moving.

I'm not sure what's going on underneath to cause this, but it's really frustrating when I accidentally hit the up arrow to try and select last entered (which is a habit of mine during development of software), and I have to close the program and/or the terminal and relaunch. I do believe I have experienced the whole terminal being unable to be used because of this issue, but I do not recall how to cause it to happen.

I'm sorry in advance if this bug has been discussed before, or if I am not following best reporting practices. I am new to open source development, and therefore, the community involvement process(es).

**Comment by mintty** [comment] 2016-05-29 10:20
It might be useful to know *which* program you are running when the problem occurs. Likely being a native Windows program, this is a duplicate of a number of previous reports, and basically of #56.

**Comment by Jimmio92** [comment] 2016-05-29 16:35
My apologies for yet another duplicate. I should have went through all issues to see if they were similar, not just the issue titles.

I have figured out how to avoid this problem in my own programs, however I cannot fix some (no source). Basically, the problem lied in the fact that I did not check for error on input, and never cleared the fail bit(s).

**Comment by mintty** [comment] 2016-05-29 16:38
You may look for a cygwin/MinGW alternative package of your software, that should work then.
Otherwise you could try the `conin` tool mentioned in issue 56.

**Closed by mintty** 2016-05-29 16:38 UTC
Labels: duplicate

**Comment by mintty** [comment] 2019-12-16 23:44
Cygwin 3.1.0 has been released with ConPTY support.
