### ISSUE TITLE
Spurious control codes render "make nconfig" for Linux Kernel sources unusable (ncurses related?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#366] opened 2015-06-04 13:04 UTC
```
Steps to reproduce:
1. use mintty to connect to a box with linux kernel sources over SSH
2. use "make nconfig" to bring up ncurses-based config menu
3. start scrolling around with the arrow keys, rapidly.

Behaviour:
Obviously, you should be able to scroll around without issue, instead you get 
flipped backward out of menus, nconfig thinks you want to exit and other 
nonsense. The behaviour seems to worsen the longer mintty has been running.

I am running mintty 1.1.2 and latest Cygwin as of 25-12-2012
```

Original issue reported on code.google.com by `oli...@gmail.com` on 25 Dec 2012 at 8:49

**Comment by mintty** [comment] 2015-06-22 14:24
The issue is likely to be
- an interworking issue of cygwin and tmux, not mintty
- fixed with cygwin 2.*
Thus closing. If it still persists, report again, following the hints in issue #395.

**Closed by mintty** 2015-06-22 14:24 UTC
Labels: Type-Defect
