### ISSUE TITLE
mintty window fails to open if configured font is being uninstalled

### ISSUE THREAD

**Issue by BrianInglis** [mintty/mintty#1031] opened 2020-08-27 07:30 UTC
Set _Text Font_ via options or specify `Font=...` in `.minttyrc` to one you have installed, then deinstall that font: `mintty` windows will become unresponsive.
You will be unable to successfully start `mintty`, as the process will exit after a few seconds, perhaps flashing a narrow window one or two times. 
Edit `.minttyrc` to comment out `Font=...` line and `mintty` will start and display window.
If a font becomes unavailable, or is not found at startup, mintty should fall back to its default font `Lucida Console`.
Found this out while upgrading `Libre Office` which deinstalled fonts _I had installed_ previously: they too will be getting an issue report! ;^>

**Comment by mintty** [comment] 2020-08-27 08:04
Cannot reproduce this behaviour. I'm getting this (do you get it too?):
![grafik](https://user-images.githubusercontent.com/12740416/91414280-9e58ce00-e84c-11ea-809b-6c6f2ef945e3.png)
and then mintty starts with a system default font (Courier in my case).

**Comment by mintty** [comment] 2020-08-27 08:05
Maybe your system default was uninstalled too?

**Comment by BrianInglis** [comment] 2020-08-27 08:50
Do not see any dialogue box or window, other than narrow window flash(es) one or two times. 
FYI mintty latest 3.3.0 Cygwin previous 3.1.6, but my local build with my latest cpuinfo patch applied for testing at start of month (eating my own dog food!) 
No problem once I commented out `~/.minttyrc` `Font=...`, came up with `Lucida Console`, problem as soon as I tried to switch back via Options Text Font: font sample `Ferq`_&oelig;_ _m_&prime;4&euro; where _&oelig;_ ligature and _m_ are smaller? 
Windows versions of `gvim` and other programs also had similar issues with LibreOffice treatment of my default until reboot: not something one usually has to do after installs these days!  
[`LibreOffice` _bug_ **136170**](https://bugs.documentfoundation.org/show_bug.cgi?id=136170) If `LO` mess around with Windows default fonts as well they deserve a good drubbing with Unicode 13 emoji glyphs! ;^>

**Comment by mintty** [comment] 2020-08-27 09:09
So after you reboot, mintty would start again?
Can you retry with #define debug_create_font and #define debug_fonts enabled in wintext.c? (And running from another, still working mintty to see the debug output...)

**Comment by BrianInglis** [comment] 2020-08-27 09:31
After commenting out `~/.minttyrc` `Font=...` new mintty instance would start and run. 
Testing only possible during `LO` install/upgrade, fonts available after reboot. 
Both Cygwin 64 and 32 windows messed up then unresponsive after active font removal/replacement. 
Can start new instances of both after `~/.minttyrc` `Font=...` commented out.

**Comment by mintty** [comment] 2020-08-27 09:57
So if you manually uninstalled the configured font, the issue does not occur?
Maybe LO somehow uninstalls the font only half-way, or deactivates them somehow, so mintty thinks it exists but it doesn't work?

**Comment by mintty** [comment] 2021-07-23 21:34
Might be a race condition, but closing as not reproducible.

**Closed by mintty** 2021-07-23 21:34 UTC
Labels: obscure
