### ISSUE TITLE
Is there a way to set one mintty window always on top

### ISSUE THREAD

**Issue by fengyichui** [mintty/mintty#1095] opened 2021-03-05 05:09 UTC
Hi,
Is there a way to set one mintty window always on top. I found SysMenuFunctions option can set user command, but I can't found always-on-top function.
The [VcXsrv](https://sourceforge.net/projects/vcxsrv/) has the "Always on Top" system menu button:
![image](https://user-images.githubusercontent.com/17896291/110069942-e2a4c800-7db3-11eb-9b13-5b7335be3412.png)

**Comment by mintty** [comment] 2021-03-05 06:37
Duplicate of #294. I don't consider this a good option; other windows would be obstructed. Well, it's just an option anyway but what would be the use case?

**Comment by fengyichui** [comment] 2021-03-05 07:28
I offen open many wsltty windows to work. Sometimes my debuging device output log to a windows and I have to watch it to debug something, in the same time, I use GDB and VIM to debug the device. The log window is small but GDB and VIM window is large, So I can pin this log window to the top of GDB without affecting my debugging.

I think toggling Always-on-Top is very useful future. I found Microsoft [PowerToy](https://github.com/microsoft/PowerToys/wiki/Roadmap) will add this feature on its roadmap.

**Comment by avih** [comment] 2021-03-05 08:17
There are many utilities which can do that for any window, and you can also use a one-liner AutoHotKey script to toggle on-top for the current window with some custom key-combo of your choice.

Random google results (I have no experience with the mentioned utilities, except AutoHotkey):

https://www.groovypost.com/howto/howto/windows-programs-always-on-top/
https://superuser.com/questions/992445/make-any-windowed-application-always-on-top-without-keyboard-shortcut

**Comment by fengyichui** [comment] 2021-03-05 08:24
Thanks! I have used a utilitie tool to workaround it. I just think this may be a useful option.

**Comment by Biswa96** [comment] 2021-03-05 08:29
+1 vote from me. Though I use the AutoHotKey trick it will be a good option to add in mintty instead of relying on different tools.

**Comment by mintty** [comment] 2021-03-16 14:36
Released 3.4.7.

**Closed by mintty** 2021-03-16 14:36 UTC
