### ISSUE TITLE
URLs with parentheses are not clickable

### ISSUE THREAD

**Issue by pragma-** [mintty/mintty#1196] opened 2023-01-09 17:05 UTC
Hello again!

Thanks for the work on `OpeningMod` to support clickable URLs.  It's been working wonderfully!

I've been noticing a minor annoyance with URLs that contain parentheses, notably Wikipedia URLs. Would it be possible to include parentheses in the URL regex? Perhaps even an option to expose the regex as a configurable item if you're willing to go that far.

**Comment by Biswa96** [comment] 2023-01-09 17:23
Can you provide an example command or text file to reproduce the issue?

**Comment by mintty** [comment] 2023-01-09 18:56
URL selection follows the same pattern as word selection, so this request is a bit tricky; I don't think you'd like to select "abc (def)" as one word with double-click. You can adapt the character set with option WordChars for experimenting.

**Comment by mintty** [comment] 2023-01-10 07:57
It wasn't actually too tricky to distinguish URL and word selection. I've uploaded a tweak that allows parentheses (also square and curly) in URLs.

**Comment by mintty** [comment] 2023-01-10 18:18
<> are not included, before or after the patch.
! must be included, like ?&=, as they add parameters to a URL which are an essential part.

**Comment by mintty** [comment] 2023-01-10 18:25
OK, you say _trailing_ `!` etc, again a bit tricky though.

**Comment by pragma-** [comment] 2023-01-26 16:50
I've stumbled up on a related issue.

Given a URL like https://metacpan.org/pod/Thread::Csp, if I mouse-over the URL the whole thing underlines. But if I click the URL before the `::` part, it opens https://metacpan.org/pod/Thread.

If I click on the URL after the `::` (i.e. clicking on on `Csp`) then it opens the full URL to https://metacpan.org/pod/Thread::Csp.

**Comment by mintty** [comment] 2023-01-30 08:40
If I hover or click before `::`, only the prefix is underlined or opened.
If I hover or click behind `::`, the whole URL is underlined or opened, consistently.

**Comment by pragma-** [comment] 2023-01-30 23:55
I suspect it is the `WordChars=[a-zA-Z0-9()_:/?#%&=.]` I had configured in an attempt to have URLs with `()` be clickable. I've removed this line and now I have the same behavior with `::` as you.

**Comment by yashpalgoyal1304** [comment] 2023-01-31 18:36
hey @pragma- , what's your use case for this?

depending on use case, the urls may also be following by closing parenthesis, which will require even more tuning to get right. but thankfully, the situation i am thinking of for that doesn't generally have to deal with terminals

so, i am interested to know what is your use case for urls in terminal?

**Comment by pragma-** [comment] 2023-02-01 06:42
@yashpalgoyal1304 Mostly IRC. But also manpages, READMEs, comments in source files, and more.

**Comment by pragma-** [comment] 2023-02-01 06:46
If the URL is followed by a closing parenthesis but does not contain an opening parenthesis, then the closing parenthesis ought to be discarded/ignored, I think? I personally have never ever seen a URL that has a `)` in it at the end without a `(` within the URL.

**Comment by pragma-** [comment] 2023-02-01 06:48
Perhaps instead of trying to hardcode a URL parser it may make sense instead to use a lightweight regexp library and expose a URL regex option so users can configure their own regexes for matching URLs, as many popular terminal emulators do?

**Comment by yashpalgoyal1304** [comment] 2023-02-01 07:58
> without a `(` within the URL.

no, i meant like this: `this was discussed at that issue (https://example.org)` - here, the trailing closing parenthesis doesn't belong to URL. Is it already lexed as intended?

**Comment by pragma-** [comment] 2023-02-08 13:16
Another URL with weird hover/click behavior:

https://encrypted-tbn0.gstatic.com/images?q=tbn:therestoftheurl&usqp=CAU

If I mouse-over the part before the `:` in `tbn:` it underlines `https://encrypted-tbn0.gstatic.com/images?q=tbn` and if I mouse over after the `tbn:` it underlines `tbn:therestoftheurl&usqp=CAU`. I can't click this URL to open it properly.

Screen recording: https://i.imgur.com/jYdsyAv.mp4

**Comment by mintty** [comment] 2023-02-08 22:15
(Such issues can easily be reproduced, screen recording not needed.)
That's likely because ":" separates the protocol prefix of a URL. I am aware that URL identification is very heuristic. There are border cases, however, that make it hardly conceivable that all cases can reasonably be caught, e.g. a URL with a (...) section vs a URL completely put into parentheses (see above).
To open any problematic link, you can always simply select it with the mouse, then right-click and choose "Open".

**Comment by pragma-** [comment] 2023-02-08 23:45
I addressed how to easily disambiguate a URL with a (...) section vs a URL wrapped in parentheses already. Disappointing.

**Comment by yashpalgoyal1304** [comment] 2023-02-09 02:07
just sharing for reference:
* MS VS Code v1.75 ('23-01): [Better Terminal link detection]
Detect links containing spaces, brackets, line and column formats.

[Better Terminal link detection]: https://code.visualstudio.com/updates/v1_75#_link-improvements

**Comment by mintty** [comment] 2023-02-09 04:46
> I addressed how to easily disambiguate a URL

If it's so easy, you are welcome to propose an implementation.

**Comment by BrianInglis** [comment] 2023-02-09 05:31
[Source](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/languages/linkComputer.ts) MIT so cloneable. 
Just happy there is an Open link option: just click or drag to select -- easier for humans -- than dragging down the terminal with excessive, or really any, code for non-core functions! 
Still [prefer](https://en.wikipedia.org/wiki/Dr._Dobb%27s_Journal) ["Running Light Without Overbyte!"](http://www.computinghistory.org.uk/det/32190/Dr-Dobbs-Journal-of-Computer-Calisthenics-Orthodontia-Running-Light-Without-Overbyte/) ;^>

**Comment by pragma-** [comment] 2023-02-12 15:12
@yashpalgoyal1304  I've switched to wezterm. See https://github.com/pragma-/dotfiles/blob/3dbeec3c9b754fa664e5044dd56ed4d035f467c5/wezterm/wezterm.lua#L62-L78 for how I have URLs clickable in exactly the way I want.

**Comment by pragma-** [comment] 2023-02-12 15:14
@yashpalgoyal1304 also note https://github.com/pragma-/dotfiles/blob/3dbeec3c9b754fa664e5044dd56ed4d035f467c5/wezterm/wezterm.lua#L4 for starting Cygwin instead of CMD. wezterm supports WSL, as well, but I don't use that.

**Comment by yashpalgoyal1304** [comment] 2023-02-12 16:21
> for starting Cygwin instead of CMD

so, u dont use Msys2? i have just set my Environment variable `ComSpec` to be `<address of bash.exe>` i.e. `D:\msys64\bin\bash.exe` and wezterm respects that and starts in it by default

**Comment by pragma-** [comment] 2023-02-12 16:46
@yashpalgoyal1304 Nice! No, I like Cygwin's package manager and the ease it provides me in installing other things. I use `xwin.exe -multiwindow` along with `ssh -Y` to have some of my desktop apps x-forwarded to my Windows machine, for instance. X-forwarding isn't really that great, but I'm used to it and it works out of the box. It's fine for apps that are very light in their graphical usage.

**Comment by mintty** [comment] 2023-02-13 22:29
URLs are now matched with proper detection of parentheses nesting.
Different styles of parentheses are not distinguished however; should that be necessary, it'll be easy to add.

**Comment by mintty** [comment] 2023-02-13 22:38
The current patch also fixes the inconsistency around `::` when setting WordChars.

**Comment by pragma-** [comment] 2023-02-14 00:35
I previously closed this issue as `Not planned`. I did not realize development would continue on this. I've reopened it so that it may be closed as `Completed` when done.

**Comment by mintty** [comment] 2023-02-14 04:13
It could be considered done for now, unless parentheses style matching is desired or someone finds another problem with it.
I usually close issues with the next release.

**Closed** 2023-02-26 17:27 UTC

**Comment by mintty** [comment] 2023-03-25 03:54
Released 3.6.4.

**Comment by clayne** [comment] 2023-04-02 20:14
Related: https://github.com/mintty/mintty/issues/1208
