### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by lf-** [mintty/mintty#601] opened 2016-10-10 05:46 UTC
It would be really nice to be able to use ligatures in fonts like [Iosevka](https://be5invis.github.io/Iosevka/) and [Fira Code](https://github.com/tonsky/FiraCode) with mintty.

Currently, it seems that ligatures are not displayed.

**Comment by mintty** [comment] 2016-10-10 13:34
This may be beyond the Windows API currently used for text output (ExtTextOut), see #430 and https://github.com/mintty/mintty/issues/438#issuecomment-232723547.
Please describe more precisely what you are missing and what you see (e.g. rendered "fl" desired to be ligature <fl>?).

**Comment by lf-** [comment] 2016-10-10 16:34
Fira Code has some crazy ligatures for programming while remaining a
monospace done font. -> is a ligature, so is ==.

The issue is that the raw characters are displayed and not the ligatures.

**Comment by mintty** [comment] 2016-10-10 16:44
So you are not asking about any Unicode ligatures but rather font-specific ligatures.
I am not aware which Windows API, if any, would be able to handle them implicitly.
So it might be necessary to handle font information explicitly in mintty to achieve that.
You are welcome to make a proposal how to implement that.

**Comment by mintty** [comment] 2016-10-11 13:59
This functionality may be available with the [Uniscribe API](https://msdn.microsoft.com/en-us/library/windows/desktop/dd374093%28v=vs.85%29.aspx).
Handling the complexity of that API is however beyond my current ambition to enhance mintty.

**Comment by mintty** [comment] 2016-10-18 08:35
So here's your homework :):

* Either find any application with source code that implements this, find how it detects which character pairs have ligatures (mapping them to font glyphs).
* Or find out how the TrueType cmap tables can be retrieved using the Windows API and which tables contains the ligature information.

**Comment by mintty** [comment] 2016-10-20 14:27
@be5invis: taking over this issue here...

> You cannot enable ligatures unless you switch from GDI to DirectWrite or FreeType.

FreeType is an external library, and DirectWrite as well as Uniscribe are of deterring complexity. I've experimented with Uniscribe, though, and it does not seem to support ligatures (so I guess notepad uses DirectWrite...).

*But:* The information must be available somewhere in the font file. And using a mapping table like 
('-', '>', '⟶') mintty could output those glyphs by glyph index rather than character code, like it does for right-to-left text already.

**Comment by be5invis** [comment] 2016-10-20 14:34
@mintty Uniscribe does not support enabling arbitrary OpenType feature tag unless it is one of the “required” tags for typesetting complex scripts (like Devanagari).

**Comment by mintty** [comment] 2016-10-20 14:39
@be5invis Thanks for the confirmation.
What about the ligature information; isn't it available as a "table" in TrueType? Any idea how to access it?

**Comment by be5invis** [comment] 2016-10-20 14:41
@mintty It’s a **feature** located in `GSUB` table, and it is corresponded to a list of **lookups**. For most programming fonts, the feature is tagged as `calt`.

**Comment by mintty** [comment] 2016-10-20 14:53
Hmm, using a `ttfdump` tool, Iosevka doesn't seem to have any `calt` entries, and Fira Code has only 16 of them, looking as mysterious as this:
```
'calt'
FeatureT07b6
                      ; FeatureRecord[17]
...
Feature FeatureT07b6
NULL
3
25
26
27
```

Probably not worth the effort...

**Comment by be5invis** [comment] 2016-10-20 14:55
@mintty To avoid some compatibility issues under Linux, Iosevka Term turned off ligatures by default.

**Comment by mintty** [comment] 2016-10-20 15:00
"By default" means the information is not contained in the font?

Whatever, I think I'll just close this issue unless someone enthusiastic about the feature will
* demonstrate how it would be useful for at least a few fonts, and not for just 16 characters of one strange font (just look at the ugly 'm' of Fira Code!)
* provide code how to retrieve a suitable mapping table from a TrueType font (starting with the GDI function `GetFontData`) because I'm not going to dig into the incredibly over-engineered insanity of the TrueType format myself (that person would gain a place on the mintty credits page, of course)

**Comment by be5invis** [comment] 2016-10-20 15:03
@mintty Iosevka Term does not have any ligature data, while Iosevka does.

In most cases, the `calt` is implemented as a contextual substitution, which means that it will try to match a glyph sequence, and apply some other lookups (usually a single substitution, or a multiple-to-one substitution) to the specified position of the match. It is really hard to interpret it, especially you are on GDI.

**Comment by mintty** [comment] 2016-10-20 15:16
> * provide code how to retrieve a suitable mapping table from a TrueType font 

or make an implementation proposal to use DirectWrite, see #430

**Comment by k-takata** [comment] 2016-10-20 15:51
DirectWrite has GDI compatible mode. If you use it, you don't need to switch all graphics code to Direct2D.
Vim 8.0 also uses it: https://github.com/vim/vim/blob/master/src/gui_dwrite.cpp

**Comment by mintty** [comment] 2016-11-15 16:03
In referring issue #605, I tried to evaluate Uniscribe for this purpose.
About DirectWrite, thanks to @k-takata for referring to that example, but I'm not going to reverse-engineer 900 lines of code to understand that nightmare of an API, sorry.
If anyone comes up with a half-way working demo solution using either Uniscribe or DirectWrite, that will help.

**Comment by riedel** [comment] 2017-10-01 09:52
Maybe @koron can help figuring this out for mintty, too. Would also be a major break-though for vim users (like me) that rather use the command line on windows (ie. cygwin). Sorry for bumping this issue: still one year later there seems to be no actual terminal (that can e.g. run tmux) on windows with ligature support.

**Comment by k-takata** [comment] 2017-10-01 10:29
Mintty already uses Uniscribe. I don't think there is additional benefit by using DirectWrite with GDI-compatible mode.

**Comment by mintty** [comment] 2017-10-01 11:05
I think @riedel was referring to ligature support, not DirectWrite.
Uniscribe does not seem to provide it, at least not implicitly.

**Comment by k-takata** [comment] 2017-10-01 12:13
Oh, I misunderstood that Uniscribe provides (some kind of) ligature support.

**Comment by riedel** [comment] 2017-10-02 11:10
@k-takata: you are right: tt seems that uniscribe supports ligatures, but not the type of OpenType ligatures eg. used by Fira Code.

Here is a uniscribe tutorial that also does not work with Fira Code: https://www.catch22.net/tuts/introduction-uniscribe .  

https://maxradi.us/documents/uniscribe/ talks about font-specific ligature and how to use the more complex workflow using `ScriptShape` to compute ligatures, but I think this also does not apply to Opentype ligatures.  But it seems unlikely that this API level works any better. 

Like @mintty hinted at, it would be great to find a simple working "drop-in" example for `ScriptStringOut ` somewhere. I could not find one, sorry.

**Comment by riedel** [comment] 2017-10-28 11:59
I accidentally just saw that sometimes ligatures are actually working: 

![firacode](https://user-images.githubusercontent.com/566485/32134178-cea1bf66-bbe7-11e7-8eca-cca2e6bd6835.png)

**Comment by mintty** [comment] 2017-10-28 14:39
What's the actual output rendered here? Can you provide a screen log please (e.g. mintty -l)?

**Comment by riedel** [comment] 2017-11-11 14:05
I ran `mintty -l x.txt sh -c "head -204 Developer_Space%2FStandards.mw|tail -1"`, which gives you only the relevant line. I confirmed that it renders the ligature (only in the beginning but not the end of the line)

This is the output:
[x.txt](https://github.com/mintty/mintty/files/1463778/x.txt)

I was on the train writing a document at the time and wasn't looking any further. Now I looked into it  because it worked for none of the other lines, which seemed strange: it seems that the long dash (hex sequence 0xe28094) in the line triggers rendering the ligatures (others ligatures from fira code work as well).  Should be easy to replicate...

**Comment by mintty** [comment] 2017-11-11 16:49
This is a miracle of Uniscribe, I don't think mintty has control over it. However, some observations:
* with `-o FontRender=textout`, no ligatures are applied
* both a wrapped line (longer than the screen width) and the em dash are needed to trigger the leading ligature
* if the line is shortened to screen width, there is a break before the dash, i.e. mintty outputs the line in chunks (as can be seen with #define debug_win_text in wintext.c), and no ligature is applied if the chunk is only "=== Information technology "

**Comment by mintty** [comment] 2017-12-20 17:08
Update: a wrapped line is not needed to produce ligatures. At least one more character of some kind (non-ASCII?) after the initial === seems to be necessary. Exact conditions remain mysterious. Scrolling may alter the display (ligature/non-ligature). The whole scenario is chaotic and not likely to be controllable (with Uniscribe).

**Comment by mintty** [comment] 2018-01-02 12:12
I have to withdraw my previous assessment this would be "a miracle of Uniscribe".
Actually, there was some presumed "optimization" in mintty which applied a fallback from Uniscribe to TextOut for ASCII-only chunks, thus obstructing the application of ligatures for ASCII characters (unless combined with non-ASCII characters in a chunk, therefore the strange observations above).

The "optimization" was based on an assumed performance penalty of Uniscribe (of < 5%) which can, however, not be reproduced. I'm uploading a fix.

**Comment by mintty** [comment] 2018-01-02 12:14
There is still a gap in ligature support while you are on a ligature with the cursor, and also the refresh if you leave the ligature clear from the cursor is not always immediate.

**Comment by riedel** [comment] 2018-01-02 14:35
![ligatures](https://user-images.githubusercontent.com/566485/34486806-c85ab3b0-efd1-11e7-86c4-a8f8e4f02514.png)

Thanks! Had to try it out immediately. Works nicely for many programming ligatures now. Somehow as you see in the image some Fira Code ligatures seem to be different such as `->` and `=>`. As you described also the others also only work if the are redrawn together, but this is already pretty cool!

**Comment by mintty** [comment] 2018-01-03 18:48
I've tweaked output chunk breaking to keep longer chunks together as relevant for ligatures.
E.g. `:=` is now applied, but the ligatures with `<` or `>` and dashes are not applied, although they are now output in one chunk (term.c).

**Comment by mintty** [comment] 2018-01-04 12:03
How and by what criteria would font rendering actually distinguish between different semantics of character sequences?
Notepad with Fira Code combines `<=` to `≤` not `⇐`.

**Comment by mintty** [comment] 2018-01-08 21:25
Released 2.8.3.

**Comment by nurettin** [comment] 2018-07-04 08:53
As a vim user I noticed that the characters revert to non-ligature versions when the cursor moves over them. However, pressing Ctrl-L in normal mode causes a re-render and I can see the ligatures again.

**Comment by nurettin** [comment] 2018-07-04 08:57
Firacode readme says mintty doesn't support ligatures, so I'm going to open a [pull request](https://github.com/tonsky/FiraCode/pull/622) for them. 

![image](https://user-images.githubusercontent.com/988845/42267157-f9c593c2-7f80-11e8-8ef7-a4c1713ac41c.png)

**Comment by mintty** [comment] 2018-07-04 11:20
> characters revert to non-ligature versions when the cursor moves over them

Output is in chunks, separated e.g. at changing character attributes, and Windows ligature composition is applicable only to chunks.
I had considered to add support for character sequences with different background (which includes the cursor position). But I wasn't sure it's worth the effort or even really desirable;
if the cursor is within a ligature, you have the option to change one of the ligature base characters - isn't it better in that case to actually see the individual components?

**Comment by nurettin** [comment] 2018-07-04 11:35
> if the cursor is within a ligature, you have the option to change one of the ligature base characters - isn't it better in that case to actually see the individual components?

Considering the philosophy of ligatures, which is only concerned with better readability, I'd say it isn't worth the effort as I shouldn't be moving my cursor over those characters while reading in the first place.

**Comment by waynew** [comment] 2018-09-06 12:48
FWIW, in qterminal when you type ligatures followed by a space, e.g. `-> ` then it renders the ligature. I'm not sure if there's a reasonable way to trigger re-rendering the text that the cursor has moved over - or even the line that the cursor is on, but that would certainly help.

**Comment by mintty** [comment] 2018-09-06 13:43
By what criteria should mintty decide to trigger redisplay?
As this is additional runtime effort (and potential screen flickering), it should not be done unconditionally.

**Comment by mintty** [comment] 2018-09-13 21:06
Pending a design proposal, I'll not work on this for the next release which is about soon.

**Comment by nurettin** [comment] 2018-10-04 11:14
I think it makes sense to start a conforming implementation (like konsole+firacode) and copy what it does.

**Comment by mintty** [comment] 2018-10-04 11:36
I'd prefer if you comment on the current improvement first.

Then - conforming to what? - it may make sense to outline additional requirements/wishes.

Next steps could be a design proposal and then possibly some implementation. I doubt it makes much sense to clone code from a foreign project as the way output is rendered to the screen is likely to vary considerably.

**Comment by nurettin** [comment] 2018-10-04 14:16
Of course, when I use windows again, I will comment on it.

Just to clarify, by `conforming` I just meant `with ligature support` and
by  suggest'ng konsole as a reference implementation I just meant that
whenever you want to make a decision like whether we want to see the
sequence when cursor is over the glyph, it would make sense to me to just
use some other project as a reference about what to do (not the code)

**Comment by mintty** [comment] 2018-10-04 16:28
Released 2.9.3.

**Comment by riedel** [comment] 2018-10-06 08:17
`LigaturesSupport=2` works great for me!  Awesome!

As mentioned before an issue for me is the support for those ligatures with a combination of `>`,`=` and `-` in FiraCode:
```
<-< <<- <-- <- <-> -> --> ->> >->
<=< <<= <==    <=> => ==> =>> >=>
>>= >>- >- -< -<< =<<
</ <!--  </>  --> />
<= >= 
```

What puzzles me is that ligatures containing very similar characters render quite nicely for me, such as:
```
     <~~ <~ <~> ~~ ~> ~~>
     == != === !== =/=
     -- ---  
```
(complete list: https://github.com/tonsky/FiraCode/blob/master/showcases/showcases.txt)

I think @mintty also alluded to that fact of partial support in his comments towards https://github.com/tonsky/FiraCode/pull/622

**Comment by mintty** [comment] 2018-12-03 09:46
Ligatures are actually applied by Windows, as provided by the font.
Mintty support is limited to avoiding unnecessary splitting of output, e.g. by redrawing parts of the line that would not otherwise need to be redrawn. This is why currently ligatures are not supported if they comprise character with different background colour or underline attributes, including the cursor position.

**Comment by roastduck** [comment] 2018-12-03 09:55
So does a normal `<` or `>` sign always have different attributes? Why are these two signs so special?

**Comment by mintty** [comment] 2018-12-03 10:43
They are not really special, but somewhat ambiguous if ligatures are available e.g. for `<=` which could become either `≤` or `⇐`. However, if there is ever a choice between such alternatives, it would be made either by the font or by the Windows framework (Uniscribe), not by mintty.

**Comment by scfrazer** [comment] 2019-12-05 14:34
I understand there are good reasons not to do ligatures for things like '=>' because of all the use cases you want to support, but I would like to have them in a private fork for my personal use.  I am building mintty myself and have poked around in the code trying to figure out how to enable the extra ligatures I'd like, but I'm not having much luck.  It seems like it should be in src/term.c somewhere, but the changes I have tried so far (including turning on verbose debug output) haven't worked.  Can you point me in the right direction?  Thanks!

**Comment by mintty** [comment] 2019-12-05 15:18
As a special hack for `<-`, `->` and other combinations with `-`, you could try to disable line
    {0x002D, 0x002D, ES},
in file bidiclasses.t. If that's what you want, we could consider to reduce the number of cases of setting `break_run` in term.c, particularly depending on `bidi_class` in lines that do not set `has_rtl`.

**Comment by scfrazer** [comment] 2019-12-05 16:18
Thanks, but removing that line didn't seem to change things.  I pulled the latest code, did 'make clean && make', I assume that's all that is needed.  I'm sure the font family supports ligatures for '->' ... if I open the test file I am using in Notepad the arrow is displayed.

**Comment by mintty** [comment] 2019-12-06 17:47
I verified that "<-" is in fact handed over to Uniscribe for output in one bunch, even without that patch, actually.
Maybe some parameters to the Uniscribe functions (wintext.c) would make a difference?

**Comment by thisguychris** [comment] 2019-12-25 04:07
hey, @mintty 👋 Mintty is awsome! I've been trying your terminal out and it mostly checks all my list for a terminal. The last is Ligature Support which it seems that mintty actually supports.

I try to edit the shortcut 
`C:\Users\username\AppData\Local\wsltty\bin\mintty.exe -o Padding=200 -o LigaturesSupport=2 --WSL= --configdir="C:\Users\username\AppData\Roaming\wsltty" -~  -`

Am I doing it correctly? I'm using [Cascadia Code](https://github.com/microsoft/cascadia-code) which supports ligature, but it seems that it doesn't work.

**Comment by mintty** [comment] 2019-12-25 06:45
The release page says:
> As in 1911.20, this release includes Cascadia Mono, a version of Cascadia that doesn't have ligatures

**Comment by thisguychris** [comment] 2019-12-26 07:09
Hi @mintty, thanks for getting back with me. Happy Holidays! 🤗 I'm not using `Cascadia Mono`, I'm using `Cascadia Code` which does include ligatures.

As you see in the release, there are six assets, 
1. Cascadia -> with ligatures
2. Cascadia Mono -> without ligatures
3. Cascadia Mono PL -> without ligatures but with patched with powerline.
4. Cascadia PL -> with ligatures patched with powerlines
5. Source Code in .zip format
6. Source Code in tar.gz format

I'm using no. 1.
![Alt text](https://monosnap.com/image/N9c7Is7WmQjVNsHwIokz4u5Bvb5cbf)

**Comment by Biswa96** [comment] 2019-12-26 07:14
Off-topic here. Are you using wsltty? There will be a `wslbrige2.exe`. Can you execute it in Windows Terminal to check if it shows ligature correctly?

**Comment by Biswa96** [comment] 2019-12-26 09:04
Install Cascadia Code, set it default in mintty, run this:

    mintty.exe -o LigaturesSupport=1 -e wslbridge2.exe

Works in my case.

**Comment by mintty** [comment] 2019-12-26 09:12
Yes, it works. If you experience any special cases that don't, describe them.

**Comment by thisguychris** [comment] 2019-12-27 08:41
If I use what @Biswa96 suggested I get an error:
![Alt text](https://monosnap.com/image/zcIIXKALWqCyVwDxOL2RST5S5Ia6HO)

I tried playing with the settings thru the shortcut:
`C:\Users\username\AppData\Local\wsltty\bin\mintty.exe -o Padding=200 -o LigaturesSupport=1 --WSL= --configdir="C:\Users\username\AppData\Roaming\wsltty" -~  -`

It somewhat works with that configuration but it's missing converting some ligatures.
 
For eg.:
`=>` and `->` doesn't work/transform.

![Alt text](https://monosnap.com/image/mtE3Swj9SqsZnvv4Htks0KCfzsXgP0)

**Comment by thisguychris** [comment] 2019-12-27 08:56
I tried using Fira Code, which doesn't work either. I've also tried: LigaturesSupport=2 (which I found in this PR https://github.com/mintty/mintty/commit/f35aa2aa72295f979dd90250c98fa7a4dc9e1c2e)

**Using Fira Code:**
![Alt text](https://monosnap.com/image/bpflJvRvVPICxqRfLwH5zaTFq9tS02)

**Comment by mintty** [comment] 2019-12-27 16:32
OK, your report was it doesn't work. As you see in your line (foo == true), it does work.
Please check the discussion above for specific combinations that are not combined into a ligature.
I might add a summary to the documentation.

**Comment by thisguychris** [comment] 2019-12-28 01:30
oh okay @mintty sorry about that, so basically `mintty` has partial support of ligatures? Looking forward to the summary thanks again for the great work. 🙏🏻

**Comment by scfrazer** [comment] 2020-02-15 21:40
> I verified that "<-" is in fact handed over to Uniscribe for output in one bunch, even without that patch, actually.
> Maybe some parameters to the Uniscribe functions (wintext.c) would make a difference?

Sorry for the slow response, life got in the way.

I finally got it to work!  I played around with the Uniscribe parameters as you suggested, and the extra ligatures I wanted appeared when I passed in some different flags for the `SCRIPT_CONTROL` parameter in `ScriptStringAnalyse`:
```
  SCRIPT_CONTROL sctrl;
  ZeroMemory(&sctrl, sizeof(SCRIPT_CONTROL));
  sctrl.fMergeNeutralItems = 1;
  HRESULT hr = ScriptStringAnalyse(hdc, psz, cch, 0, -1,
    // could | SSA_FIT and use `width` (from win_text) instead of MAXLONG
    // to justify to monospace cell widths;
    // SSA_LINK is needed for Hangul and default-size CJK
    SSA_GLYPHS | SSA_FALLBACK | SSA_LINK, MAXLONG,
    &sctrl, NULL, dxs, NULL, NULL, &ssa);
```
Is this something you would want to incorporate, or should I maintain my own fork?

**Comment by BrianInglis** [comment] 2020-02-15 22:26
Add another bit setting to enable this in LigaturesSupport?

**Comment by mintty** [comment] 2020-02-16 09:38
Thanks for digging this out. No forks, please, I'll add that to the code. But it can only be an option, due to the ambiguity discussed before, see the marked case in the screenshot:
![grafik](https://user-images.githubusercontent.com/12740416/74602384-2729cc80-50a8-11ea-9263-b9dd51ddb76e.png)
Any idea how to tackle this (and other?) cases?
Should it be a distinct option or a bitmask variation as Brian suggested?

**Comment by scfrazer** [comment] 2020-02-16 12:19
Thanks for adding it as an option, I didn't want to have to keep up with all your releases.

Regarding the ambiguity, I imagine the common case of, say, '<=' is less-than-or-equal-to, not double-arrow-pointing-left.  The only way I see around it is if you think it is worthwhile to write code to scan blocks, potentially break them up, and feed them to Uniscribe with different options.  I suggest starting out with everything on or off, and see if many people ask for fine-grained control.  FWIW, all the other programs I have tried go the less-than-or-equal-to glyph route.

For the option, you could hedge your bet about people wanting more control and have another option that is a bitmask.  One bit for 'all ligatures on', and in the future other bits could be 'double-arrow-pointing-left on'.

**Comment by mintty** [comment] 2020-02-16 14:30
I wouldn't know how to persuade Uniscribe to render <= as left-arrow.

The current option is about interactive line rendering support (i.e. rendering while typing), which isn't yet perfect actually.
The new option would be about the range of ligatures to enable, so a bit different - maybe it should be a separate option `Ligatures` then.

**Comment by mintty** [comment] 2020-02-25 08:28
Released 3.1.4.

**Closed by mintty** 2020-02-25 08:28 UTC
Labels: Difficulty-Insane, enhancement, help wanted

**Comment by nyuszika7h** [comment] 2020-02-25 10:39
Nice, is wsltty going to be updated? (Also you forgot to actually release 3.1.0.3.)

**Comment by mintty** [comment] 2020-02-25 10:59
There is a bug with crash potential in the wslbridge gateway. Waiting for its fix.
