### ISSUE TITLE
Cygwin/Win7-8.1_External monitor_only title bar is transparent

### ISSUE THREAD

**Issue by arb-c** [mintty/mintty#561] opened 2016-06-16 09:48 UTC
Whether the desktop is switched to "extended", "external only" or "clone", the terminal background transparency is not working on the external monitor. In "extended" desktop, the terminal background features transparency on the laptop display, but when I drag the window to the external monitor, transparency disappears (the title bar remains transparent). Played with different levels of transparency / background color.

Tested on 
32-bit Mobile Intel 915/910 Win 7 in VGA
65-bit 2014 laptop Win 8.1 in HDMI & VGA

**Comment by mintty** [comment] 2016-06-16 12:34
This works here (Win 7).
Maybe there is some magic configuration effective on your external monitor that prevents transparency altogether?
By the way, I've heard of 36-bit computers and even 27-bit machines in history, but not of 65-bit processors yet :)

**Comment by mintty** [comment] 2016-06-21 07:12
Cannot reproduce the issue in Windows 10 either.
Closing.

**Closed by mintty** 2016-06-21 07:12 UTC
