### ISSUE TITLE
title bar is too large when moving from high dpi screen to low dpi screen

### ISSUE THREAD

**Issue by kangjianbin** [mintty/mintty#617] opened 2016-12-21 03:15 UTC
I'm using a high dpi laptop, while its builtin display is 3200x1800, and a monitor with 1920x1080.
While creating mintty windows on the monitor, I found that the title bar was too large:
![image](https://cloud.githubusercontent.com/assets/121803/21376251/7ceebcaa-c76e-11e6-970f-17e6212bacb5.png)

**Comment by mintty** [comment] 2016-12-21 06:56
Duplicate #588.
This issue is fixed for recent Windows releases.
For older releases, esp. Windows 7 (what's yours?), there is no fix possible, unless the title bar would be drawn by mintty itself, as discussed in #547.

**Comment by kangjianbin** [comment] 2016-12-22 02:53
I am using windows 10 version 1511 and mintty is built from newest git commit. Still has the problem.
The fonts in UI is large. But in terminal the font changes smoothly on different monitors.

**Comment by mintty** [comment] 2016-12-22 08:08
Thanks. The Windows fix is actually in the developers preview, not yet in the current release, I think, so you'll have to wait.
Anyway, the workaround (to use the new, not yet released Windows API to enable title bar scaling) is in mintty, so the issue is closed from a mintty point of view.

**Comment by mintty** [comment] 2017-04-12 15:01
Apparently fixed in current general Windows 10 release.

**Closed by mintty** 2017-04-12 15:01 UTC
Labels: duplicate
