### ISSUE TITLE
MinTTY silently exists if terminal type is set to "xterm-256color"

### ISSUE THREAD

**Issue by gsbabil** [mintty/mintty#747] opened 2018-02-25 12:36 UTC
## Bug Description

If terminal type is set to `xterm-256color` from `mintty` options,
[MSYS2][1] `bash` will abort, and thereby make `mintty` to silently
quit under default options.

This is probably an issue with `bash/terminfo` shipped with
[MSYS2][1]. I'm still reporting the issue here since `mintty` allows
setting the `xterm-256color` terminal type from within its options.

I'd appreciate if someone could help me narrow down the issue so
that it can be reported it to the right project.

## Environment

- MinTTY               : `2.8.3`
- Bash                 : `4.4.12(2)-release (x86_64-pc-msys)`
- [Git for Windows][2] : `2.16.2-64-bit`

## Steps to Reproduce

- Create a file named `C:\Users\<user-name>\.minttyrc-test` with the
    following one line content:

    ```
    Term=xterm-256color
    ```

- Run the following command:

    ```
    mintty
      --nodaemon
      --hold always
      --config C:\Users\<user-name>\.minttyrc-test
      -- /usr/bin/bash --login -i
    ```

- Bash's abort behavior can also be reproduced by running `mintty`
    without a configuration file (delete `.minttyrc`), and then
    running the following command from within an existing `mintty`
    session:

    ```
    TERM=xterm-256color bash
    ```

### Actual Result

- `mintty` silently quits (as `bash` silently aborts)

### Expected Behavior

- `mintty` and the shell should use the terminal type of
    `xterm-256color` without silently quitting

## Notes

Although I'm not 100% sure, this issue is more likely to be with
`bash` or `terminfo` database shipped with [MSYS2][1]/[Git for Windows][2].

I ran into the issue with `mintty-2.8.3` that is shipped with Git
for windows (version `2.16.2-64-bit`), and I'm reporting it here
since `mintty` supports setting terminal to `xterm-256color` from
within it's options (shown in the figure below).

![image](https://user-images.githubusercontent.com/1061108/36641423-48e4641e-1a83-11e8-8617-5c913e2fade8.png)

[1]: https://github.com/msys2/msys2
[2]: https://gitforwindows.org

**Comment by avih** [comment] 2018-02-25 12:42
Duplicate of #738 .

Fixed in upstream ncurses, made its way to MSYS2 already here https://github.com/Alexpux/MSYS2-packages/pull/1165 (run `pacman -Syu` to get the fix), and also already propagated to git for windows and will be available at their next release.

**Comment by mintty** [comment] 2018-02-25 12:51
> mintty silently quits (as bash silently aborts)

As you had already analyzed it's not a mintty issue, why do your report it here?

**Closed by mintty** 2018-02-25 12:51 UTC

**Comment by gsbabil** [comment] 2018-02-25 13:16
@avih

Thanks a lot for the details. Much appreciated.

@mintty

> `mintty` wrote:
>
> As you had already analyzed it's not a mintty issue, why do your
> report it here?

>> `gsbabil` wrote:
>>
>>  ... I'm still reporting the issue here since `mintty` allows
setting the `xterm-256color` terminal type from within its options

Because I think the issue is likely to affect other `mintty` users
and it really stemed from a `mintty` setting in my case.

Thank you.
