### ISSUE TITLE
Weird behavior with Meslo fonts (inducing condensed ligatures)

### ISSUE THREAD

**Issue by avoidik** [mintty/mintty#754] opened 2018-03-20 14:26 UTC
![image](https://user-images.githubusercontent.com/6435932/37660234-9849a4e0-2c5a-11e8-86ca-382a8a8d7046.png)

On the first line you can see in echo output that "f"-character somehow influences the next character after it. When I press Up arrow on keyboard (select previous command from history) same issue occurs for actual input.

mintty 2.8.4

Font MesloLGM NF from here:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo/M/complete

**Comment by mintty** [comment] 2018-03-20 19:46
"fl" is substituted by an fl ligature here.
For a fixed-width font, if it includes ligature replacement, the ligatures used as substitutes should not affect the total string width, like FiraCode does (see #601). Apparently this Meslo version does not respect fixed font width when handling ligatures. Please report this as a bug to the font.

**Comment by avoidik** [comment] 2018-03-20 19:54
More interestingly that I haven't had any issues with 2.7.9 version

**Comment by mintty** [comment] 2018-03-20 23:09
2.8.3 fixed ligature support. But the behaviour of that font is broken.

**Comment by ryanoasis** [comment] 2018-03-21 10:46
https://github.com/ryanoasis/nerd-fonts/issues/186 might be of relevance to you

**Comment by mintty** [comment] 2018-03-24 13:40
Cannot reproduce with the linked font, was it updated meanwhile?
As a workaround, you could also try to set `-o FontRender=textout`.

**Comment by avoidik** [comment] 2018-03-24 16:12
With `-o FontRender=textout` it worked as expected

**Comment by mintty** [comment] 2018-03-25 07:03
Cannot reproduce with your config file. I doubt we're having the same font version because for me the font properties info show Leading: -3, Underline: manual.

**Comment by mintty** [comment] 2018-03-28 15:27
I would have waited with closing this issue until I could reproduce a Meslo update that fixes this.
However, as I couldn't even reproduce the broken ligatures in the first place, can we close the issue or is anything still unclear?

**Comment by avoidik** [comment] 2018-03-28 15:50
Yes, please close it

>

**Closed** 2018-03-28 16:04 UTC

**Comment by mintty** [comment] 2019-11-19 16:20
With the next release, it will be possible to configure using a "nerd font" or otherwise for for "Powerline" only for Private Use ranges.

**Comment by mintty** [comment] 2019-11-23 18:57
Released 3.1.0.
