### ISSUE TITLE
Tab as last character on terminal not displayed

### ISSUE THREAD

**Issue by faramir** [mintty/mintty#1020] opened 2020-07-10 06:45 UTC
There is buf (I think it is regression from 3.1.4) on mintty 3.2.0 (x86_64-pc-cygwin) [Windows 19041].

In cygwin/bash (terminal size 80x25) type command:
```for i in `seq 10 50`; do echo -ne "$i$i.$i\t"; done```
The output is:
```
1010.10 1111.11 1212.12 1313.13 1414.14 1515.15 1616.16 1717.17 1818.18 1919.192
020.20  2121.21 2222.22 2323.23 2424.24 2525.25 2626.26 2727.27 2828.28 2929.293
030.30  3131.31 3232.32 3333.33 3434.34 3535.35 3636.36 3737.37 3838.38 3939.394
040.40  4141.41 4242.42 4343.43 4444.44 4545.45 4646.46 4747.47 4848.48 4949.495
050.50
```
but should be:
```
1010.10 1111.11 1212.12 1313.13 1414.14 1515.15 1616.16 1717.17 1818.18 1919.19 
2020.20 2121.21 2222.22 2323.23 2424.24 2525.25 2626.26 2727.27 2828.28 2929.29 
3030.30 3131.31 3232.32 3333.33 3434.34 3535.35 3636.36 3737.37 3838.38 3939.39 
4040.40 4141.41 4242.42 4343.43 4444.44 4545.45 4646.46 4747.47 4848.48 4949.49 
5050.50
```

The problem is with the last tab (when the 1 char left) on line.
Changing command to (`\t` changed to ` `):
```for i in `seq 10 50`; do echo -ne "$i$i.$i "; done```
produces proper output:
```
1010.10 1111.11 1212.12 1313.13 1414.14 1515.15 1616.16 1717.17 1818.18 1919.19 
2020.20 2121.21 2222.22 2323.23 2424.24 2525.25 2626.26 2727.27 2828.28 2929.29 
3030.30 3131.31 3232.32 3333.33 3434.34 3535.35 3636.36 3737.37 3838.38 3939.39 
4040.40 4141.41 4242.42 4343.43 4444.44 4545.45 4646.46 4747.47 4848.48 4949.49 
5050.50
```

Changing terminal size to 81x25 also produces right output.

**Comment by mintty** [comment] 2020-07-10 21:25
It's not a regression, it has always been like this and behaviour is consistent with xterm.
It's related to the "pending wrap position" behaviour of DEC terminals (which is admittedly a bit weird).

**Comment by faramir** [comment] 2020-07-11 06:12
OK, so are there any workarounds to have that behaviour changed, that tab is at least one char long or start at the position _mod 8 == 0_?

**Comment by mintty** [comment] 2020-07-11 09:40
> It's related to the "pending wrap position" behaviour of DEC terminals

Actually, it's due to the fact that TAB does *not* set the "pending wrap" state. It could be checked with VT100 whether that's really the original behaviour (or checked in xterm documentation whether there is a comment on this already).

**Comment by avih** [comment] 2020-07-11 11:00
> The output is:
> 
> ```
> 1010.10 1111.11 1212.12 1313.13 1414.14 1515.15 1616.16 1717.17 1818.18 1919.192
> 020.20  2121.21 2222.22 2323.23 2424.24 2525.25 2626.26 2727.27 2828.28 2929.293
> 030.30  3131.31 3232.32 3333.33 3434.34 3535.35 3636.36 3737.37 3838.38 3939.394
> 040.40  4141.41 4242.42 4343.43 4444.44 4545.45 4646.46 4747.47 4848.48 4949.495
> 050.50
> ```

That's exactly how a real VT102 behaves:
```
--- LED [ BEEP SCAN LOCAL LOCKED CTS DSR INSERT L1 ] CLK 5668864
 0 ││
 1 ││
 2 │$ bash -c 'for i in `seq 10 50`; do echo -ne "$i$i.$i\t"; done'                 │
 3 │1010.10 1111.11 1212.12 1313.13 1414.14 1515.15 1616.16 1717.17 1818.18 1919.192│
 4 │020.20  2121.21 2222.22 2323.23 2424.24 2525.25 2626.26 2727.27 2828.28 2929.293│
 5 │030.30  3131.31 3232.32 3333.33 3434.34 3535.35 3636.36 3737.37 3838.38 3939.394│
 6 │040.40  4141.41 4242.42 4343.43 4444.44 4545.45 4646.46 4747.47 4848.48 4949.495│
 7 │050.50  $                                                                       │
 8 │                                                                                │
 9 │                                                                                │
10 │                                                                                │
11 │                                                                                │
12 │                                                                                │
13 │                                                                                │
14 │                                                                                │
15 │                                                                                │
16 │                                                                                │
17 │                                                                                │
18 │                                                                                │
19 │                                                                                │
20 │                                                                                │
21 │                                                                                │
22 │                                                                                │
23 │                                                                                │
24 │                                                                                │
25 │                                                                                │
```

`bash -c` because `echo -ne` is non standard, but bash does support it.
Tested using http://blog.schmorp.de/2015-11-10-emulating-vt102-hardware-in-perl-1.html

**Comment by mintty** [comment] 2020-07-11 22:00
I was pondering whether to consider an option to make TAB consistent with other characters with respect to auto-wrap behaviour, but on the other hand, TAB is not a printable character so not really comparable. It's common description as horizontal tabulation suggests it advances the cursor only horizontally, thus not having any wrap behaviour associated.

**Closed by mintty** 2020-07-11 22:00 UTC
