### ISSUE TITLE
Window=max doesn't work

### ISSUE THREAD

**Issue by arcanis** [mintty/mintty#850] opened 2019-02-12 19:48 UTC
Maybe a race condition w/ tmux? The `Window=max` option opens the window maximized, but its content has the regular size, as seen on the following screenshot:

![image](https://user-images.githubusercontent.com/1037931/52663675-0d86ff80-2eff-11e9-9092-a74c94c33057.png)

**Comment by arcanis** [comment] 2019-02-12 19:50
Interestingly, `-w` does work - is there a semantical difference? I've used `Window=max` based on the answer to [this SO question](https://stackoverflow.com/questions/33991079/git-bash-mintty-how-to-open-maximized).

**Comment by arcanis** [comment] 2019-02-12 19:58
Not a tmux problem - running `echo $COLUMNS` from outside tmux yields 80 (instead of 190 after manually resizing / expanding the window).

**Comment by mintty** [comment] 2019-02-13 00:08
Works fine here. Maybe you have something setting COLUMNS in your .profile or .bashrc?

**Comment by arcanis** [comment] 2019-02-13 08:59
Couldn't find anything. Running `tput cols` also reports 80 columns, so it looks like more than just an environment problem (I'm running with the latest wsltty release btw).

I've tried with /bin/bash as startup shell (I'm using zsh+tmux otherwise), and the same problem can be reproduced there as well.

**Comment by mintty** [comment] 2019-02-13 11:32
You had'nt said it's with wsltty. That might make a difference, possibly.
There have been similar reports before (#675, wsltty#73), without solution but also without evidence of faulty behaviour. It's hard to debug such an issue remotely. But it's likely there's something in your local startup environment that spoils the settings. Which WSL distribution do you use? Did you change any WSL startup scripts?

**Comment by mintty** [comment] 2019-02-27 07:46
> Which WSL distribution do you use? Did you change any WSL startup scripts?

Please add `stty size` at the top of all your WSL startup scripts (.profile or .bash_profile, .bashrc, /etc/... if you changed any, zsh-specific ones).

**Comment by mintty** [comment] 2019-03-26 14:09
As this is not reproducible and likely caused by some intricate local setup details, I'm closing the issue.

**Closed by mintty** 2019-03-26 14:09 UTC
