### ISSUE TITLE
Mouse click is not working when font size is small

### ISSUE THREAD

**Issue by dzhang-b** [mintty/mintty#949] opened 2019-12-20 19:55 UTC
Hi, 

I am using MINGW64 terminal simulator (3.0.1) from Git for windows. When the **the font size is 9**, and I split multiple vim windows vertically, The mouse click wont work for the rightmost windows.

When I change the font size >= 12, mouse click seems to work again.

Easily to reproduce with the following commands:
```
vim -u NONE
:set mouse=a
```
and do `Ctrl-w v` multiple time and then try to click the rightmost window.

**Comment by mintty** [comment] 2019-12-20 23:46
Cannot reproduce (mintty 3.1.0, cygwin), even if the rightmost pane is only 1 column wide.

**Comment by dzhang-b** [comment] 2019-12-21 00:29
How about full screen the terminal emulator? It seems to have a dead zone area where mouse click cannot be captured.

Btw, is it possible to install a standalone mintty terminal emulator?

**Comment by mintty** [comment] 2019-12-21 00:35
You should click into a used, valid column.

Mintty runs a client in it, pure deployment does not make much sense. But you can bundle it with specific clients. One such project is wsltty, another is mined.

**Comment by dzhang-b** [comment] 2019-12-21 00:43
Yeah, what I mean is that in the right hand side of the terminal, there are two vim columns. The right most column is completely un-clickable, but the column next to it I can only click on the start part of the line but not end of line.

**Comment by mintty** [comment] 2019-12-21 00:49
As I said, I did not reproduce this. Maybe more precise instructions and/or a screenshot could help.

**Comment by mintty** [comment] 2020-03-11 10:50
Closing as no reproducible issue was estasblished.

**Closed by mintty** 2020-03-11 10:50 UTC
