### ISSUE TITLE
pass scrollback to user-defined commands

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#475] opened 2015-08-31 20:57 UTC
In mrxvt, it is possible to define commands and bind them to keyboard shortcuts which can get (all or one page) of the scrollback buffer as stdin. Can we have that in mintty please?

Here are some examples why I find that useful:
* Together with a script which writes stdin to a file and opens that file in an editor, this feature could be used as a workaround for selecting text with the keyboard (issue #84).
* Together with less, it's a good compromise between wrapping and horizontal scrolling (#138): mintty itself could keep wrapping; whenever the user notices that the previous command had better been piped to less, she presses the keyboard shortcut to view the scrollback in less.
* While we're at it, less also handles #85 :-)

I'm not quite sure whether those custom commands should see the original text with ANSI escapes or a "sanitized" version, or whether selectable per command. Probably the former, and leave removing escapes to the command if necessary?

Please also consider adding the custom commands to a sub menu of the context menu for people running out of hotkeys. Thanks!

**Comment by mintty** [comment] 2015-09-01 12:34
Not having user-definable hotkeys right now, what about a solution to access the scrollback buffer via the clipboard? (Using an escape sequence to copy it to the clipboard which can be invoked from a script.)

**Comment by mkq** [comment] 2015-09-01 15:51
Thanks for the feedback.

I would like to avoid the clipboard, because I usually have a multi-clipboard tool ([Ditto](http://ditto-cp.sf.net/)) running which would then store a lot of stuff that I don't need in there. So the scrollback data would replace "more valuable" data or I would have to let Ditto store more entries and probably require more memory.
And also without running any multi-clipboard manager, I think invoking those commands in mintty would "feel" mintty-internal, not like writing to clipboard. So I expect quite a lot accidental clipboard overwrites.

BTW, I would also like to avoid temp files (too much stress for the disk, maybe).

How about one more non-configurable shortcut (maybe CTRL+Menu) to open a commands popup menu? The entries' order, names and underlined shortcuts (I mean like the A in "Select All" in the context menu) should be configurable. (That would be [Autohotkey](http://www.autohotkey.com/)-friendly, so I could still have all the hotkeys I want.)

**Comment by mintty** [comment] 2015-09-01 16:27
So you are basically not asking for a scrollback buffer feature, but for user-defined commands.
Which means I am closing this issue as a duplicate of #100.

**Closed by mintty** 2015-09-01 16:27 UTC

**Comment by mkq** [comment] 2015-09-01 19:26
With its current description, I don't think that #100 covers my needs. My wish is to use the scrollback without mouse selection, while #100 is about mouse selection or mouse click position AFAIU. 

Would you expand #100 to cover scrollback? I.e. add two additional placeholders for one page / all of scrollback? 

I'm not familiar with the suggested .mailcap format. The placeholders %s and %t sound like they would specify arguments - so would scrollback be written to a temp file and the placeholder be replaced with its name? Or would it also support file-less piping as I suggested?

BTW, ideally that "one page" would be according to the current scroll position, not necessarily the end of scrollback. I forgot to mention that earlier.

**Comment by mintty** [comment] 2015-09-01 20:21
Issue 100 is substantially about user-defined functionality. That is the major effort of the implementation.
I'm not referring to details of the discussed proposals there; adding comfort like references to the scrollback buffer would be a minor issue then.
Don't expect much this year... sorry.

**Comment by mkq** [comment] 2015-09-01 20:30
Ok, I'll watch issue 100 then. Thanks.

**Comment by mintty** [comment] 2017-02-16 20:45
The repository version now supports user-defined commands, including substitution of the selection or scrollback buffer. See manual page for a description.
Please give it a try and provide feedback.

**Comment by mintty** [comment] 2017-03-11 21:01
Released with 2.7.5.
