### ISSUE TITLE
ansi background color goes over the tail of the next line

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#413] opened 2015-06-04 13:04 UTC
```
if the line is wrapped in the middle of a highlighted word
then background "flows down" to the end of the next line
see screenshot attached

test command
perl -e '$x="1234567890"; $xBg="\e[41m$x\e[0m"; print "\n\n---ok---\n$x $x $xBg 
$x $x $x"; print "\n\n---bug---\n$x $x $x $x $xBg $x\n\n"'

winxp
cygwin
mintty 1.1.3

```

Original issue reported on code.google.com by `bdim...@gmail.com` on 26 Nov 2013 at 3:39

Attachments:
* [mintty-background-goes-down.png](https://storage.googleapis.com/google-code-attachments/mintty/issue-413/comment-0/mintty-background-goes-down.png)

**Comment by mperry2** [comment] 2016-04-11 23:17
It's not a bug. It's the correct behavior for xterm (which mintty emulates) because the terminal capabilities has `back_color_erase` (bce) set.

The reason you see it with the scrollbar is because your cursor has reached the bottom of the window. In that case the example code is changing the color of the background and then the text is wrapping to a new line at the bottom of the window while the background is set to red. The background of the new line that appears is filled with the current background color which is red.

**Comment by mintty** [comment] 2016-04-12 07:53
Right, thanks. For the records, the feature used to be configurable in putty (from which mintty was derived) and one could arguably ask for the option to unset it because that behaviour is nicer. But then we'd have a deviating terminal spec. And (as I had commented before) programs relying on the feature *unset* are not very portable. Thus I think I'll just close the issue.

**Closed** 2016-04-22 13:26 UTC
Labels: Type-Enhancement
