### ISSUE TITLE
mintty 3.4.4 middle button/mouse wheel press no longer pastes with default config

### ISSUE THREAD

**Issue by BrianInglis** [mintty/mintty#1081] opened 2021-01-22 02:42 UTC
```
$ win-ver.sh
Windows 10 Home Client Core Multiprocessor Free 6.3 1909 19h1_release 10 0 18363 1256
$ uname -srvmo
CYGWIN_NT-10.0 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
$ mintty -V
mintty 3.4.4 (x86_64-pc-cygwin)
© 2013/2020 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
$ fgrep MiddleClickAction /etc/minttyrc ~/.minttyrc
/etc/minttyrc:#MiddleClickAction=paste  # Middle click action paste|extend|enter|void
~/.minttyrc:#MiddleClickAction=paste    # Middle mouse button paste|extend|void|enter
```
Keyboard `<Shift><Insert>` still works okay

**Comment by mintty** [comment] 2021-01-22 11:21
Strange. How about
grep MiddleClickAction /etc/minttyrc "$APPDATA/mintty/config" ~/.config/mintty/config ~/.mintty/config

**Comment by BrianInglis** [comment] 2021-01-22 19:46
Default or nonexistent: 
```
$ fgrep MiddleClickAction /etc/minttyrc ~/.minttyrc "$APPDATA/mintty/config" \
					~/.config/mintty/config ~/.mintty/config
/etc/minttyrc:#MiddleClickAction=paste # Middle click action paste|extend|enter|void
$HOME/.minttyrc:#MiddleClickAction=paste # Middle mouse button paste|extend|void|enter
grep: $HOME/AppData/Roaming/mintty/config: No such file or directory
grep: $HOME/.config/mintty/config: No such file or directory
grep: $HOME/.mintty/config: No such file or directory
```
How to proceed to determine if it a Cygwin, console, Windows, or mintty change?

**Comment by mintty** [comment] 2021-01-23 01:17
Mintty has not changed in this respect and I do not reproduce the issue.
Maybe your mouse configuration changed? Does it work in any other application?

**Comment by antoineco** [comment] 2021-02-03 16:53
`mintty 3.4.4` user here, plain default config and can confirm it works for me.

**Comment by mintty** [comment] 2021-02-07 16:37
@Biswa96 , you applied a "thumb" to the original report, do you reproduce any issue here?

**Comment by Biswa96** [comment] 2021-02-07 19:05
Yup.

**Comment by mintty** [comment] 2021-02-07 21:26
Well, there must be something weird happening. As 2 experts observed an issue that I don't reproduce, can somebody analyse it?

**Comment by Biswa96** [comment] 2021-02-08 04:25
Let me unlease my ultimate power, 'printf debugging' 😎 Is there any way to see either mouse middle button click is registered, processed etc.?

**Comment by BrianInglis** [comment] 2021-02-08 06:38
It may be a Windows bug and/or some kind of device feature to "better" support touch alternatives (tablet tail still wagging the desktop gorilla), as the mouse control panel setting for middle button/scroll wheel click has disappeared, according to existing advice about tuning this feature. 
As long as Windows still supports their "borrowed" Motif CDE <c-Ins>, <s-Del>, <s-Ins> keyboard operations, I'll use them instead after mouse selection.

**Comment by mintty** [comment] 2021-02-08 09:22
@Biswa96 : there is #define dont_debug_messages in winmain.c, remove the "dont_".
With #define debug_messages , you'll get a _lot_ of output!
You can also rm ../bin/cygwin64/winmain.o; make CCOPT=-Ddebug_messages for a temporary build.

@BrianInglis : that sounds like it, but message debugging could perhaps reveal an alternative to catch the case...

**Comment by Biswa96** [comment] 2021-02-10 05:07
> there is #define dont_debug_messages in winmain.c, remove the "dont_".

If I do this, I get compiler error `winmain.c:2621:10: fatal error: _wm.t: No such file or directory`

> make CCOPT=-Ddebug_messages for a temporary build

If I do this I get compiler error `winctrls.c:1503:12: fatal error: _wm.t: No such file or directory`

**Comment by mintty** [comment] 2021-02-10 13:03
Yeah, sorry. There are a few debug includes that need to be generated, like: `make _wm.t`. (I think this would work automatically after `make clean`.)

**Comment by Biswa96** [comment] 2021-02-10 13:38
Maybe the middle button of my mouse does not work 😟 mintty does not show any debug event. I have tried with AutoHotKey `~MButton::Send {Volume_Up}` for testing (why did not I come up with this idea first). By the way, I have to do this `cd mintty/src; make _winidm.t _wm.t`, it may be built by default.

**Comment by mintty** [comment] 2021-02-10 18:08
OK, thanks for the feedback, so I'll close the issue for now.

**Closed by mintty** 2021-02-10 18:08 UTC
