### ISSUE TITLE
Cygwin nonfunctional when using Azure AD

### ISSUE THREAD

**Issue by bcampitf** [mintty/mintty#563] opened 2016-06-26 23:20 UTC
I posted this over in issue #493  before noticing the issue was closed. I'm having the same problem and I haven't found any solution, besides not using Azure Active Directory.

Cygwin doesn't seem to work properly when invoked from a domain account on an Azure AD joined machine.

Trying to launch the Cygwin64 Terminal results in -

`Error: could not fork child process: There are no available terminals. 
`

bash can be started via cmd.exe, but many utilities don't work properly. I think its due to Cygwin being unable to determine a user's id when logged in via an Azure AD account -

```
C:\cygwin64>bin\bash -l

Unknown+User@DESKTOP-3PFRJV1 ~
$ whoami
Unknown+User

Unknown+User@DESKTOP-3PFRJV1 ~
$ tmux
open terminal failed: not a terminal

Unknown+User@DESKTOP-3PFRJV1 ~
$ whoami
Unknown+User

Unknown+User@DESKTOP-3PFRJV1 ~
$ id
uid=4294967295(Unknown+User) gid=4294967295(Unknown+Group) groups=405504(High Mandatory Level),544(Administrators),545(Users),4(INTERACTIVE),66049(CONSOLE LOGON),11(Authenticated Users),15(This Organization),66048(LOCAL),4294967295(Unknown+Group),262180(Cloud Account Authentication)

Unknown+User@DESKTOP-3PFRJV1 ~
$
```

Other utilities, like X, also break with similar errors.

**Comment by mintty** [comment] 2016-06-27 13:57
> I posted this over in issue #493 before noticing the issue was closed.

because, as I tried to explain there, there is no evidence of a mintty issue. Also what is this about Azure?

> but many utilities don't work properly

> Other utilities, like X, also break with similar errors.

Both observations reported by yourself, confirm this has nothing to do with mintty. These things unfortunately tend to happen with a cygwin installation, especially in unusual system environments, and they are certainly a nuisance for the impacted user, but the mintty issue tracker is not the right place to seek support about them.

**Comment by bcampitf** [comment] 2016-06-27 14:07
Windows 10 (maybe 8 too?) will allow you to join machines directly to an Azure AD domain rather than a traditional AD domain. The experience is similar to a traditional AD domain, except that you authenticate with your company's Azure AD credentials when logging in, and your favorite terminal won't launch :)

I reported it here because I'd seen it reported here in the other issue #, but see that I should have reported it directly to Cygwin.

Thanks

**Comment by michaellashinsky** [comment] 2016-07-14 01:13
Installing git for windows and electing to install Mintty as your terminal with a machine that is connected to an Azure domain does readily reproduce this issue.  If you elect to install git for windows without using Mintty as your terminal, all is good and git bash can be used albeit in a regular terminal window.  If you install it on a machine that is a regular Microsoft or even a local account the issue does not occur.  The issue appears to be related to the user not being picked up.  When you launch a terminal connecting to bash on a AADD instead of getting your user name you get Uknown+User@machine name as your user.  Being that Unknown+User doesn't have permission to do anything it breaks.

**Comment by mintty** [comment] 2016-07-14 12:44
That might give a clue indeed, although it's not precisely the "unknown" user mapping; I have seen other machines with network domain accounts that report this and where mintty runs seamlessly.

But in fact missing permissions to either fork() or create a pty would explain the failure, if these features depend on any permissions at all. Both problems are out of scope of mintty, however. Perhaps you/we should take this to the cygwin mailing list.

**Comment by michaellashinsky** [comment] 2016-07-14 13:17
I can most certainly do that.  If I run whoami /fqdn it returns with something along the line is user is not a member of a domain.  The domain that I am connected to is an azure domain which is kind of like a fake domain.

**Comment by mintty** [comment] 2016-07-14 17:15
I have committed a patch that should provide at least some more precise information on which system call actually fails. Please try the current repository version.

**Comment by michaellashinsky** [comment] 2016-07-17 21:54
Sorry been away, I can will grab the repo version and give it a shot.

**Comment by mintty** [comment] 2016-07-23 18:37
Enhanced error diagnostics available with release 2.4.1. Please check.

**Comment by srbellare** [comment] 2016-07-26 10:30
I'm on the 2.4.1 mintty version and an Azure domain and this is what I'm getting
`Error: could not fork child process: There are no available terminals (-1).`

I hope it helps with the debugging. Thanks!

**Comment by mintty** [comment] 2016-07-26 11:31
I noticed that the diagnostic code I built in is actually not included (blush), because the self-implemented forkpty call was only intended for early cygwin versions.
Can you please enable it for another round of diagnostics with the following patch in line 125 of std.c:
#if CYGWIN_VERSION_API_MINOR < 93 __|| 1__

**Comment by srbellare** [comment] 2016-07-26 14:24
I changed line 125 of std.c from
`#if CYGWIN_VERSION_API_MINOR < 93`
to
`#if CYGWIN_VERSION_API_MINOR < 93 || 1`
and built the executable and this is what I got after
`Error: could not fork child process: There are no available terminals (-2).`

Still not reaching your diagnostic code or did it?

**Comment by mintty** [comment] 2016-07-26 15:44
Yes, it did, thanks. And it indicates that the call
```
open ("/dev/ptmx", O_RDWR | O_NOCTTY)
```
failed. Please report
```
ls -l /dev/ptmx
```
and maybe try to manipulate it.

Please also try with the cygwin test release 2.6.0-0.2 under the vague idea that https://cygwin.com/ml/cygwin/2016-07/msg00275.html could be related.

**Comment by srbellare** [comment] 2016-07-27 06:25
Well.. I didn't try the test release yet but you are right, it seems the permissions are screwed for the fake domain AzureAD. This is what permissions looks like
`Unknown+User@TEST /
$ ls -l /dev/ptmx
crw-rw-rw- 1 Unknown+User Unknown+Group 5, 2 Jul 27 11:46 /dev/ptmx`

When I did a strace whoami I see this
`Unknown+User@TEST /
$ ls -l /dev/ptmx
crw-rw-rw- 1 Unknown+User Unknown+Group 5, 2 Jul 27 11:46 /dev/ptmx`

A similar issue was reported on the cygwin mailing list but no traction
[https://cygwin.com/ml/cygwin/2016-02/msg00046.html](url)

As as I workaround, I have created a local user account on my windows 10 machine and running mintty as that user from the shortcut. In the Target section of the shortcut
`runas.exe /user:<local_computer_name>\<local_user> "C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -"`

It may help someone facing similar issue till this is addressed by cygwin(?)

**Comment by mintty** [comment] 2016-07-27 10:55
Likely `ls -ln /dev/ptmx` would report a different user ID than `id`.

**Comment by Spitzbub** [comment] 2016-07-27 12:47
For what it's worth, mine cygwin install (mintty 2.4.1) reports the same ID:

Unknown+User@Lenovo-PC ~
$ stat /dev/ptmx
  File: '/dev/ptmx'
  Size: 0               Blocks: 0          IO Block: 65536  character
special file
Device: 8e6fb9dh/149355421d     Inode: 327682      Links: 1     Device
type: 5,2
Access: (0666/crw-rw-rw-)  Uid: (4294967295/Unknown+User)   Gid:
(4294967295/Unknown+Group)
Access: 2016-07-27 08:44:11.000000000 -0400
Modify: 2016-07-27 08:44:11.000000000 -0400
Change: 2006-11-30 19:00:00.000000000 -0500
 Birth: 2006-11-30 19:00:00.000000000 -0500

Unknown+User@Lenovo-PC ~
$ id
uid=4294967295(Unknown+User) gid=4294967295(Unknown+Group)
groups=401408(Medium Mandatory
Level),545(Users),4(INTERACTIVE),66049(CONSOLE LOGON),11(Authenticated
Users),15(This
Organization),66048(LOCAL),4294967295(Unknown+Group),262180(Cloud Account
Authentication)

Unknown+User@Lenovo-PC ~
$ cat /dev/ptmx
cat: /dev/ptmx: No such device or address

Unknown+User@Lenovo-PC ~
$ echo > /dev/ptmx
bash: /dev/ptmx: No such device or address

Unknown+User@Lenovo-PC ~
$

**Comment by hcd00045** [comment] 2016-08-01 14:08
Hi,

I also use Azure AD to log into my Windows 10 PC, and I also have encountered this issue when installing cygwin. 

I did find a workaround, though I am not confident in calling it a "fix" because I don't know much about Windows SIDs and I'm not sure what kind of damage this causes. That being said, it has seemingly worked well for months. 

Basically my understanding is that cygwin can't find the information it needs for your account because it's stored in Azure AD and not available using the typical means cygwin uses to find this information. The workaround takes advantage of the fact that cygwin will fall back on its own /etc/passwd (which doesn't exist by default) when looking up user info. To create an /etc/passwd with the right information:

First, look up your SID. From PowerShell:

```
$objUser = New-Object System.Security.Principal.NTAccount("azuread", "$YOUR_USERNAME")
$strSID = $objUser.Translate([System.Security.Principal.SecurityIdentifier])
$strSID.Value
```

Then create a passwd file. From cygwin:

`
mkpasswd > /etc/passwd
`

Edit that File. Add a line like this with the correct values added:

`${YOUR_CYGWIN_USERNAME}:*:297109:297121:${YOUR_WINDOWS_ID},${YOUR_WINDOWS_SID}:${YOUR_CYGWIN_HOME_DIR}:/bin/bash`

FWIW, my Windows ID looks like "azuread\myname". For the 3rd and 4th segments, which appear to be user and group id, I basically just added 100000 to the last entry in the passwd file to make something unique. 

Hope that helps!

**Comment by mintty** [comment] 2016-08-01 20:17
If this is an intrinsic problem with pty handling (which seems to be the purpose of /dev/ptmx), 
it should also be affecting other terminals (like xterm) and maybe ssh.
Can somebody who is affected please test that?
And can somebody who is affected please test with a current cygwin test release?

**Comment by Spitzbub** [comment] 2016-08-01 20:52
I tried with cygwin 2.6.0-0.5 (and mintty 2.4.2-0 - still got "There are no
available termins (-1)") but unfortunately it did not help.

C:\cygwin64>whoami
azuread\russellmora

C:\cygwin64>Cygwin.bat


Unknown+User@Lenovo-PC ~
$ id
uid=4294967295(Unknown+User) gid=4294967295(Unknown+Group)
groups=401408(Medium Mandatory
Level),545(Users),4(INTERACTIVE),66049(CONSOLE LOGON),11(Authenticated
Users),15(This
Organization),66048(LOCAL),4294967295(Unknown+Group),262180(Cloud Account
Authentication)

Unknown+User@Lenovo-PC ~
$ stat /dev/ptmx
  File: '/dev/ptmx'
  Size: 0               Blocks: 0          IO Block: 65536  character
special file
Device: 8e6fb9dh/149355421d     Inode: 327682      Links: 1     Device
type: 5,2
Access: (0666/crw-rw-rw-)  Uid: (4294967295/Unknown+User)   Gid:
(4294967295/Unknown+Group)
Access: 2016-08-01 16:47:11.000000000 -0400
Modify: 2016-08-01 16:47:11.000000000 -0400

Change: 2006-11-30 19:00:00.000000000 -0500
 Birth: 2006-11-30 19:00:00.000000000 -0500

Unknown+User@Lenovo-PC ~
$

Anything else I can get for you?

Cheers,
Russell.

**Comment by mintty** [comment] 2016-08-01 21:08
Yes, thanks, can you please enable the self-made forkpty like I asked above with the following patch in line 125 of std.c:
#if CYGWIN_VERSION_API_MINOR < 93 || 1
but disable the self-made openpty by renaming it in line 190 and adding an include:
#include <pty.h>
int
dont_openpty(int *amaster, int *aslave, char *name,
...

**Comment by Spitzbub** [comment] 2016-08-01 21:57
Looks like the include file name got stripped - what was it?

**Comment by Spitzbub** [comment] 2016-08-01 22:17
Unfortunately because all the permissions are messed up it isn't simple to build.... may take me a while....

```
Unknown+User@Lenovo-PC /cygdrive/c/cygwin64/mintty
$ make
#cd src; make exe
#cd src; make bin
cd src; make
make[1]: Entering directory '/cygdrive/c/cygwin64/mintty/src'
gcc -c -MMD -MP -DTARGET=x86_64-pc-cygwin -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  -fstack-check winsearch.c -o ../bin/cygwin64/winsearch.o
cc1: fatal error: can’t open ‘/tmp/ccXVC1G6.s’ for writing: Permission denied
compilation terminated.
make[1]: *** [Makefile:120: ../bin/cygwin64/winsearch.o] Error 1
make[1]: Leaving directory '/cygdrive/c/cygwin64/mintty/src'
make: *** [Makefile:21: exe] Error 2

Unknown+User@Lenovo-PC /cygdrive/c/cygwin64/mintty
$
```

**Comment by Spitzbub** [comment] 2016-08-01 22:29
OK, figured out the include file was pty.h and got it building using the /etc/passwd work-around mentioned previously. Now what? When I run the new mintty I get the same result (Error: could not fork child process: There are no available terminals (-1)) but only when I remove the /etc/passwd workaround (with the work-around in place the new mintty runs fine)

**Comment by mintty** [comment] 2016-08-02 09:26
Thanks, so that doesn't offer a potential workaround within mintty.
Also permissions seem to be screwed up in general in your environment (/tmp/...);
I've taken the issue to the cygwin mailing list.
For a better picture, it would still be interesting to know whether any other terminal works at all (like xterm).
Also whether the latest test release of cygwin (2.5.0-0.5) makes a difference.

**Comment by mintty** [comment] 2016-08-02 10:07
Please note https://cygwin.com/ml/cygwin/2016-08/msg00018.html (some quotes below) and maybe somebody can cooperate with Corinna to find a cygwin workaround...

> This may be fixable by somebody with such an account and willing to hack on the Cygwin function pwdgrp::fetch_account_from_windows().  There's already some code for the so-called "Windows accounts" which seem to work in a similar fashion (albeit in this case the user has a local account SID).

> Alternatively I need at least a guinea pig with such an account,

**Comment by mintty** [comment] 2016-08-24 12:15
Could be fixed in cygwin 2.6.0-0.9, see https://cygwin.com/ml/cygwin/2016-08/msg00346.html

**Comment by mintty** [comment] 2016-09-02 12:46
Please check and confirm whether this is resolved with cygwin 2.6.0 (just released) so we can close the issue.

**Comment by mintty** [comment] 2016-09-07 11:50
Further information that may be related or not, I don't know: http://stackoverflow.com/questions/2439336/msysgit-sh-exe-fork-permission-denied-vista-64-bit

Anyway, @bcampitf, if cygwin 2.6.0 solves this issue for you, can you close it please?

**Comment by simonjodet** [comment] 2016-09-07 12:22
I can confirm Cygwin now works for me on Windows 10 with Azure AD account.

**Closed** 2016-09-08 07:29 UTC
Labels: help wanted

**Comment by mintty** [comment] 2025-07-25 12:58
This is the wrong place for this report. Please address the cygwin mailing list.

**Comment by mintty** [comment] 2025-08-05 11:53
No mails from "ben" on the list. If you upload or quote the mail text here, I may send it on your behalf.
