### ISSUE TITLE
font display for portable application

### ISSUE THREAD

**Issue by duytrung** [mintty/mintty#1004] opened 2020-05-29 03:34 UTC
Hi,

I have used the Msys2 on USB stick. The mintty display the character incorrectly if I use the Vim with Evervim distribution as these require Knack Nerd font. How to display the font correctly in this case?

![image](https://user-images.githubusercontent.com/2046672/83218250-e06e6700-a1ac-11ea-87d1-c132febc6a89.png)

Should mintty have a font folder for users to put the necessary fonts in there instead of using Windows host font. As some computers do require admin rights to install fonts.

Thank you very much

**Comment by mintty** [comment] 2020-05-29 05:19
Duplicate of #901, see my first comment there.

**Comment by mintty** [comment] 2020-10-16 16:06
Actually, this turned out to be much easier, using Windows function AddFontResourceEx.
Introduced new configuration subfolder `fonts` to drop dynamic fonts.
A portable installation would need to provide its config tree and set it in the invocation via command line parameter `--configdir`.

**Comment by mintty** [comment] 2020-10-24 15:42
Released 3.4.1.

**Closed by mintty** 2020-10-24 15:42 UTC
Labels: duplicate, enhancement
