### ISSUE TITLE
Pressing Enter while in tail -f

### ISSUE THREAD

**Issue by nissan18** [mintty/mintty#805] opened 2018-10-03 13:34 UTC
I'm using GitBash on Windows. While running  `tail -f somefile.log` , I often press Enter to make space in the output. However, when exiting the `tail -f` command using Ctrl-C, those Enter keys are replayed again on the terminal.

**Comment by mintty** [comment] 2018-10-03 13:43
Apparently, `tail -f` does not read keyboard input, so of course the keys are buffered. In any case, this is not a terminal issue.

**Comment by nissan18** [comment] 2018-10-03 14:31
Who should I address this issue to?

**Comment by mintty** [comment] 2018-10-03 15:14
It's not a bug of anything, it's traditional Unix handling of tty/pty input.
However, you could ask for a `tail` feature to swallow such intermediate key strokes.
It's part of the coreutils package which you find "upstream" at gnu.org.

**Comment by nissan18** [comment] 2018-10-03 15:40
I'm sorry if this is not a right place to ask but the commands are buffered how come I see spaces when I press Enter in `tail -f`?
Also, how come the issue only happens on Windows GitBash but not in Unix/Linux shell?

**Comment by mintty** [comment] 2018-10-03 16:32
No idea what spaces you mean.
Testing on one Linux system, it does indeed behave differently. This can have a number of reasons, maybe different pty configuration (`stty`).
Anyway, behaviour is the same in cygwin xterm, for that matter.

**Comment by nissan18** [comment] 2018-10-03 16:37
I meant every time you press Enter while in `tail -f`, it actually shows new empty line on the screen. Then it resumes showing output from `tail -f`. After you exit `tail`, it "runs" those Enter keys again. Only happens in GitBash on Windows afaik.

**Comment by mintty** [comment] 2018-10-03 16:45
The pty is in echo mode. This still buffers keys for input.

**Comment by nissan18** [comment] 2018-10-03 16:47
Is there a way to turn this option on or off?

**Comment by mintty** [comment] 2018-10-03 16:57
`stty -echo`, but then you'll have no echo...

**Comment by avih** [comment] 2018-10-03 17:31
Here's a shorter test case to reproduce. Type this at the shell prompt (and ENTER):
```sh
while sleep 1; do : ; done
```
Then press ENTER three times and then abort with CTRL-C. On both Windows and linux it echoes en empty line each time ENTER is pressed, but only on Windows the shell sees them again after the break (manifested as the prompt appearing 4 times after the break - the normal one plus the three from the ENTER presses).

Interestingly, it _doesn't_ happen for keys other than ENTER, e.g. if you press A three times and break - there's a normal prompt without any A's.

But, if one presses A three times and then ENTER and then CTRL-C, then after the break the shell behaves as if AAA ENTER was entered at the prompt - it tries to execute AAA (and would likely fail).

Initially I thought it's an issue with bash itself on windows, but it also happens with dash. It also happens with cygwin so it's not an MSYS2-specific issue (on which git-bash is based).

> Anyway, behaviour is the same in cygwin xterm, for that matter.

While I didn't test xterm. I did test [st](http://st.suckless.org/) (compiles cleanly on cygwin with x-libs), and the issue happens also with st (with bash or dash).

The only thing common to all the results so far is [underlying] cygwin.

I suggest trying the cygwin mailing list, and link to this issue in your email.

**Comment by mintty** [comment] 2018-10-03 20:08
Thanks; after successful redirection, I'm closing the issue here.

**Closed by mintty** 2018-10-03 20:08 UTC
Labels: invalid

**Comment by avih** [comment] 2018-10-03 20:47
For the record, interestingly, it _doesn't_ happen with cygwin in a `cmd.exe` window (running `Cygwin.bat` instead of the `Cygwin64 Terminal` shortcut).

It seems that inputs are completely ignored with the same test case (`while sleep 1; do : ; done`) - nothing is echoed at the terminal when pressing A or ENTER, and the shell doesn't see anything extra after CTRL-C, and also nothing extra is printed.

If instead I use `while read x; echo $x  ; done` (with the `cmd.exe` window) then inputs are echoed, and the line is printed in again on ENTER (i.e. as expected), and everything is fine after CTRL-C.

However, with the `read x` loop, if I press A few times and then CTRL-C (without ENTER), then these A's appear as already-entered input at the shell prompt (and pressing ENTER will execute it as a command).

With mintty this case is fine and same as linux (while read x..., press AAA (no-enter) then CTRL-C). A's are echoes while pressed, re-echoed on enter, and CTRL-C with or without first pressing enter gets back to a clean shell prompt with no extra A's.

If I run the st x-terminal from the cygwin cmd.exe window (without any mintty instances running) - then the original issue still happens.

So it's definitely unrelated to mintty, but interesting that it doesn't happen with cmd.exe .
