### ISSUE TITLE
altgr+space opens context menu

### ISSUE THREAD

**Issue by davidnorthetal** [mintty/mintty#790] opened 2018-08-27 11:51 UTC
Hey,

on a german keyboard typing a pipe in a shell can cause me to accidentally close the whole window among other random stuff.

The issue is that `altgr+space` opens some sort of context menu for the window, which can happen if I remain on altgr, which is necessary for pressing the pipe on a german keyboard.

Is this necessary? - I don't know of any terminal emulator that behaves this way and I don't know of a windows application either that would have this binding.

Thanks for any response.
Dnorth

**Comment by mintty** [comment] 2018-08-27 12:45
It's the window menu ("SystemMenu"), not the context menu. Opening it with Alt+space is intended by design. Opening it also with AltGr+space is an unintended side effect. I'll look into this.
Inadvertent closing from the window menu could also be prevented by removing the "c" shortcut from its menu entry. Is that desirable?

**Comment by davidnorthetal** [comment] 2018-08-27 13:35
If I'd be in a position to wish something I'd not want to have the menu open at all because I don't intend as such and it swallows whatever I was intending to type anyway.

I have little defense for my workflow except that it just never seemed to matter so I apparently didn't bother much in my typing to relase my `altgr`-key in time often before hitting `space` and such it is ingrained in my brain.

If it's unintended ontop I'd be extremely pleased if this would be removed.

**Comment by mintty** [comment] 2018-09-20 11:54
Released 2.9.1.

**Closed by mintty** 2018-09-20 11:54 UTC
