### ISSUE TITLE
error ELIFECYCLE errno 3221225786 on ctrl-c in node/express/npm w/ mintty 2.8.5

### ISSUE THREAD

**Issue by jamessouth** [mintty/mintty#788] opened 2018-08-12 20:07 UTC
I haven't been able to find much applicable information about this error but I believe I have narrowed it down to mintty, or perhaps git, since changing node/npm versions didn't fix.  To reproduce:

1. start a simple node project
2. install express
3. my js file is:
```javascript
const express = require('express');
const app = express();
app.get('/', (req, res) => {
  res.send('hello');
});
app.listen(3000, () => {
  console.log('running on port 3000');
});
```

With mintty 2.8.5 when I stop the server with CTRL-C, I get the ELIFECYCLE error with code 3221225786.  I tried this in node 8.11.3 and 8.10.0, npm 6.3.0 and 5.6.0, express 4.16.3, got the error in all cases, UNTIL: rollback to mintty 2.7.3, no more error.  So, it seems something introduced since 2.7.3 is causing this.  I have seen some discussion of what seem to be similar issues but I don't know how related they are.  Also, FWIW, I did NOT get this error in Windows Command Prompt.

**Comment by mintty** [comment] 2018-08-12 21:28
This is not the place to analyze 'node' behaviour. If you think there is a root cause in mintty, please narrow the issue down to it and provide a reproducible test case. If you mention "similar issues", at least refer to them. Why do you expect this project to invest guesswork for third-party problems?

**Comment by mintty** [comment] 2018-08-12 21:59
And if you think you need to blame mintty without any evidence, you should at least care to identify the release update which makes a change for you, and check the change log for hints. There are a dozen releases between the two mentioned ones.

**Comment by jamessouth** [comment] 2018-08-13 02:13
OK, I haven't been through them because I don't know anything about building from source, I would need to find some instructions, BUT! - I do still have the installer for Git for Windows 2.16.2, which comes with mintty 2.8.4, and I *cannot* reproduce the error!  When I swap that out for GfW 2.18.0 and mintty 2.8.5, I get the error.

**Comment by mintty** [comment] 2018-08-13 06:02
As 'node' is a Windows native program, there are unresolved incompatibilities with respect to pty input (esp. "raw" input), character set, and signal handling. Why this changes from mintty 2.8.4 to 2.8.5, however, is puzzling, and we may try to analyze it.

First, following https://github.com/nodejs/node/pull/16104#issuecomment-335254130, can you try to wrap 'node' into that script, please, in order to get winpty involved?

Another interesting hint is https://github.com/git-for-windows/git/issues/1219#issuecomment-312089597:
> The way Ctrl+C is handled in Git for Windows changed recently, indeed.

It would be interesting to test with mintty 2.8.5 on the older Git for Windows release, or 2.8.4 on the newer one. Unfortunately, Git for Windows makes it deliberately hard to install a development environment, so self-compiling mintty may be a challenge... Can you, by any chance, reproduce the issue in cygwin?

On the other hand, as a cross-check, nodejs/node#4182 suggests similar problems occur in other environments as well, mintty not involved.

**Comment by mintty** [comment] 2018-08-16 07:54
You could also enable me to test the issue by providing a reproducible test case, including all necessary binaries.

**Comment by mintty** [comment] 2018-08-19 04:01
Thanks, and with mintty 2.8.5 in that environment? There was a change concerning exit codes (actually start error exit indication).
To install it from Cygwin Setup: change View (top left) to "Category", open category "Base", find the mintty entry, and click in the "New" column to 2.8.4 or 2.8.5. You could make a copy before (cp /bin/mintty /bin/mintty290) to have multiple versions available at the same time for comparing testing.

**Comment by jamessouth** [comment] 2018-08-23 01:49
with:

npm 6.4.0
node 8.10.0
mintty 2.8.4

I cannot reproduce the error.

**Comment by jamessouth** [comment] 2018-08-23 01:55
with:

npm 6.4.0
node 8.10.0
mintty 2.8.5

I cannot reproduce the error.

**Comment by mintty** [comment] 2018-09-21 11:58
Closing as I don't have the impression there is a problem anymore...

**Closed by mintty** 2018-09-21 11:58 UTC
Labels: invalid
