### ISSUE TITLE
Various interactive Windows programs fail to receive input while reading from pipe

### ISSUE THREAD

**Issue by FrostKiwi** [mintty/mintty#1210] opened 2023-04-10 06:07 UTC
I have found multiple commands in multiple setups, that fail to work with a well known symptom around MinTTY: No Inputs. All of the following works Alacritty, but not on MinTTY. Setup is: Windows 10, MSYS2 environment. Same result for MinGW64 environment or the simple MSYS2 one.

- `FZF` when accessed through `ZSH` and it's `FZF` plugin: https://github.com/unixorn/fzf-zsh-plugin.
  - Normal fzf works
  - If Pressing `CTRL+R` to access the `ZSH` history via the `FZF` interface, the interface displays, but arrows keys or any other inputs work. MinTTY sometimes even fails to exist the command, as not even `CTRL+C` works
  - Works in Alacritty just fine (Alacritty can be used to access MSYS2 the same way MinTTY can do it)
- `fx` (https://github.com/antonmedv/fx) doesn't work at all with MinTTY
  - It loads successfully, but not input works. No arrowkeys, no letter keys
  - Works just fine in Alacritty
  
Any idea as to why? How can I provide useful debug info?

**Comment by mintty** [comment] 2023-04-10 07:28
Which MSYS version do you run? (`uname-a`)
Is ConPTY support enabled? (`echo $MSYS`)

**Comment by mintty** [comment] 2023-04-10 07:38
Do you use the Windows version of fzf? (`type fzf`)
Duplicate of #1105 and #941.

**Comment by FrostKiwi** [comment] 2023-04-10 07:39
> Which MSYS version do you run? (`uname-a`) Is ConPTY support enabled? (`echo $MSYS`)

MSYS2 Version: `uname -a` result: `MINGW64_NT-10.0-19045 DENB-2108033 3.4.6.x86_64 2023-04-01 11:43 UTC x86_64 Msys`
I have `ConPTY=on` in my `.minttyrc`. Result of `echo $MSYS` is `enable_pcon` with MinTTY and empty with Alacritty.

**Comment by mintty** [comment] 2023-04-10 08:06
> type fzf results in /mingw64/bin/fzf

Which means it's not a native cygwin/msys package as it is located in the mingw branch. `pacman -S fzf` fails.
The cygwin package of fzf works, see #941.

**Comment by mintty** [comment] 2023-04-10 08:40
Yes, cygwin fzf is a Ruby script, so maybe something different.
Anyway, fx does not install for me ("Unsupported OS") and fzf installation seems like a bigger issue.
The question in #941 about how to install that tool remained unanswered and I cannot analyse this issue further without a reproducible test case.

**Comment by FrostKiwi** [comment] 2023-04-10 08:47
> Yes, cygwin fzf is a Ruby script, so maybe something different. Anyway, fx does not install for me ("Unsupported OS") and fzf installation seems like a bigger issue. The question in #941 about how to install that tool remained unanswered and I cannot analyse this issue further without a reproducible test case.

`fx does not install for me ("Unsupported OS")`
Yeah, the installer script does not recognize MSYS. Here is the windows package directly: https://github.com/antonmedv/fx/releases/download/24.1.0/fx_windows_amd64.exe Putting that into a place where MSYS2's `PATH` can see, let's you call that tool. Work perfectly fine with Alacritty, but MinTTY fails.

Regarding the specific reproducible test case for fzf: Install ZSH, git clone the fzf-plugin repo and simply add to the .zshrc according to https://github.com/unixorn/fzf-zsh-plugin#without-using-a-framework . Finally, launch the command history via Ctrl+R. Now it fails with MinTTY, but still works with Alacritty.

**Comment by mintty** [comment] 2023-04-10 09:30
The fx tool (apparently a JSON viewer) works for me in MSYS.
The fzf does not but ("illegal option: --height" and beeps on ^R).
Alacritty is a native Windows program, so maybe there is still some gap in the cygwin ConPTY support to bridge the worlds.

**Comment by FrostKiwi** [comment] 2023-04-10 09:39
> The fx tool (apparently a JSON viewer) works for me in MSYS.

Can you define "works"?
It opens up, but none of the keys work. If you open a .JSON file you cannot select entries, expand collapse etc. all keys are just ignored...

**Comment by mintty** [comment] 2023-04-10 09:48
It displays JSON, navigates, collapses on cursor-left, quits on q.

**Comment by FrostKiwi** [comment] 2023-04-11 00:55
> It displays JSON, navigates, collapses on cursor-left, quits on q.

@mintty 
Figured it out! It's the pipes! 

With `fx`, the keys, when reading from a file works. But that is not the main use-case for `fx`. It is inspecting the JSON output of a command. 
Try this: `curl -s https://api.openai.com/v1/chat/completions -H 'Content-Type: application/json' > test.json; fx test.json` and compare to `curl -s https://api.openai.com/v1/chat/completions -H 'Content-Type: application/json' | fx`

Same for `fzf`. Just `fzf` works. But `find | fzf` fails! It starts up, but input is all broken and stuff. (Talking about the newest fzf from the package manager)

**Comment by FrostKiwi** [comment] 2023-04-11 08:26
Great to have finally narrowed down the cause.
> Please report this to the cygwin mailing list as a special gap of either pipe or ConPTY support.

Reported here: https://cygwin.com/pipermail/cygwin/2023-April/253424.html

**Comment by FrostKiwi** [comment] 2023-05-08 05:38
https://github.com/ellie/atuin Is another candidate, that doesn't work. Installs fine on MSYS2, runs perfectly with ZSH, works when accessing the MSYS2 environment via Alacritty, but fails with MinTTY.

**Comment by mintty** [comment] 2023-06-18 11:29
The issue has been addressed in cygwin 3.4.7.

**Closed** 2024-02-25 17:34 UTC
Labels: invalid, question
