### ISSUE TITLE
gdb from MSYS doesn't work properly with mintty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#380] opened 2015-06-04 13:04 UTC
```
What steps will reproduce the problem?
1. Run MSYS using mintty shell.
2. Run gdb and try to use readline shortcuts, e.g. navigate the history with 
arrow keys or Ctrl+R search.

What is the expected output? What do you see instead?
Arrow keys don't change the prompt to commands from history but move the cursor 
around the screen. Gdb interprets the input wrongly and it "hangs": pressing 
enter will not cancel the input and will repeatedly give error: Undefined 
command: "".
Ctrl+R moves cursor to next line, but is otherwise ignored - entering text will 
be interpreted as command.
Other readline shortcuts like Ctrl+W or Ctrl+K don't work either.

What versions of mintty, Cygwin/MSYS, and Windows are you using?
mintty 1.1.2 for MSYS, MSYS - latest packages retrieved on 2013-03-24 (gdb 
version is 7.5) , Windows XP SP3

Please provide any additional information below.
Everything works as expected under MSYS's default shell.
```

Original issue reported on code.google.com by `piot...@gmail.com` on 24 Mar 2013 at 7:06

**Comment by mintty** [comment] 2015-07-30 13:23
As rpjohnst reported, this seems to be an interoperability problem between MSYS and MinGW.
Maybe the readline library does not work for MinGW applications in an MSYS environment using a pty terminal?
I would appreciate if this could be tested with a different terminal on MSYS, but unfortunately there does not seem to be one.
Nonetheless, I do not think this is a mintty issue and I'm feeling inclined to close it.

**Comment by html1** [comment] 2015-09-09 14:36
same issue with arm-none-eabi-gdb  7.8.0.20150604-cvs

**Comment by newKingg** [comment] 2015-09-16 11:37
@mintty I think it mintty related. When you are running wget or "pacman -Syu", meanwhile press "Up key", you will see somethings mess up.

**Comment by mintty** [comment] 2015-09-16 12:16
"somethings mess up" isn't very specific. I suppose you mean that the cursor goes up. Well, that's basically the function of the Up key. The issue here is what happens if you type input while the application isn't listening to input.
While in many environments keys will be buffered silently, in some they are also echoed right away. This does not only occur in mintty. It is caused by handling of tty/pty input somewhere in the system and it's no evidence of any bug in the terminal.

**Comment by mintty** [comment] 2015-09-16 12:47
The confusion here is the distinction between MinGW and MSYS environments.
If you build an application for MinGW, it is basically a Windows application. Running it in a POSIX environment (e.g. MSYS) is bound to cause problems, the most apparent being the inability to interact with a pty-based terminal as expected, or to recognize terminal control sequences.
The same problems occur if you run Windows command-line applications in a Cygwin terminal (see #56). Maybe someone will eventually come up with a working trick to bridge the two worlds (initial attempts for cygwin are available but no generic solution yet) but for now people will have to live with it.
The problem is shared with xterm and all other such terminals. Again: it is not specific to mintty. Closing issue.

**Closed by mintty** 2015-09-16 12:47 UTC

**Comment by mintty** [comment] 2015-11-09 15:36
Referring to my comment of 30 Jul:

> I would appreciate if this could be tested with a different terminal on MSYS, but unfortunately there does not seem to be one.

Actually, there is one: rxvt.
Cross-testing this with rxvt reveals the same unpleasant behaviour.
Which confirms that this is not a mintty issue. Staying closed, sorry.

**Comment by mintty** [comment] 2019-12-16 23:45
Cygwin 3.1.0 has been released with ConPTY support.
