### ISSUE TITLE
git bash not opning using window 7

### ISSUE THREAD

**Issue by MuhammadUmair321** [mintty/mintty#1024] opened 2020-07-22 18:37 UTC
Exception: STATUS_ACCESS_VIOLATION at eip=000D0424
eax=00000000 ebx=0045028B ecx=0022C5CC edx=76E064F4 esi=004A0410 edi=80000000
ebp=0022CB48 esp=0022C614 program=C:\Program Files\Git\usr\bin\mintty.exe, pid 788, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CB48  000D0424 (20060D98, 20060DA2, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace

**Comment by mintty** [comment] 2020-07-22 18:47
Duplicate of 
1014, see https://github.com/mintty/mintty/issues/1014#issuecomment-645220269.

**Comment by k-takata** [comment] 2020-07-29 01:22
Git for Windows 2.28.0 is now available, which comes with mintty 3.2.0.
I think this can be closed now.

**Comment by mintty** [comment] 2020-07-29 12:37
Thanks for the notice.

**Closed by mintty** 2020-07-29 12:37 UTC
