### ISSUE TITLE
DirectWrite support with selection of hinting mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#430] opened 2015-06-04 13:05 UTC
```
Will be nice to have DirectWrite support, whiche give possibilty to select font 
hinting. This give fonts (mostly non-windows native) better feel.
```

Original issue reported on code.google.com by `nsho...@gmail.com` on 11 Jun 2014 at 9:38

**Comment by gcollombet** [comment] 2015-08-04 12:49
I'll try to do it!

**Comment by mintty** [comment] 2015-08-04 12:56
Great proposal! I had checked myself and found the API to be so specific that someone enthusiastic about this issue is needed to do it...
How does this actually relate to #438? Is that part of DirectWrite or something different; could it be combined or is it an alternative?

**Comment by gcollombet** [comment] 2015-08-04 13:03
Ok, I'll take a look too

**Comment by mintty** [comment] 2016-07-14 16:49
I'd rather use Uniscribe which does not seem to have an API as insane as DirectWrite and may be supporting sufficient rendering features.

**Comment by mintty** [comment] 2016-12-04 21:52
Release Uniscribe support in 2.7.1.
I don't think DirectWrite would now still bring much value-add, so I'm closing this issue.

**Closed by mintty** 2016-12-04 21:52 UTC
Labels: Difficulty-Insane, help wanted

**Comment by fcharlie** [comment] 2017-06-10 12:25
@mintty is Uniscribe Support more Emoji or Color Font ?

On Windows 10 1607 ,DirectWrite Support  color fonts and more font set
https://msdn.microsoft.com/en-us/library/windows/desktop/hh802480(v=vs.85).aspx

![emoji](https://pic2.zhimg.com/46a11a7e2b1abea11a36b5987d81fcd9_r.png)

**Comment by mintty** [comment] 2017-06-10 12:29
Not sure what you mean. Emojis are displayed if they are included in your font, or in a fallback font that Windows finds via Uniscribe. I don't think Uniscribe supports colour fonts.

**Comment by fcharlie** [comment] 2017-06-10 12:35
@mintty I suggest mintty use DirectWrite.
Windows console is planning to use Directwrite to render its font


https://github.com/Microsoft/BashOnWindows/issues/75#issuecomment-304415019

**Comment by mintty** [comment] 2017-06-10 20:18
Which benefit would DirectWrite have that Uniscribe cannot offer (other than fancy colour icons which are not really a traditional terminal feature)?

**Comment by nelix** [comment] 2017-09-05 04:36
Ligatures and a more user friendly experience when trying to do things like powerline...
Windows is always a huge edge case for people who make fonts or terminal apps/themes, most editors and browsers are using directwrite, there is no terminal on windows besides those based on Electron (... lots of memory) that support these things...

**Comment by mintty** [comment] 2017-09-05 08:37
@nelix, you are addressing quite different issues; for DirectWrite, my previous question still remains unanswered; ligature support could be added without it if only I knew how to get at the font ligature information; and powerline is a completely different thing, it's about character width handling and has been discussed elsewhere.

**Comment by mintty** [comment] 2018-01-23 23:25
@fcharlie: The current repository upload provides full emoji support.

**Comment by fcharlie** [comment] 2018-01-23 23:35
@mintty Good news, once I have the time, I'll test it.

**Comment by fcharlie** [comment] 2018-01-23 23:51
No matter what font I use, the four-byte Emoji display is not normal.
 
![image](https://user-images.githubusercontent.com/6904176/35306916-31a1d32a-00db-11e8-997d-0fbc8186f0a0.png)

**Comment by mintty** [comment] 2018-01-24 07:27
Please check the wiki/Tips.md file from the repository for advice how to deploy actual emoji data.
It's not yet online (because it describes unreleased features). I could place it online with a note if needed.
The screenshot does not exhibit the new emoji feature, it just displays emoji symbols from the font.

**Comment by mintty** [comment] 2018-01-24 07:34
![mintty-emojis](https://user-images.githubusercontent.com/12740416/35319724-57b542d0-00e1-11e8-8eb3-07efe87728b9.png)

**Comment by fcharlie** [comment] 2018-01-24 08:20
@mintty Good. That little flag looks wider than the others?

**Comment by mintty** [comment] 2018-01-24 10:38
The width of an emoji is determined by the defined widths of its component characters, so it may actually have any width between 1 and 8 character cells. Also depends on option `Charwidth=unicode`.

**Comment by mintty** [comment] 2018-01-24 10:39
To tweak the resulting streching effect, there is also option `EmojiPlacement`.

**Comment by fcharlie** [comment] 2018-01-24 10:44
@mintty Thanks.

**Comment by mintty** [comment] 2018-01-24 11:16
@fcharlie, do you have an idea where the actual emoji data are stored in Windows?
If they are available as a resource, mintty could support at least Windows-style emojis out-of-the-box, without any additional deployment.

**Comment by fcharlie** [comment] 2018-01-24 12:58
@mintty Sorry, I don't known. But You can set the Emoji font to **Segoe UI**. But the GDI rendering Emoji has no `Direct2D` effect. Direct2D support `D2D1_DRAW_TEXT_OPTIONS_ENABLE_COLOR_FONT` (Windows 10  Creators Update or Later).

Right Direct2D:

![image](https://user-images.githubusercontent.com/6904176/35333294-2c319538-0149-11e8-861b-886e12ea902f.png)

That's why I suggest you use direct2d rendering.

**Comment by fcharlie** [comment] 2018-01-24 14:20
It looks blurry when the font size is small, and it has a bit of delay (or Resize)
![capture20180124221857838](https://user-images.githubusercontent.com/6904176/35336911-c6bb462a-0154-11e8-88e4-e18a0f79ef67.png)

![capture20180124221907842](https://user-images.githubusercontent.com/6904176/35336923-cd34ce68-0154-11e8-908d-9d41793abfbf.png)

**Comment by mintty** [comment] 2018-01-24 15:15
At small sizes, everything will eventually look blurry...
Emoji display is delayed and slow, I don't know why...

**Comment by mintty** [comment] 2018-01-24 15:32
How about `echo -e '\U1F604'` for a more intuitive test case?

**Comment by fcharlie** [comment] 2018-01-24 22:33
The same `echo -e '\U1F604'` display is delayed. PNG emoji scaling without SVG or font effect。

**Comment by mintty** [comment] 2018-01-25 07:33
The echo format was just about the test case to write the same output.
Yes, emoji graphics are used in pixel format (png, jpg or gif would work too);
the MS API does not support loading SVG. Also most actual emoji data repositories provide PNG, not SVG.

**Comment by fcharlie** [comment] 2018-01-25 09:21
[SVG Support](https://msdn.microsoft.com/en-us/library/windows/desktop/mt790715(v=vs.85).aspx)  Windows 10 Creators Update or Later and **Direct2D only**

**Comment by mintty** [comment] 2018-01-25 10:16
Mintty currently displays emojis using image functions, not via a font.
See `GdipLoadImageFromStream` and `GdipLoadImageFromFile` in winimg.c.
I can check again whether those accept SVG now, so it could be used.

**Comment by pandasauce** [comment] 2019-11-25 16:38
As I switched from Ubuntu/Terminator to Windows/ConEmu to Windows/mintty I kept wondering why the rendering looked off in mintty. Then I discovered that mintty supports both GDI and Uniscribe, but not DirectWrite, which would explain why it renders text so differently compared to other software. Same font sizes are rendered differently and letter spacing in particular looks odd.

**Comment by mintty** [comment] 2019-11-25 18:27
Fixed-width display of characters is even by the nature of a cell-based terminal, not odd :)
No idea how to interpret this fuzzy comment.

**Comment by pandasauce** [comment] 2019-11-26 18:52
Actually, this might have something to do with size calculation. It's almost as if mintty uses smaller cells than glyph size from the settings and it squishes the characters together a bit to compensate - does this make any sense?

I will have to play around with this a bit once I have the time. ConEmu calculates sizes differently (try setting 18 there and in mintty) so it might just be that the equivalent of 18 in ConEmu is something like 13.4 in mintty, which can't be set anywhere outside of Sublime Text as far as I know.

**Comment by mintty** [comment] 2019-11-26 19:03
Mintty does not "squish" characters. Unless you use option `ColSpacing`, the font is configured to use the full cell width. Row width may be adjusted according to font information ("internal leading") which is a typographic advice that mintty properly follows.
The size comparison sounds like ConEmu uses pixel size while mintty uses point size (or "logical coordinate units" in Windows terms). Point size makes more sense as it scales with DPI.

**Comment by assiless** [comment] 2021-09-21 16:11
> @mintty is Uniscribe Support more Emoji or Color Font ?
> 
> On Windows 10 1607 ,DirectWrite Support color fonts and more font set
> https://msdn.microsoft.com/en-us/library/windows/desktop/hh802480(v=vs.85).aspx
> 
> ![emoji](https://camo.githubusercontent.com/40781bb0a8dc6e00101422a9b9d0ad3a21fe3071f83ec0bebc9951931d58426b/68747470733a2f2f706963322e7a68696d672e636f6d2f34366131316137653262316162656131316133366235393837643831666364395f722e706e67)

What app is this?please

**Comment by assiless** [comment] 2021-09-22 21:22
> Noto Color Emoji cannot be installed in Windows as a font?
there is  [Windows Compatible](https://t.me/rkbdiemoji/100)

**Comment by mintty** [comment] 2021-09-22 22:44
... which failed to install for me too, a while ago; and I'm certainly not going to open something as suspicicious as a "Telegram link".

**Comment by assiless** [comment] 2021-09-23 17:14
>suspicicious as a "Telegram link".

fair enough.
the font in "Telegram link" is renamed to Segoe UI Emoji to replace windows Segoe UI Emoji with Noto Color Emoji
you can use "not suspicicious link" [googlefonts/noto-emoji](https://github.com/googlefonts/noto-emoji/tree/main/fonts)

remark: "googlefonts/noto-emoji/NotoColorEmoji_WindowsCompatible.ttf" file named Noto Color Emoji not Segoe UI Emoji
therefore it will not replace windows Segoe UI Emoji and you will not see the effect
to rename it use [fontname.py](https://github.com/chrissimpkins/fontname.py) 
remark: backup the original  SegoeUIEmoji.ttf before you install it

**Comment by mintty** [comment] 2021-09-23 19:52
OK, that font is installed already (had forgotten); the problem is a failed Windows design decision, at the cost of developers. When they introduced color fonts, they should have been made available for all font APIs but rather they are only available with the by far most complex of those APIs, which does not foster the usage of color fonts.
