### ISSUE TITLE
Slow rendering of unicode replacement character

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#1145] opened 2022-02-24 14:34 UTC
The rendering of unicode is very slow in mintty. Just cat a random binary for proof. I wonder if it's related to the unicode width lookup?

It might be an option to allocate 16384 bytes of memory to allow O(1) access to the first 65536 unicode characters with a lookup table.

As far as I can tell only 2 bits per character would be needed.

It's possible to further compress a lookup table.

https://github.com/apankrat/notes/tree/master/fast-case-conversion

**Comment by mintty** [comment] 2022-02-24 18:29
There were rendering issues with non-BMP characters which have been fixed meanwhile.
Apart from that, mintty rendering is faster or even much faster compared to many other terminals and you would have to demonstrate your claim and describe which terminal you compare with and how you measure speed.
Also the purpose of your proposed lookup is obscure; mintty stores Unicode characters internally and passes them to Windows for rendering.

**Comment by BrianInglis** [comment] 2022-02-24 19:00
There are descriptions of recent Windows slowdowns, presumably from recent upgrades or patches, addressed in February patches, if you have not yet allowed them to be applied (I may be seeing the symptoms, and am waiting to see whether there are reports they are addressed in the patches). 
What's your situation?

**Comment by scandum** [comment] 2022-02-24 22:07
I made sure to update to the latest mintty (3.5.3). It does appear to run a bit faster now, about 5 seconds to cat a 528K binary file on WSL. My main issue is with unicode graphics rendering, but I assume the two issues are related and this is easy to reproduce.

Using PowerShell 7.1.4 the same operation takes less than a second.

Looking at xcwidth() the lookup is slightly suboptimal, assuming that does what I think it does. It's hard to say if it matters without running some benchmarks, my best guess would be that it accounts for 0.1 seconds on a million lookups, so it's most likely a rendering issue.

You could add a 160 byte lookup table for ascii 0 to 159 for xcwidth, you already got "combining.t" after all, but I'll leave that up to you since it wouldn't accomplish much.

**Comment by mintty** [comment] 2022-02-25 08:51
What's your cygwin version (`uname -a`)?
This is certainly not easy to reproduce, please provide a test file. PowerShell is not a terminal but I could assume you run it in its implicit Windows Terminal (could also be run within mintty or from the legacy cmd console). Again, a test case is needed (assuming `type file` otherwise).
Function xcwidth does have an ASCII shortcut (no lookup < 0x7F). It cannot be expanded to 0xFF because some of those characters have ambiguous width.
I'm repeating myself, actual rendering is done by Windows, not mintty.

**Comment by mintty** [comment] 2022-02-25 17:44
Despite missing cooperation to identify the issue, I think I found something. It's likely just about the replacement character that's used instead of rendering invalid characters, not Unicode rendering in general. Changed title accordingly.

**Comment by BrianInglis** [comment] 2022-02-25 17:44
ISTR a number of the `mintty` updates were to tweak width handling because *Windows* default rendering was bad, so `mintty` may be tweaking output per character (@mintty ?), where `PS` just dumps lines to the *Windows* renderer, so you can expect anomalous width renderings there, but they are done fast. ;^> 
This matters to the ~15/16 (~7.5/~8 billion) non-native-English users out there! 
Dumping huge binary files to terminals is never a good idea, or a fair test of anything other than how robust the input processing is: there are multiple levels of interpretation looking at many random characters and performing the appropriate actions. [Some testers I worked with picked some huge sys file from the *Windows* root dir as their first input test for any program, then some other random text file that came with the system!]
I think a fairer comparison might be to have `PS` list a (syntax highlighted and coloured) program vs run e.g. `time source-highlight --failsafe --infer-lang -f esc --style-file=esc.style -i` on the same file or another type of comparable size. 
It takes about 3.5s to render a 2MB .h or 30s for a 6.6MB on my system with current W10 Home, *Cygwin*, `mintty`.

**Comment by scandum** [comment] 2022-02-25 18:07
I can post the file, but I suspect the problem is indeed with replacement characters, which seem abundant in the output I'm seeing.

It's indeed the recent Windows Terminal I'm comparing against.

**Comment by mintty** [comment] 2022-03-25 18:23
Released 3.6.0.

**Closed by mintty** 2022-03-25 18:23 UTC
