### ISSUE TITLE
Disable zooming when resizing with shift

### ISSUE THREAD

**Issue by Efreak** [mintty/mintty#618] opened 2016-12-24 21:05 UTC
I have an action bound to <kbd>shift</kbd>+resize* actions. I could change these settings, but I would prefer to leave them enabled, and to disable zooming entirely in MinTTY; it's not something I need, and the hotkey only conflicts with MinTTY. Disabling the zoom setting in options only disables the <kbd>ctrl</kbd>+<kbd>+</kbd>/<kbd>-</kbd>/<kbd>0</kbd> hotkeys, not the shift modifier.

*specifically, I have a DisplayFusion feature enabled that normally maximizes to fill *most* instead of *all* of the screen; this is disabled by holding shift. Shift is also used to bypass the window snapping feature.

**Comment by mintty** [comment] 2016-12-29 16:44
There are a number of zooming-related configuration options available, not all of them appear in the Options dialog. Please check the manual page http://mintty.github.io/mintty.1.html whether one of them achieves what you want (and report back here).

**Comment by mintty** [comment] 2017-01-02 20:07
Are the available options sufficient so we can close the issue? Otherwise please describe *precisely* which actions are currently handled in an unsuitable way for you and which handling you would prefer.

**Closed** 2017-01-09 11:45 UTC

**Comment by mintty** [comment] 2018-10-04 10:14
ZoomFontWithWindow=no (since 2.2.1).

**Comment by kkuhle** [comment] 2019-03-27 21:10
I've been trying to work around this behavior.  I use a windows management tool where I define regions for windows to snap into.  When I want to override the regions and maximize to full screen, I have to hold shift (shift + alt + enter).  The ZoomFontWithWindow=no ZoomFontWithWindow=false do not avoid this behavior (I believe the documentation indicates this).

Is there any way to prevent this behavior?  I typically do not want this zoom behavior and would like to be able to use the window management application along with mintty and not have my font size changing when I maximize the window.

**Comment by mintty** [comment] 2019-03-28 08:55
The manual explicitly mentions this as an exception to ZoomFontWithWindow:
> If this option is set to false, implicit font zooming coupled with window zooming by the Shift key is disabled, except for the keyboard zoom functions Shift+Alt+Enter/F11 and the Shift+menu function.

There was some technical reason for this, it somehow did not work. I'll look into it. If it works, I could also offer Control to override Shift-Zoom dynamically rather than the static option, so that Control+Shift+Alt+Enter would not zoom. Would that make sense?

**Comment by kkuhle** [comment] 2019-03-28 15:59
Thanks for looking at this.

I was excited to find the option, but then read the documentation more closely when it was not working and realized it was not applicable to what I was trying to accomplish as you pointed out above.

If you can get it a different keyboard combination (Control+Shift+Alt+Enter), I would be happy with that.

**Comment by mintty** [comment] 2019-03-29 13:57
The ZoomFontWithWindow=false option was actually a workaround form some people using specific hotkeys (cf. #476) and the "exception" with Shift+Alt+Enter was intended to allow them to still scale the font for full-screen if they want. So I guess the overriding effect of Shift over the option should be kept.
(Although ZoomFontWithWindow could also have a stronger value range, like yes/no/never.)
Control to "back-override" Shift will be available in any case. It's tricky to test all kinds of conceivable side-effects of such a change, that's why it didn't get into 3.0.0.

**Comment by kkuhle** [comment] 2019-04-16 21:50
That makes sense.  This has been bothersome for me for quite some time.  I have requested the devs of the window management app (display fusion) to provide a different option for the shortcut key so shift doesn't interfere, but I'm not sure when/if that will be possible.  If you can implement something that I can work around this in mintty, it would be appreciated!

**Comment by mintty** [comment] 2019-04-17 06:01
I have in fact uploaded a tweak already (apparently forgot to refer to this issue):

Window handling
  * Revised/fixed fullscreen/font zooming behaviour and effect of ZoomFontWithWindow.
  * Fixed Default Size function in some cases after previous fullscreen zooming.

If you want to try this change before the next release, you may compile the repository version yourself.
