### ISSUE TITLE
Whitespace injected at random

### ISSUE THREAD

**Issue by bakoontz** [mintty/mintty#1075] opened 2020-12-23 22:16 UTC
New install of Cygwin in Windows 10, seeing some odd behavior with random whitespace being injected into output lines:

[ERROR] Re-run Maven using the -X switch to enable ful                 l debug l
ogging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAV
EN/DependencyResolutionException

Strangely, redirecting to a file doesn't show the same behavior.

I've tried different emulations, problem remains.

mintty 3.4.4 (x86_64-pc-cygwin)

**Comment by mintty** [comment] 2020-12-23 22:43
This description of a supposed behaviour is very fuzzy - at best. Nothing reproducible anyway.
Certainly mintty does not "inject" any whitespace. If you want a comment on some phenomenon, describe it. Best thing is to provide a file which, when output with cat, demonstrate your issue.

**Comment by bakoontz** [comment] 2020-12-23 23:23
> Nothing reproducible anyway.

Oh I'm sure you tried.  [ConEmu](http://conemu.github.io) renders console output correctly.  Even cmd.exe renders correctly (although using cmd.exe is pure torture).

> Certainly mintty does not "inject" any whitespace.

Of course not.  That's why I suppose every other term I tried didn't seem to have this problem.

> Best thing is to provide a file which, when output with cat, demonstrate your issue.

Had you actually read my issue, you would know why there's not a file attached.

But whatever.

**Comment by mintty** [comment] 2020-12-23 23:30
Your description does not even show any commands that would be run. It does suggest however to run Maven, which I don't. That's not a bug report. Yet I do in fact have an idea what might be happening if you compare mintty to cmd. However, cmd and ConEmu are really not "every other term", cmd is not a terminal at all and that may be part of the issue, mentioning ConPTY support.
I leave you at guessing what that is, as fuzzy as your report is.

**Comment by mintty** [comment] 2020-12-23 23:33
> Best thing is to provide a file which, when output with cat, demonstrate your issue.

By using some kind of logging, which can be done. Either by mintty, screen etc.

**Comment by mintty** [comment] 2020-12-29 17:52
This has been explained on the cygwin mailing list, with a workaround. Closing here.

**Closed by mintty** 2020-12-29 17:52 UTC
Labels: invalid, obscure

**Comment by bakoontz** [comment] 2020-12-31 19:59
@mintty Have a link?  I searched the 2020 cygwin archives but no hits...

**Comment by mintty** [comment] 2021-01-01 17:11
https://sourceware.org/pipermail/cygwin/2020-December/247165.html

**Comment by eabase** [comment] 2021-01-02 07:15
@mintty 
> Yet I do in fact have an idea what might be happening if you compare mintty to cmd.

And what is that? It would be good to know, just in case, as I have had various problems with powershell & terminal characters on Win10.

**Comment by mintty** [comment] 2021-01-02 11:39
I have no hint beyond the linked information and the suggestion it may be related to ConPTY.
If you'd like me to do my own analysis, you'd have to provide me with a reproducible test case that does not require me to install 3rd-party software first (Maven).

**Comment by bakoontz** [comment] 2021-01-04 16:25
Just a follow-up note for others who might stumble on this issue:

The cygwin ML link recommends using jansi-2.1.1.jar.  Except that jar is not available in the jansi downloads.  The latest jar (jansi-2.1.0.jar) seems to be broken in the Cygwin environment (throws an exception). However, jansi-2.0.1.jar works nicely and solves the problem.
