### ISSUE TITLE
Long line continues on the *same* line instead of wrapping to the next

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#377] opened 2015-06-04 13:04 UTC
```
Steps to reproduce.

I haven't got the slightest idea how to reproduce it, but *after a while* the 
problem always resurfaces, even if I don't do anything special.

Environment.

* Windows 7 (with every possible updates available)
* mintty 1.1.2
* cygwin 1.7.17 (with every possible updates available)

(However, the problem to be described isn't new to me at all, so it's possible 
that other versions would produce the same problem.)

Other information.

I've attached a screenshot which shows my problem. After I use mintty for 
5/10/X minutes and I start writing a long line then mintty (or maybe something 
else entirely) instead of wrapping it just starts to *overwrite* the characters 
from the start of the same line.

Sorry if this is confusing it's hard for me to put this into words, this is 
something one has to see, but I hope that I was able to catch the *essence* of 
my problem.

Now I haven't got the faintest idea what could cause this. Sometimes I only use 
Vim from the command line for a short time and nothing else and the same 
happens. Sometimes I work for hours with Git, Maven, Vim, Subversion, etc. 
without this annoyance even coming up once.

One thing I always use is Bash's incremental/reverse search thingy 
(reverse-i-search, Ctrl-R). Most of the time I realize that long lines aren't 
wrapped anymore is when I use this feature: when I'm searching and I *hit* a 
long line it doesn't get wrapped.

When this happens I have to restart mintty to be able to use it again because 
it's just too much annoying that I can't see the start of my lines sometimes.

I'm not sure if this problem is new, but I didn't find anything searching 
through open/closed tickets (hard to find a keyword for *this*).

Please, if more information is needed to get to the bottom of this then please 
tell what. I'm willing to do anything to solve this (if you tell me to 
pay/donate some dough, then I'll will - I didn't found a donate button anywhere 
around tho') , because I use mintty/cygwin daily and this annoyance can ruin my 
whole day.



```

Original issue reported on code.google.com by `kohanyi....@gmail.com` on 14 Mar 2013 at 12:44

Attachments:
* [a.png](https://storage.googleapis.com/google-code-attachments/mintty/issue-377/comment-0/a.png)

**Comment by mintty** [comment] 2015-06-23 12:01
Try to log mintty output (run mintty -l logfile) until the issue occurs.
Then we can try to reproduce it with the tail of the logfile, cross-check with xterm, etc.

**Comment by mintty** [comment] 2015-09-04 12:55
I see a few cases that can create this problem:
* The shell not having the proper idea of the screen dimensions. This frequently happens if you resize the terminal window while in a program, then return to the shell. Diagnostic information needed: stty size.
* The shell not having the proper idea of the current cursor position, e.g. caused by a misconfigured prompt (-> 191). Diagnostic information needed: terminal log (mintty -l log).
* The terminal having run into a special state, e.g. a scrolling region set up by a program and not reset. Diagnostic information needed: terminal log (mintty -l log).
* The shell running in a locale not matching the terminal character encoding, e.g. setting LC_ALL=de_DE inside bash inside a UTF-8 terminal. Diagnostic information needed: locale charset, value of Options... -> Text -> Character set.

Unless someone provides further debugging info, I will close the issue soon.

**Closed** 2015-10-20 14:41 UTC

**Comment by math2001** [comment] 2017-09-08 01:33
I'd like to help :slightly_frowning_face:.

- The `stty size` does get updated, it just outputs `y` before `x`. It *does* get updated on resize.
- (this one sounds likely to me) log bellow
- Log bellow 
- In my case, I just set the PS1 to this `PS1='\033[1;33m>\033[0m '` (from [here](http://tldp.org/HOWTO/Bash-Prompt-HOWTO/nonprintingchars.html)). Is there any other way that this sequence can be inserted? I've disabled my .bashrc (just renamed) it, set the PS1 to the one above, and I still got this issue.
- My encoding settings: `en_US` and `UTF-8`

---

It works properly if there isn't any escape sequence in `PS1` though.

**Comment by mintty** [comment] 2017-09-08 06:36
Please look at the last example in the doc you quoted: escape sequences in PS1 must be embedded in `\[`...`\]` to prevent their accounting for the line length. (This is the second item in my previous comment above.)

**Comment by jedmao** [comment] 2019-01-25 04:51
Same issue. Fixed it by changing my custom/broken `PS1` to the following in `.bashrc` on Windows 10:
```ini
PS1='\[\033[35m\]$(shortwd)\[\033[36m\]$(git_branch)\[\033[0m\]$'
#    |   pink   |   pwd    |  green   |  __git_ps1  |  white  |$
```
Where `shortwd` is a short working directory:
```bash


function shortwd() {
    num_dirs=3
    pwd_symbol="..."
    newPWD="${PWD/#$HOME/~}"
    if [ $(echo -n $newPWD | awk -F '/' '{print NF}') -gt $num_dirs ]; then
        newPWD=$(echo -n $newPWD | awk -F '/' '{print $1 "/.../" $(NF-1) "/" $(NF)}')
    fi
    echo -n $newPWD
}
```

And `git_branch` is self-explanatory:

```bash
git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
```

Looks great now!

![image](https://user-images.githubusercontent.com/1058243/51725935-724ee880-202a-11e9-8cff-da8ea415ceb5.png)

**Comment by BrianInglis** [comment] 2019-01-25 05:50
bash PS1 wd is \w, short wd is \W, both use ~ tilde - I use \W in the prompt and \w in the window title with  PS1="\[\e]0;\u@\h ${debian_chroot:+($debian_chroot) }\w\a\]..."
