### ISSUE TITLE
mintty does not show/handle german umlauts on Windows 10

### ISSUE THREAD

**Issue by micmartin** [mintty/mintty#498] opened 2015-12-03 06:51 UTC
If I type special characters like 'ä', 'ö' or 'ü' on my german keyboard under Windows 10, they are not displayed. Also if I do a file listing (ls) files or folders with these characters they are show as '?'.
If I use the same binaries on machines with Windows 7 or 8.1 erverything works fine.

**Comment by mintty** [comment] 2015-12-03 09:07
What is the output of `locale`? `uname -a`? Which font do you use?

**Comment by micmartin** [comment] 2015-12-03 09:26
$ locale
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

$ uname -a
CYGWIN_NT-10.0-WOW COMPUTERNAME 2.3.1(0.291/5/3) 2015-11-14 12:42 i686 Cygwin

Font is "Consolas" on every machine.

The output of "locale" on my Windows 7 machine is
$ locale
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_ALL=

So I think that point into the right direction.
After adding exports for these entries to my .bashrc everything works fine. But the question is, why it works on Windows 7/8.1 without the "exports"?

**Comment by mintty** [comment] 2015-12-03 10:19
Is any specific character set configured for mintty? (Options – Text – Locale / Character set)
Does the font actually look like Consolas (compare with other installation)? (A substitute would be used if Consolas is configured but not installed)
Output of `stty -a`?

**Comment by micmartin** [comment] 2015-12-03 10:45
Windows 10
$ stty -a
speed 38400 baud; rows 50; columns 150; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = ^Z; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -tostop echoctl echoke

Windows 7
$ stty -a
speed 38400 baud; rows 50; columns 150; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = ^Z; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc ixany imaxbel
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -tostop echoctl echoke

Text options:
![text-options](https://cloud.githubusercontent.com/assets/5081699/11558471/4e27bd66-99b3-11e5-9f5a-9a97e488a817.png)

**Comment by micmartin** [comment] 2015-12-03 11:06
Will try to reproduce the problem on a clean Windows 10 installation.

**Comment by mintty** [comment] 2015-12-03 12:06
Last suspicion for now: Do you start mintty in some specific custom way? Maybe using a cygwin script already? It would be useful to find out the locale that is set before mintty is started. If you set the shell locale to some different value (was C.UTF-8 in your case before the patch), mintty will not respect that and the problem is hard to identify...
Setting de_DE.UTF-8 now in .bashrc might affect the starting procedure already, hence the working fix.

**Comment by micmartin** [comment] 2015-12-03 12:47
I think I found the reason: If I start mintty.exe with parameter "-" the locals are set correct.
C:\Cygwin\bin\mintty.exe -
Found this while inventigation the shortcuts on the different machines.
Without the minus character also the other machines with Windows 7/8.1 have problems with umlauts.

**Comment by mintty** [comment] 2015-12-03 14:16
Usually, when starting mintty without parameters from the desktop, the environment will not be set up properly with all sorts of resulting inconveniences but not exactly this one – non-ASCII characters still work fine here. I'd like to find the precise reason for that. Do you have specific custom versions of any of /etc/profile, ~/.profile, ~/.bash_profile, ~/.bash_login, ~/.bashrc and could you send or attach them?

**Comment by micmartin** [comment] 2015-12-03 15:41
[CygwinFiles.zip.txt](https://github.com/mintty/mintty/files/50991/CygwinFiles.zip.txt)

**Comment by mintty** [comment] 2015-12-03 16:31
Thanks, but that didn't reveal anything special. How do you start mintty? From a desktop shortcut? The default shortcut installed by Cygwin setup? That wouldn't have had the "-" missing, I guess, so if anything else, please describe exactly.

**Comment by micmartin** [comment] 2015-12-04 08:06
Installer created this shortcut: C:\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -
This shortcut works and the locale settings are fine.
I created my own shortcut and there the hyphen at the end was missing and in that case the locale settings where not set correctly. This is also the case if you start mintty by double click in file explorer.

**Comment by mintty** [comment] 2015-12-04 12:07
I am still puzzled. I can also create my shortcut, from \cygwin\bin, from desktop (how did you?) and the PATH will not work and locale is C.UTF-8 but ö works anyway.
What's your output of `chcp.com`?

**Comment by micmartin** [comment] 2015-12-04 12:32
I have codepage 850.
If you like you can close that issue, the solution with the hyphen is fine for me.

**Comment by ElvenSpellmaker** [comment] 2015-12-20 16:00
How are you setting up your locale? The dash `-` denotes a log-in shell which does different things than a normal interactive non-log-in shell.

From `man bash`:
> A login shell is one whose first character of argument zero is a -, or one started
> with the --login option.

And then further down:

> When  bash is invoked as an interactive login shell, or as a non-interactive shell
> with the --login option, it first  reads  and  executes  commands  from  the  file
> /etc/profile,  if  that  file  exists.   After  reading  that  file,  it looks for
> ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and  exe‐
> cutes  commands  from  the first one that exists and is readable.  The --noprofile
> option may be used when the shell is started to inhibit this behavior.

Therefore if you're relying on `.bash_profile` to set up some of your profile settings or if mintty passes on some of its settings to bash when it's a log-in shell (does it?) then that'd explain it.

**Comment by micmartin** [comment] 2015-12-21 06:24
I have this line in my ~/.profile file

export LANG=$(locale -uU)

This seems to set my local settings to the correct value.

**Comment by mintty** [comment] 2015-12-21 10:20
Thanks for further suggesting how to *fix* this problem.
However, as I still have no information how to *reproduce* the problem in the first place, I will simply close the issue next year :)

**Comment by ElvenSpellmaker** [comment] 2015-12-22 00:01
I think you're misunderstanding, @mintty. There is actually no problem as such I don't think.
Basically how to *reproduce* the 'problem' is to put things in your `.profile` file and then run a non-login-shell, which behaves as expected and doesn't load any of the profile files I mentioned above and so nothing in those files will get executed.

@micmartin was relying on his `.profile` file for his `LANG` settings and `.profile` isn't called on a non-log-in shell, which is one without the `-` which means that his `LANG` settings weren't being set-up as expected.

Unless mintty doesn't come with the dash `-` by default on Windows 10 entries then there is no bug, just a confusion over what is loaded by an interactive log-in shell vs an interactive non-log-in shell.

For extra information:
 * `bash` for example has the command `shopt login_shell` to tell you if you are running as a log-in shell or not. (It appears to be slightly broken in Cygwin in that if this variable is in the `off` state it generates an extra new line.)
 * Also if argument `0` to `bash` is `-bash` then `echo $0` will produce `-bash` instead of `bash`. This doesn't happen with `bash --login` even though it makes bash a log-in shell as `--login` is argument **1** and not **0**.
 * To pass an argument `0` to a programme one can use the `exec` built-in to bash:
  * `exec -l bash` or
  * `exec -a -bash bash` or
  * `exec -a - bash`, etc.
 * All of the above is possible in other shells with different commands.

**Comment by mintty** [comment] 2015-12-22 04:22
Sure there is no bug with dash – there is none without dash either for me, that's the point.
I had checked the OP's bash init scripts (attached above) and tried various combinations to reproduce the reported phenomenon, to no avail. Your comment wasn't helpful either to demonstrate it.

**Comment by ElvenSpellmaker** [comment] 2015-12-22 13:14
OK, here are the actual reproduction steps then:
 1. Go to mintty's options and go to the `Text` option and *clear* both the `Locale` and `Character set` (not choosing default, actually clearing them).
 * `export LC_ALL=C.UTF-8`
 * `export LC_ALL=`
 * `export LANG=`
 * Clear your `.inputrc`
This sets up your environment similar to his as shown above.

Now if you try to enter characters other than ASCII it'll not enter them and the terminal won't show the characters either.
Blank `LANG` and `LC_ALL`:
![blanklang](https://cloud.githubusercontent.com/assets/2286713/11954875/261c3248-a8a4-11e5-8bf1-3fc297da3c84.PNG)
`en_GB.UTF-8` settings using log-in shell:
![engblang](https://cloud.githubusercontent.com/assets/2286713/11954886/359e7b9a-a8a4-11e5-96a8-f697e938c9ea.PNG)
`en_GB.UTF-8` settings on non-log-in shell:
![engblangnon-login-shell](https://cloud.githubusercontent.com/assets/2286713/11955889/c1fc32d6-a8ad-11e5-803d-5a1b46bd329f.png)

This isn't a problem, it's just how `locale` and `bash` work, and the above instructions reproduce this behaviour.

**Comment by mintty** [comment] 2015-12-22 14:00
No, they don't:
```
~> LC_CTYPE=C.UTF-8 LC_ALL= LANG= sh
~> ls ~/.inputrc
ls: cannot access /cygdrive/d/home/.inputrc: No such file or directory
~> ls test
Привет
~> echo höẃ
höẃ
```
Only an explicit `set convert-meta on` in .inputrc spoils input and maybe some other junk setting (but which?) would spoil output too. Anyway, obviously not a mintty issue.

**Closed** 2015-12-22 17:11 UTC

**Comment by ElvenSpellmaker** [comment] 2015-12-25 12:28
Odd for you that it doesn't happen if you mimic what I did above exactly. Did you ensure the `locale` and `character set` are blanked out so that mintty isn't enforcing another character set? That might need a new terminal after clearing those settings depending on how mintty works. (No idea how it does its locale settings).

*Either way*, as said in my first post, it's not an issue at all, it's just how bash works. =)
