### ISSUE TITLE
Better support for git: Auto-login

### ISSUE THREAD

**Issue by KSXGitHub** [mintty/mintty#481] opened 2015-10-07 15:57 UTC
Dear Mintty developers,
I'm using Windows 10 and I installed GitHub Desktop. Mintty makes many convenient with its nice graphic and helpful features. Because of that, I want to open Git Shell by Mintty. However, when I `git push`, it ask me for password, but I can't type anything after that (it also happens when I open cmd or powershell directly but everything is fine if I open them by Git Shell shortcut).
So, it would be great if Mintty supports all features that Git Shell needs.

**Comment by mintty** [comment] 2015-10-07 17:26
The symptom typically arises from an incompatibility of different input techniques as used by Windows programs, console-based programs, or on the other hand cygwin programs running in pty-based terminals.
I guess you are running a mix of software from the various worlds, e.g. a cygwin mintty and a Windows git command line program. Git for Windows comes with its own adaptation of mintty; using that this should not happen (or if it does, file a bug with Git). Alternatively, you could run cygwin mintty *and* cygwin git and that would run nicely, too.

**Comment by mintty** [comment] 2015-10-07 17:29
(Didn't understand your original report title and changed that.)
This is likely to be a duplicate of #56.

**Comment by KSXGitHub** [comment] 2015-10-08 04:16
The new title doesn't describes what I really want. And so, I think you didn't understand me.

The issue **is not password input** - which is also not fine in `cmd`, `powershell` and even GitHub's own `bash` - that is: cannot enter account login information. So, password input **is not your issue** and you needn't fix that, instead, GitHub or Microsoft should does.

The really issue is: When I open Git Shell by clicking Git Shell shortcut (`C:\Users\<username>\AppData\Local\GitHub\GitHub.appref-ms --open-shell`), although it automatically logins to my account (branch master) when I used `cmd`, `powershell` or GitHub's `bash` for Git Shell (change settings in GitHub Desktop GUI), Mintty doesn't. So, what I request is: support to automatically login user's GitHub account.

**Comment by mintty** [comment] 2015-10-08 06:52
OK, so this is not even a mintty issue at all, I'm pretty sure. Mintty never logs in into anything, that's the task of other software. It's a matter of what command is invoked inside mintty, so it's a Git configuration issue.
Closing.

**Closed by mintty** 2015-10-08 06:52 UTC

**Comment by KSXGitHub** [comment] 2015-10-08 11:12
Why do you think that is only GitHub's issue?

> It's a matter of what command is invoked inside mintty

Yes, but that commands is invoked already:

I also test Git Shell with Python shell, Powershell and even Console 2 (another console emulator like mintty). All them work fine! They show the message `Everything up-to-date` instead of ask me password.

![image](https://cloud.githubusercontent.com/assets/11488886/10364398/28971622-6de5-11e5-896a-0230e78dd76c.png)

Then I try again with mintty, I tried many method: open mintty directly (set GitHub options --> default shell a link point directly to mintty), open cmd/powershell then use cmd/powershell to open mintty. I expect the message `Everything up-to-date` but it asks me password which I'm not able to give.

![image](https://cloud.githubusercontent.com/assets/11488886/10364536/6b62a196-6de6-11e5-9efb-ba3618a6b125.png)

I think it's actually an issue of your `bash` because when I use cmd to open your bash, I see the result below:

![image](https://cloud.githubusercontent.com/assets/11488886/10364598/11d98ada-6de7-11e5-94d1-df19704d831c.png)

Can you explain why Console2 do it well but Mintty doesn't?

Finally, if you also manage `bash` and this is actually an issue of your `bash`, resolve this issue (or support more features). But if you don't manage `bash` or there was a technical limit, leave this issue closed.

**Comment by mintty** [comment] 2015-10-08 12:35
First, your comment confirms that this is not a mintty issue as the problem occurs in the 3rd screenshot without mintty being involved.
Then, it's not "my bash". Bash is an application that can run inside mintty or any other terminal or console emulator, or even without.
What likely happens is that you somehow get a different environment configured depending on how you start. You may compare the following in both environments.
```
echo $HOME # to check whether your .git configuration is found
type git # to check whether you're running the same git installation
mount # to check whether you're really running the same git installation
```
You may also want to cross-check calling `mintty -` with an explicit `-` parameter to enforce starting a login shell.
Feedback welcome.

**Comment by mintty** [comment] 2019-12-16 23:45
Cygwin 3.1.0 has been released with ConPTY support.
