### ISSUE TITLE
mintty 2.7.4: Gap between last line and window border increased

### ISSUE THREAD

**Issue by kgraefe** [mintty/mintty#631] opened 2017-02-14 11:08 UTC
When running mintty in fullscreen, the gap between the last line and the window border was increased with version 2.7.4. I am running on Windows 10 with the default theme and a screen resolution of `1920x1080`.

Again, I'd blame commit cd5ec9e1e34ff41eabc46e6205dd57ca834349e9 for this. What is the purpose of this commit? What are the parameters the automatic metric is based on? Unfortunately this is hard to get from the commit message (and the source code). :-( 

I like the idea of changing the font metrics so that things fit perfectly into the viewport. But if that was the purpose, it is not working for me. Furthermore, I get 11 lines less in the newer version compared to mintty 2.7.3 (should I open a new issue for that?).

Screenshots (sorry for the size):
- mintty 2.7.3:
![mintty1](https://cloud.githubusercontent.com/assets/3797324/22926667/e6050d56-f2ad-11e6-9130-1a9091de71aa.PNG)
- mintty 2.7.4 (2cc746667595e08f57b12cfa0df0b67787762620): 
![mintty2](https://cloud.githubusercontent.com/assets/3797324/22926671/eaab7430-f2ad-11e6-947c-2ed008c560bb.png)

**Comment by mintty** [comment] 2017-02-14 12:06
Background:
Some fonts appear with strange row spacing proportions when layed out simply based on their character height, as mintty used to do. Examples are Courier and FreeMono, which look squeezed vertically, and Monaco which looks inappropriately stretched vertically.
However, the font contains information about advisable "leading" to be applied. (Windows provides this information in the TEXTMETRIC API.)
Mintty considers leading values for row spacing since 2.2.4. This used to break line drawing, so I limited the adjustment to the negative case (e.g. for Monaco) in 2.3.6. After I had changed VT100 line drawing graphics to be drawn manually in 2.4.0, I removed the limitation again in 2.7.4, not considering the case of Unicode box drawing characters, which I've fixed now for 2.7.5.

The change of 2.7.4 should only be effective for those fonts like Courier and FreeMono that would otherwise be somewhat squeezed. Do you use one of them? And yes, of course that means the whole window geometry and terminal size is affected, that's not a bug.
And in fullscreen mode, if the pixel size does not happen to be evenly divisible by the row height, there will be a few padding pixels, that's also not a bug; you would have seen such padding before as well, with other font/size combinations.

**Comment by kgraefe** [comment] 2017-02-14 13:10
Thank you for your explanation. It makes sense now.

Do you see any chance to add an option to disable the new behavior (e.g. via configuration file)?

Otherwise I guess the correct fix for me would be to change font itself (for the record: `Lucida Console 10pt`). :-\

**Comment by mintty** [comment] 2017-02-14 13:18
A workaround is to compensate the effect with option `RowSpacing`.
Actually, I thought the new behaviour to be a good idea. Would you motivate a bit why you think it should be possible to disable it?

**Comment by kgraefe** [comment] 2017-02-14 13:36
`RowSpacing=-2` resolves the issue for me, thank you. I did not know about this option.

I guess there is no need for yet another option. But since you asked, the reasons why it bothered me are:
- Obviously I was not affected by squeezed fonts beforehand.
- The space at the bottom of the window did not occur before the change, because my font magically fits my screen resolution (and mintty adapts the window size to the lines, when not maximized).
- Less lines displayed is not cool (though not too important, sure).

**Closed** 2017-02-15 11:28 UTC

**Comment by mintty** [comment] 2017-03-11 21:13
Mentioned in Wiki: https://github.com/mintty/mintty/wiki/Tips#font-rendering-and-geometry

**Comment by feryardiant** [comment] 2018-09-10 09:39
In my case it's solved by adding `Padding=0` because IMO it's looks weird when I use `RowSpacing=-2`, I mean the font height isn't look good on my setup.

**Comment by mintty** [comment] 2019-12-17 17:31
Just noticed, this is a duplicate of #323.
