### ISSUE TITLE
Please revert cd5ec9e1 (increased row padding) or at least make it configurable

### ISSUE THREAD

**Issue by wmwdld** [mintty/mintty#632] opened 2017-02-17 18:00 UTC
I don't like or want extra padding.  It makes the window too large.  And I really don't appreciate upgrading to a point release and having a major visual change that requires me to stop everything I'm doing and revert to a previous version before I can continue working.

**Comment by mintty** [comment] 2017-02-17 19:27
I could start to tell about incompatible changes in other software that I did not appreciate, like grep or firefox, and sometimes they came rather hidden. That is not an argument to discuss changes.
Also I am not aware of widely-acknowledged rules about what to change with minor vs. major version. Every project has their own practice, and some don't distinguish version levels at all.
I think a major version should come with established functionality, and preferably not introduce bugs; with this point of view, it would be previous minor versions to try out changes.

**Comment by mintty** [comment] 2017-02-17 19:33
Now about the issue: It's a duplicate of #631; see https://github.com/mintty/mintty/issues/631#issuecomment-279690468 for an explanation which was accepted there. It's actually not new behaviour because it was introduced in 2.2.4 already. The change had just been suspended (in 2.3.6) to avoid unpleasant interworking effects which now don't occur anymore.
Also the change does not make windows too large. It rather adjusts windows that used to be too small.
Please check the compensation option presented in #631 whether that's sufficient.
Based on these clarifications we can discuss the issue further if you feel the need.

**Comment by wmwdld** [comment] 2017-02-18 02:27
Thanks for the quick reply.  The `RowSpacing=-2` thing works great to get the old behavior back.  I understand now that the font is requesting the extra space and that that is probably the desirable behavior.  Thanks for taking the time to explain, and next time I'll have some coffee or something before writing a bug report.

**Comment by mintty** [comment] 2017-03-11 21:12
Improved Wiki: https://github.com/mintty/mintty/wiki/Tips#font-rendering-and-geometry

**Closed by mintty** 2017-03-11 21:12 UTC
Labels: duplicate

**Comment by mintty** [comment] 2021-03-24 05:12
Released 3.4.7 with new heuristics for auto-adjustment of line spacing.
