### ISSUE TITLE
Closing mintty leaves ssh process running

### ISSUE THREAD

**Issue by xnoreq** [mintty/mintty#1061] opened 2020-11-18 16:54 UTC
Using the mintty and ssh shipped with Git for Windows.

If I run ssh and close mintty then the ssh process will keep running in the background.
What is the reason for this?

**Comment by xnoreq** [comment] 2020-11-18 17:01
Ok, seems to be due to the bash used in Git for Windows. Doesn't happen with MSYS2 binaries.

**Comment by mintty** [comment] 2020-11-18 17:21
Sounds like the opposite of #747, and could be a duplicate of #674.
Works for me in cygwin, on the other hand.

**Comment by xnoreq** [comment] 2020-11-18 17:59
Actually, I have just tried a fresh MSYS2 installation and I'm also using mintty TERM=xterm-256color and I get the same behavior of ssh not exiting.

**Comment by xnoreq** [comment] 2020-11-18 18:08
After a couple of retries it appears to be randomly, though mostly fails.

Starting `mintty.exe -- /usr/bin/bash --login -i` which also starts conhost, then ssh (which gets its key from ssh-agent which was started in a previous session), then close mintty.

Now closing mintty leaves the conhost and mintty processes running. Upgrading mintty, bash, ncurses .. doesn't fix it.

**Comment by mintty** [comment] 2020-11-18 18:44
Please cross-test with a different terminal, like xterm. I assume behaviour will be the same and it's not a mintty issue.

**Comment by xnoreq** [comment] 2020-11-18 19:12
I've tried with WIndows' cmd several times and it never failed.

**Comment by mintty** [comment] 2020-11-18 19:21
Windows cmd is not a terminal. To be more precise, please test with another cygwin-based terminal (will need an X server too). The background is that I suspect it to be related to the pty issues / ConPTY support.

**Comment by xnoreq** [comment] 2020-11-23 19:27
I'm pretty sure cmd spawns a terminal.
I tested with Cygwin and it didn't see it happening there, but since mintty supports MSYS2 this is an issue.

**Comment by mintty** [comment] 2020-11-23 20:16
This suggests it may be related to a pty issue. MSYS2 used to disable ConPTY support. Which version of MSYS2 do you run and what's the value of the environment variable CYGWIN or probably MSYS or MSYS2? If your environment contains `disable_pcon` in any of them, clear that variable and run another mintty from there for testing.

**Comment by k-takata** [comment] 2020-11-24 05:57
MSYS2 still disables ConPTY by default. To enable ConPTY on MSYS2, the `MSYS=enable_pcon` environment variable should be set.

**Comment by mintty** [comment] 2020-12-12 19:22
Closing as not caused by mintty.

**Closed by mintty** 2020-12-12 19:22 UTC
